// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: investment.proto

package investment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MarketType int32

const (
	MarketType_MARKET_TYPE_UNSPECIFIED    MarketType = 0
	MarketType_MARKET_TYPE_A_SHARE        MarketType = 1 // A股
	MarketType_MARKET_TYPE_HK_STOCK       MarketType = 2 // 港股
	MarketType_MARKET_TYPE_US_STOCK       MarketType = 3 // 美股
	MarketType_MARKET_TYPE_CRYPTO         MarketType = 4 // 加密货币
	MarketType_MARKET_TYPE_FUND           MarketType = 5 // 基金
	MarketType_MARKET_TYPE_PRECIOUS_METAL MarketType = 6 // 贵金属
)

// Enum value maps for MarketType.
var (
	MarketType_name = map[int32]string{
		0: "MARKET_TYPE_UNSPECIFIED",
		1: "MARKET_TYPE_A_SHARE",
		2: "MARKET_TYPE_HK_STOCK",
		3: "MARKET_TYPE_US_STOCK",
		4: "MARKET_TYPE_CRYPTO",
		5: "MARKET_TYPE_FUND",
		6: "MARKET_TYPE_PRECIOUS_METAL",
	}
	MarketType_value = map[string]int32{
		"MARKET_TYPE_UNSPECIFIED":    0,
		"MARKET_TYPE_A_SHARE":        1,
		"MARKET_TYPE_HK_STOCK":       2,
		"MARKET_TYPE_US_STOCK":       3,
		"MARKET_TYPE_CRYPTO":         4,
		"MARKET_TYPE_FUND":           5,
		"MARKET_TYPE_PRECIOUS_METAL": 6,
	}
)

func (x MarketType) Enum() *MarketType {
	p := new(MarketType)
	*p = x
	return p
}

func (x MarketType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MarketType) Descriptor() protoreflect.EnumDescriptor {
	return file_investment_proto_enumTypes[0].Descriptor()
}

func (MarketType) Type() protoreflect.EnumType {
	return &file_investment_proto_enumTypes[0]
}

func (x MarketType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MarketType.Descriptor instead.
func (MarketType) EnumDescriptor() ([]byte, []int) {
	return file_investment_proto_rawDescGZIP(), []int{0}
}

type TradeType int32

const (
	TradeType_TRADE_TYPE_UNSPECIFIED TradeType = 0
	TradeType_TRADE_TYPE_BUY         TradeType = 1
	TradeType_TRADE_TYPE_SELL        TradeType = 2
)

// Enum value maps for TradeType.
var (
	TradeType_name = map[int32]string{
		0: "TRADE_TYPE_UNSPECIFIED",
		1: "TRADE_TYPE_BUY",
		2: "TRADE_TYPE_SELL",
	}
	TradeType_value = map[string]int32{
		"TRADE_TYPE_UNSPECIFIED": 0,
		"TRADE_TYPE_BUY":         1,
		"TRADE_TYPE_SELL":        2,
	}
)

func (x TradeType) Enum() *TradeType {
	p := new(TradeType)
	*p = x
	return p
}

func (x TradeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TradeType) Descriptor() protoreflect.EnumDescriptor {
	return file_investment_proto_enumTypes[1].Descriptor()
}

func (TradeType) Type() protoreflect.EnumType {
	return &file_investment_proto_enumTypes[1]
}

func (x TradeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TradeType.Descriptor instead.
func (TradeType) EnumDescriptor() ([]byte, []int) {
	return file_investment_proto_rawDescGZIP(), []int{1}
}

type Investment struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId           string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Symbol           string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"` // 代码 (600519, AAPL, BTC)
	Name             string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`     // 名称
	MarketType       MarketType             `protobuf:"varint,5,opt,name=market_type,json=marketType,proto3,enum=familyledger.investment.v1.MarketType" json:"market_type,omitempty"`
	Quantity         float64                `protobuf:"fixed64,6,opt,name=quantity,proto3" json:"quantity,omitempty"`                                          // 持有数量
	CostBasis        int64                  `protobuf:"varint,7,opt,name=cost_basis,json=costBasis,proto3" json:"cost_basis,omitempty"`                        // 成本（分）
	CurrentValue     int64                  `protobuf:"varint,8,opt,name=current_value,json=currentValue,proto3" json:"current_value,omitempty"`               // 当前市值（分）
	TotalReturn      float64                `protobuf:"fixed64,9,opt,name=total_return,json=totalReturn,proto3" json:"total_return,omitempty"`                 // 总收益率
	AnnualizedReturn float64                `protobuf:"fixed64,10,opt,name=annualized_return,json=annualizedReturn,proto3" json:"annualized_return,omitempty"` // 年化收益率
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	FamilyId         string                 `protobuf:"bytes,13,opt,name=family_id,json=familyId,proto3" json:"family_id,omitempty"` // 家庭 ID（空 = 个人投资）
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Investment) Reset() {
	*x = Investment{}
	mi := &file_investment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Investment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Investment) ProtoMessage() {}

func (x *Investment) ProtoReflect() protoreflect.Message {
	mi := &file_investment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Investment.ProtoReflect.Descriptor instead.
func (*Investment) Descriptor() ([]byte, []int) {
	return file_investment_proto_rawDescGZIP(), []int{0}
}

func (x *Investment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Investment) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Investment) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Investment) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Investment) GetMarketType() MarketType {
	if x != nil {
		return x.MarketType
	}
	return MarketType_MARKET_TYPE_UNSPECIFIED
}

func (x *Investment) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Investment) GetCostBasis() int64 {
	if x != nil {
		return x.CostBasis
	}
	return 0
}

func (x *Investment) GetCurrentValue() int64 {
	if x != nil {
		return x.CurrentValue
	}
	return 0
}

func (x *Investment) GetTotalReturn() float64 {
	if x != nil {
		return x.TotalReturn
	}
	return 0
}

func (x *Investment) GetAnnualizedReturn() float64 {
	if x != nil {
		return x.AnnualizedReturn
	}
	return 0
}

func (x *Investment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Investment) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Investment) GetFamilyId() string {
	if x != nil {
		return x.FamilyId
	}
	return ""
}

type InvestmentTrade struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	InvestmentId  string                 `protobuf:"bytes,2,opt,name=investment_id,json=investmentId,proto3" json:"investment_id,omitempty"`
	TradeType     TradeType              `protobuf:"varint,3,opt,name=trade_type,json=tradeType,proto3,enum=familyledger.investment.v1.TradeType" json:"trade_type,omitempty"`
	Quantity      float64                `protobuf:"fixed64,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         int64                  `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`                                // 成交价（分/股）
	TotalAmount   int64                  `protobuf:"varint,6,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"` // 总金额（分）
	Fee           int64                  `protobuf:"varint,7,opt,name=fee,proto3" json:"fee,omitempty"`                                    // 手续费（分）
	TradeDate     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=trade_date,json=tradeDate,proto3" json:"trade_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvestmentTrade) Reset() {
	*x = InvestmentTrade{}
	mi := &file_investment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvestmentTrade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvestmentTrade) ProtoMessage() {}

func (x *InvestmentTrade) ProtoReflect() protoreflect.Message {
	mi := &file_investment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvestmentTrade.ProtoReflect.Descriptor instead.
func (*InvestmentTrade) Descriptor() ([]byte, []int) {
	return file_investment_proto_rawDescGZIP(), []int{1}
}

func (x *InvestmentTrade) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InvestmentTrade) GetInvestmentId() string {
	if x != nil {
		return x.InvestmentId
	}
	return ""
}

func (x *InvestmentTrade) GetTradeType() TradeType {
	if x != nil {
		return x.TradeType
	}
	return TradeType_TRADE_TYPE_UNSPECIFIED
}

func (x *InvestmentTrade) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *InvestmentTrade) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *InvestmentTrade) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *InvestmentTrade) GetFee() int64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *InvestmentTrade) GetTradeDate() *timestamppb.Timestamp {
	if x != nil {
		return x.TradeDate
	}
	return nil
}

type MarketQuote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	MarketType    MarketType             `protobuf:"varint,3,opt,name=market_type,json=marketType,proto3,enum=familyledger.investment.v1.MarketType" json:"market_type,omitempty"`
	CurrentPrice  int64                  `protobuf:"varint,4,opt,name=current_price,json=currentPrice,proto3" json:"current_price,omitempty"`     // 当前价（分）
	Change        int64                  `protobuf:"varint,5,opt,name=change,proto3" json:"change,omitempty"`                                     // 涨跌额（分）
	ChangePercent float64                `protobuf:"fixed64,6,opt,name=change_percent,json=changePercent,proto3" json:"change_percent,omitempty"` // 涨跌幅
	Open          int64                  `protobuf:"varint,7,opt,name=open,proto3" json:"open,omitempty"`
	High          int64                  `protobuf:"varint,8,opt,name=high,proto3" json:"high,omitempty"`
	Low           int64                  `protobuf:"varint,9,opt,name=low,proto3" json:"low,omitempty"`
	PrevClose     int64                  `protobuf:"varint,10,opt,name=prev_close,json=prevClose,proto3" json:"prev_close,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketQuote) Reset() {
	*x = MarketQuote{}
	mi := &file_investment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketQuote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketQuote) ProtoMessage() {}

func (x *MarketQuote) ProtoReflect() protoreflect.Message {
	mi := &file_investment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketQuote.ProtoReflect.Descriptor instead.
func (*MarketQuote) Descriptor() ([]byte, []int) {
	return file_investment_proto_rawDescGZIP(), []int{2}
}

func (x *MarketQuote) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *MarketQuote) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MarketQuote) GetMarketType() MarketType {
	if x != nil {
		return x.MarketType
	}
	return MarketType_MARKET_TYPE_UNSPECIFIED
}

func (x *MarketQuote) GetCurrentPrice() int64 {
	if x != nil {
		return x.CurrentPrice
	}
	return 0
}

func (x *MarketQuote) GetChange() int64 {
	if x != nil {
		return x.Change
	}
	return 0
}

func (x *MarketQuote) GetChangePercent() float64 {
	if x != nil {
		return x.ChangePercent
	}
	return 0
}

func (x *MarketQuote) GetOpen() int64 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *MarketQuote) GetHigh() int64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *MarketQuote) GetLow() int64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *MarketQuote) GetPrevClose() int64 {
	if x != nil {
		return x.PrevClose
	}
	return 0
}

func (x *MarketQuote) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type PortfolioSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalValue    int64                  `protobuf:"varint,1,opt,name=total_value,json=totalValue,proto3" json:"total_value,omitempty"`     // 总市值（分）
	TotalCost     int64                  `protobuf:"varint,2,opt,name=total_cost,json=totalCost,proto3" json:"total_cost,omitempty"`        // 总成本（分）
	TotalProfit   int64                  `protobuf:"varint,3,opt,name=total_profit,json=totalProfit,proto3" json:"total_profit,omitempty"`  // 总盈亏（分）
	TotalReturn   float64                `protobuf:"fixed64,4,opt,name=total_return,json=totalReturn,proto3" json:"total_return,omitempty"` // 总收益率
	Holdings      []*HoldingItem         `protobuf:"bytes,5,rep,name=holdings,proto3" json:"holdings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortfolioSummary) Reset() {
	*x = PortfolioSummary{}
	mi := &file_investment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortfolioSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortfolioSummary) ProtoMessage() {}

func (x *PortfolioSummary) ProtoReflect() protoreflect.Message {
	mi := &file_investment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortfolioSummary.ProtoReflect.Descriptor instead.
func (*PortfolioSummary) Descriptor() ([]byte, []int) {
	return file_investment_proto_rawDescGZIP(), []int{3}
}

func (x *PortfolioSummary) GetTotalValue() int64 {
	if x != nil {
		return x.TotalValue
	}
	return 0
}

func (x *PortfolioSummary) GetTotalCost() int64 {
	if x != nil {
		return x.TotalCost
	}
	return 0
}

func (x *PortfolioSummary) GetTotalProfit() int64 {
	if x != nil {
		return x.TotalProfit
	}
	return 0
}

func (x *PortfolioSummary) GetTotalReturn() float64 {
	if x != nil {
		return x.TotalReturn
	}
	return 0
}

func (x *PortfolioSummary) GetHoldings() []*HoldingItem {
	if x != nil {
		return x.Holdings
	}
	return nil
}

type HoldingItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvestmentId  string                 `protobuf:"bytes,1,opt,name=investment_id,json=investmentId,proto3" json:"investment_id,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Quantity      float64                `protobuf:"fixed64,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	CurrentValue  int64                  `protobuf:"varint,5,opt,name=current_value,json=currentValue,proto3" json:"current_value,omitempty"`
	Weight        float64                `protobuf:"fixed64,6,opt,name=weight,proto3" json:"weight,omitempty"` // 占比 0-1
	ReturnRate    float64                `protobuf:"fixed64,7,opt,name=return_rate,json=returnRate,proto3" json:"return_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HoldingItem) Reset() {
	*x = HoldingItem{}
	mi := &file_investment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HoldingItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HoldingItem) ProtoMessage() {}

func (x *HoldingItem) ProtoReflect() protoreflect.Message {
	mi := &file_investment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HoldingItem.ProtoReflect.Descriptor instead.
func (*HoldingItem) Descriptor() ([]byte, []int) {
	return file_investment_proto_rawDescGZIP(), []int{4}
}

func (x *HoldingItem) GetInvestmentId() string {
	if x != nil {
		return x.InvestmentId
	}
	return ""
}

func (x *HoldingItem) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *HoldingItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HoldingItem) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *HoldingItem) GetCurrentValue() int64 {
	if x != nil {
		return x.CurrentValue
	}
	return 0
}

func (x *HoldingItem) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *HoldingItem) GetReturnRate() float64 {
	if x != nil {
		return x.ReturnRate
	}
	return 0
}

type PricePoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Price         int64                  `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"` // 分
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PricePoint) Reset() {
	*x = PricePoint{}
	mi := &file_investment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PricePoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PricePoint) ProtoMessage() {}

func (x *PricePoint) ProtoReflect() protoreflect.Message {
	mi := &file_investment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PricePoint.ProtoReflect.Descriptor instead.
func (*PricePoint) Descriptor() ([]byte, []int) {
	return file_investment_proto_rawDescGZIP(), []int{5}
}

func (x *PricePoint) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *PricePoint) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type SymbolInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	MarketType    MarketType             `protobuf:"varint,3,opt,name=market_type,json=marketType,proto3,enum=familyledger.investment.v1.MarketType" json:"market_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SymbolInfo) Reset() {
	*x = SymbolInfo{}
	mi := &file_investment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SymbolInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SymbolInfo) ProtoMessage() {}

func (x *SymbolInfo) ProtoReflect() protoreflect.Message {
	mi := &file_investment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SymbolInfo.ProtoReflect.Descriptor instead.
func (*SymbolInfo) Descriptor() ([]byte, []int) {
	return file_investment_proto_rawDescGZIP(), []int{6}
}

func (x *SymbolInfo) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *SymbolInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SymbolInfo) GetMarketType() MarketType {
	if x != nil {
		return x.MarketType
	}
	return MarketType_MARKET_TYPE_UNSPECIFIED
}

// InvestmentService
type CreateInvestmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	MarketType    MarketType             `protobuf:"varint,3,opt,name=market_type,json=marketType,proto3,enum=familyledger.investment.v1.MarketType" json:"market_type,omitempty"`
	FamilyId      string                 `protobuf:"bytes,4,opt,name=family_id,json=familyId,proto3" json:"family_id,omitempty"` // 家庭 ID（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInvestmentRequest) Reset() {
	*x = CreateInvestmentRequest{}
	mi := &file_investment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInvestmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInvestmentRequest) ProtoMessage() {}

func (x *CreateInvestmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_investment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInvestmentRequest.ProtoReflect.Descriptor instead.
func (*CreateInvestmentRequest) Descriptor() ([]byte, []int) {
	return file_investment_proto_rawDescGZIP(), []int{7}
}

func (x *CreateInvestmentRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *CreateInvestmentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateInvestmentRequest) GetMarketType() MarketType {
	if x != nil {
		return x.MarketType
	}
	return MarketType_MARKET_TYPE_UNSPECIFIED
}

func (x *CreateInvestmentRequest) GetFamilyId() string {
	if x != nil {
		return x.FamilyId
	}
	return ""
}

type GetInvestmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvestmentId  string                 `protobuf:"bytes,1,opt,name=investment_id,json=investmentId,proto3" json:"investment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInvestmentRequest) Reset() {
	*x = GetInvestmentRequest{}
	mi := &file_investment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInvestmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInvestmentRequest) ProtoMessage() {}

func (x *GetInvestmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_investment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInvestmentRequest.ProtoReflect.Descriptor instead.
func (*GetInvestmentRequest) Descriptor() ([]byte, []int) {
	return file_investment_proto_rawDescGZIP(), []int{8}
}

func (x *GetInvestmentRequest) GetInvestmentId() string {
	if x != nil {
		return x.InvestmentId
	}
	return ""
}

type ListInvestmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarketType    MarketType             `protobuf:"varint,1,opt,name=market_type,json=marketType,proto3,enum=familyledger.investment.v1.MarketType" json:"market_type,omitempty"` // optional filter
	FamilyId      string                 `protobuf:"bytes,2,opt,name=family_id,json=familyId,proto3" json:"family_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInvestmentsRequest) Reset() {
	*x = ListInvestmentsRequest{}
	mi := &file_investment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInvestmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInvestmentsRequest) ProtoMessage() {}

func (x *ListInvestmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_investment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInvestmentsRequest.ProtoReflect.Descriptor instead.
func (*ListInvestmentsRequest) Descriptor() ([]byte, []int) {
	return file_investment_proto_rawDescGZIP(), []int{9}
}

func (x *ListInvestmentsRequest) GetMarketType() MarketType {
	if x != nil {
		return x.MarketType
	}
	return MarketType_MARKET_TYPE_UNSPECIFIED
}

func (x *ListInvestmentsRequest) GetFamilyId() string {
	if x != nil {
		return x.FamilyId
	}
	return ""
}

type ListInvestmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Investments   []*Investment          `protobuf:"bytes,1,rep,name=investments,proto3" json:"investments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInvestmentsResponse) Reset() {
	*x = ListInvestmentsResponse{}
	mi := &file_investment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInvestmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInvestmentsResponse) ProtoMessage() {}

func (x *ListInvestmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_investment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInvestmentsResponse.ProtoReflect.Descriptor instead.
func (*ListInvestmentsResponse) Descriptor() ([]byte, []int) {
	return file_investment_proto_rawDescGZIP(), []int{10}
}

func (x *ListInvestmentsResponse) GetInvestments() []*Investment {
	if x != nil {
		return x.Investments
	}
	return nil
}

type UpdateInvestmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvestmentId  string                 `protobuf:"bytes,1,opt,name=investment_id,json=investmentId,proto3" json:"investment_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // only name can be updated
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateInvestmentRequest) Reset() {
	*x = UpdateInvestmentRequest{}
	mi := &file_investment_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateInvestmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInvestmentRequest) ProtoMessage() {}

func (x *UpdateInvestmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_investment_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInvestmentRequest.ProtoReflect.Descriptor instead.
func (*UpdateInvestmentRequest) Descriptor() ([]byte, []int) {
	return file_investment_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateInvestmentRequest) GetInvestmentId() string {
	if x != nil {
		return x.InvestmentId
	}
	return ""
}

func (x *UpdateInvestmentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteInvestmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvestmentId  string                 `protobuf:"bytes,1,opt,name=investment_id,json=investmentId,proto3" json:"investment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteInvestmentRequest) Reset() {
	*x = DeleteInvestmentRequest{}
	mi := &file_investment_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteInvestmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteInvestmentRequest) ProtoMessage() {}

func (x *DeleteInvestmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_investment_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteInvestmentRequest.ProtoReflect.Descriptor instead.
func (*DeleteInvestmentRequest) Descriptor() ([]byte, []int) {
	return file_investment_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteInvestmentRequest) GetInvestmentId() string {
	if x != nil {
		return x.InvestmentId
	}
	return ""
}

type RecordTradeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvestmentId  string                 `protobuf:"bytes,1,opt,name=investment_id,json=investmentId,proto3" json:"investment_id,omitempty"`
	TradeType     TradeType              `protobuf:"varint,2,opt,name=trade_type,json=tradeType,proto3,enum=familyledger.investment.v1.TradeType" json:"trade_type,omitempty"`
	Quantity      float64                `protobuf:"fixed64,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         int64                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"` // 成交价（分/股）
	Fee           int64                  `protobuf:"varint,5,opt,name=fee,proto3" json:"fee,omitempty"`     // 手续费（分）
	TradeDate     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=trade_date,json=tradeDate,proto3" json:"trade_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordTradeRequest) Reset() {
	*x = RecordTradeRequest{}
	mi := &file_investment_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordTradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordTradeRequest) ProtoMessage() {}

func (x *RecordTradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_investment_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordTradeRequest.ProtoReflect.Descriptor instead.
func (*RecordTradeRequest) Descriptor() ([]byte, []int) {
	return file_investment_proto_rawDescGZIP(), []int{13}
}

func (x *RecordTradeRequest) GetInvestmentId() string {
	if x != nil {
		return x.InvestmentId
	}
	return ""
}

func (x *RecordTradeRequest) GetTradeType() TradeType {
	if x != nil {
		return x.TradeType
	}
	return TradeType_TRADE_TYPE_UNSPECIFIED
}

func (x *RecordTradeRequest) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *RecordTradeRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *RecordTradeRequest) GetFee() int64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *RecordTradeRequest) GetTradeDate() *timestamppb.Timestamp {
	if x != nil {
		return x.TradeDate
	}
	return nil
}

type ListTradesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvestmentId  string                 `protobuf:"bytes,1,opt,name=investment_id,json=investmentId,proto3" json:"investment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTradesRequest) Reset() {
	*x = ListTradesRequest{}
	mi := &file_investment_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTradesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTradesRequest) ProtoMessage() {}

func (x *ListTradesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_investment_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTradesRequest.ProtoReflect.Descriptor instead.
func (*ListTradesRequest) Descriptor() ([]byte, []int) {
	return file_investment_proto_rawDescGZIP(), []int{14}
}

func (x *ListTradesRequest) GetInvestmentId() string {
	if x != nil {
		return x.InvestmentId
	}
	return ""
}

type ListTradesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trades        []*InvestmentTrade     `protobuf:"bytes,1,rep,name=trades,proto3" json:"trades,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTradesResponse) Reset() {
	*x = ListTradesResponse{}
	mi := &file_investment_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTradesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTradesResponse) ProtoMessage() {}

func (x *ListTradesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_investment_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTradesResponse.ProtoReflect.Descriptor instead.
func (*ListTradesResponse) Descriptor() ([]byte, []int) {
	return file_investment_proto_rawDescGZIP(), []int{15}
}

func (x *ListTradesResponse) GetTrades() []*InvestmentTrade {
	if x != nil {
		return x.Trades
	}
	return nil
}

type GetPortfolioSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FamilyId      string                 `protobuf:"bytes,1,opt,name=family_id,json=familyId,proto3" json:"family_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPortfolioSummaryRequest) Reset() {
	*x = GetPortfolioSummaryRequest{}
	mi := &file_investment_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPortfolioSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPortfolioSummaryRequest) ProtoMessage() {}

func (x *GetPortfolioSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_investment_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPortfolioSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetPortfolioSummaryRequest) Descriptor() ([]byte, []int) {
	return file_investment_proto_rawDescGZIP(), []int{16}
}

func (x *GetPortfolioSummaryRequest) GetFamilyId() string {
	if x != nil {
		return x.FamilyId
	}
	return ""
}

// MarketDataService
type GetQuoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	MarketType    MarketType             `protobuf:"varint,2,opt,name=market_type,json=marketType,proto3,enum=familyledger.investment.v1.MarketType" json:"market_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuoteRequest) Reset() {
	*x = GetQuoteRequest{}
	mi := &file_investment_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuoteRequest) ProtoMessage() {}

func (x *GetQuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_investment_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuoteRequest.ProtoReflect.Descriptor instead.
func (*GetQuoteRequest) Descriptor() ([]byte, []int) {
	return file_investment_proto_rawDescGZIP(), []int{17}
}

func (x *GetQuoteRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetQuoteRequest) GetMarketType() MarketType {
	if x != nil {
		return x.MarketType
	}
	return MarketType_MARKET_TYPE_UNSPECIFIED
}

type BatchGetQuotesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*GetQuoteRequest     `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetQuotesRequest) Reset() {
	*x = BatchGetQuotesRequest{}
	mi := &file_investment_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetQuotesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetQuotesRequest) ProtoMessage() {}

func (x *BatchGetQuotesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_investment_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetQuotesRequest.ProtoReflect.Descriptor instead.
func (*BatchGetQuotesRequest) Descriptor() ([]byte, []int) {
	return file_investment_proto_rawDescGZIP(), []int{18}
}

func (x *BatchGetQuotesRequest) GetRequests() []*GetQuoteRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type BatchGetQuotesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quotes        []*MarketQuote         `protobuf:"bytes,1,rep,name=quotes,proto3" json:"quotes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetQuotesResponse) Reset() {
	*x = BatchGetQuotesResponse{}
	mi := &file_investment_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetQuotesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetQuotesResponse) ProtoMessage() {}

func (x *BatchGetQuotesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_investment_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetQuotesResponse.ProtoReflect.Descriptor instead.
func (*BatchGetQuotesResponse) Descriptor() ([]byte, []int) {
	return file_investment_proto_rawDescGZIP(), []int{19}
}

func (x *BatchGetQuotesResponse) GetQuotes() []*MarketQuote {
	if x != nil {
		return x.Quotes
	}
	return nil
}

type SearchSymbolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	MarketType    MarketType             `protobuf:"varint,2,opt,name=market_type,json=marketType,proto3,enum=familyledger.investment.v1.MarketType" json:"market_type,omitempty"` // optional filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchSymbolRequest) Reset() {
	*x = SearchSymbolRequest{}
	mi := &file_investment_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchSymbolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchSymbolRequest) ProtoMessage() {}

func (x *SearchSymbolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_investment_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchSymbolRequest.ProtoReflect.Descriptor instead.
func (*SearchSymbolRequest) Descriptor() ([]byte, []int) {
	return file_investment_proto_rawDescGZIP(), []int{20}
}

func (x *SearchSymbolRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchSymbolRequest) GetMarketType() MarketType {
	if x != nil {
		return x.MarketType
	}
	return MarketType_MARKET_TYPE_UNSPECIFIED
}

type SearchSymbolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbols       []*SymbolInfo          `protobuf:"bytes,1,rep,name=symbols,proto3" json:"symbols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchSymbolResponse) Reset() {
	*x = SearchSymbolResponse{}
	mi := &file_investment_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchSymbolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchSymbolResponse) ProtoMessage() {}

func (x *SearchSymbolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_investment_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchSymbolResponse.ProtoReflect.Descriptor instead.
func (*SearchSymbolResponse) Descriptor() ([]byte, []int) {
	return file_investment_proto_rawDescGZIP(), []int{21}
}

func (x *SearchSymbolResponse) GetSymbols() []*SymbolInfo {
	if x != nil {
		return x.Symbols
	}
	return nil
}

type GetPriceHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	MarketType    MarketType             `protobuf:"varint,2,opt,name=market_type,json=marketType,proto3,enum=familyledger.investment.v1.MarketType" json:"market_type,omitempty"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPriceHistoryRequest) Reset() {
	*x = GetPriceHistoryRequest{}
	mi := &file_investment_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPriceHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPriceHistoryRequest) ProtoMessage() {}

func (x *GetPriceHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_investment_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPriceHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetPriceHistoryRequest) Descriptor() ([]byte, []int) {
	return file_investment_proto_rawDescGZIP(), []int{22}
}

func (x *GetPriceHistoryRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetPriceHistoryRequest) GetMarketType() MarketType {
	if x != nil {
		return x.MarketType
	}
	return MarketType_MARKET_TYPE_UNSPECIFIED
}

func (x *GetPriceHistoryRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *GetPriceHistoryRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

type PriceHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	MarketType    MarketType             `protobuf:"varint,2,opt,name=market_type,json=marketType,proto3,enum=familyledger.investment.v1.MarketType" json:"market_type,omitempty"`
	Points        []*PricePoint          `protobuf:"bytes,3,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceHistoryResponse) Reset() {
	*x = PriceHistoryResponse{}
	mi := &file_investment_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceHistoryResponse) ProtoMessage() {}

func (x *PriceHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_investment_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceHistoryResponse.ProtoReflect.Descriptor instead.
func (*PriceHistoryResponse) Descriptor() ([]byte, []int) {
	return file_investment_proto_rawDescGZIP(), []int{23}
}

func (x *PriceHistoryResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *PriceHistoryResponse) GetMarketType() MarketType {
	if x != nil {
		return x.MarketType
	}
	return MarketType_MARKET_TYPE_UNSPECIFIED
}

func (x *PriceHistoryResponse) GetPoints() []*PricePoint {
	if x != nil {
		return x.Points
	}
	return nil
}

type GetIRRRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvestmentId  string                 `protobuf:"bytes,1,opt,name=investment_id,json=investmentId,proto3" json:"investment_id,omitempty"` // specific investment; empty = portfolio-level
	FamilyId      string                 `protobuf:"bytes,2,opt,name=family_id,json=familyId,proto3" json:"family_id,omitempty"`             // optional: for family portfolio IRR
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIRRRequest) Reset() {
	*x = GetIRRRequest{}
	mi := &file_investment_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIRRRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIRRRequest) ProtoMessage() {}

func (x *GetIRRRequest) ProtoReflect() protoreflect.Message {
	mi := &file_investment_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIRRRequest.ProtoReflect.Descriptor instead.
func (*GetIRRRequest) Descriptor() ([]byte, []int) {
	return file_investment_proto_rawDescGZIP(), []int{24}
}

func (x *GetIRRRequest) GetInvestmentId() string {
	if x != nil {
		return x.InvestmentId
	}
	return ""
}

func (x *GetIRRRequest) GetFamilyId() string {
	if x != nil {
		return x.FamilyId
	}
	return ""
}

type CashFlow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"` // positive = inflow (sell), negative = outflow (buy)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CashFlow) Reset() {
	*x = CashFlow{}
	mi := &file_investment_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CashFlow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CashFlow) ProtoMessage() {}

func (x *CashFlow) ProtoReflect() protoreflect.Message {
	mi := &file_investment_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CashFlow.ProtoReflect.Descriptor instead.
func (*CashFlow) Descriptor() ([]byte, []int) {
	return file_investment_proto_rawDescGZIP(), []int{25}
}

func (x *CashFlow) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *CashFlow) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type IRRResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AnnualizedIrr float64                `protobuf:"fixed64,1,opt,name=annualized_irr,json=annualizedIrr,proto3" json:"annualized_irr,omitempty"`
	CashFlows     []*CashFlow            `protobuf:"bytes,2,rep,name=cash_flows,json=cashFlows,proto3" json:"cash_flows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IRRResponse) Reset() {
	*x = IRRResponse{}
	mi := &file_investment_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IRRResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IRRResponse) ProtoMessage() {}

func (x *IRRResponse) ProtoReflect() protoreflect.Message {
	mi := &file_investment_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IRRResponse.ProtoReflect.Descriptor instead.
func (*IRRResponse) Descriptor() ([]byte, []int) {
	return file_investment_proto_rawDescGZIP(), []int{26}
}

func (x *IRRResponse) GetAnnualizedIrr() float64 {
	if x != nil {
		return x.AnnualizedIrr
	}
	return 0
}

func (x *IRRResponse) GetCashFlows() []*CashFlow {
	if x != nil {
		return x.CashFlows
	}
	return nil
}

var File_investment_proto protoreflect.FileDescriptor

const file_investment_proto_rawDesc = "" +
	"\n" +
	"\x10investment.proto\x12\x1afamilyledger.investment.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xed\x03\n" +
	"\n" +
	"Investment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12G\n" +
	"\vmarket_type\x18\x05 \x01(\x0e2&.familyledger.investment.v1.MarketTypeR\n" +
	"marketType\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\x01R\bquantity\x12\x1d\n" +
	"\n" +
	"cost_basis\x18\a \x01(\x03R\tcostBasis\x12#\n" +
	"\rcurrent_value\x18\b \x01(\x03R\fcurrentValue\x12!\n" +
	"\ftotal_return\x18\t \x01(\x01R\vtotalReturn\x12+\n" +
	"\x11annualized_return\x18\n" +
	" \x01(\x01R\x10annualizedReturn\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1b\n" +
	"\tfamily_id\x18\r \x01(\tR\bfamilyId\"\xae\x02\n" +
	"\x0fInvestmentTrade\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rinvestment_id\x18\x02 \x01(\tR\finvestmentId\x12D\n" +
	"\n" +
	"trade_type\x18\x03 \x01(\x0e2%.familyledger.investment.v1.TradeTypeR\ttradeType\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x01R\bquantity\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x03R\x05price\x12!\n" +
	"\ftotal_amount\x18\x06 \x01(\x03R\vtotalAmount\x12\x10\n" +
	"\x03fee\x18\a \x01(\x03R\x03fee\x129\n" +
	"\n" +
	"trade_date\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\ttradeDate\"\xfa\x02\n" +
	"\vMarketQuote\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12G\n" +
	"\vmarket_type\x18\x03 \x01(\x0e2&.familyledger.investment.v1.MarketTypeR\n" +
	"marketType\x12#\n" +
	"\rcurrent_price\x18\x04 \x01(\x03R\fcurrentPrice\x12\x16\n" +
	"\x06change\x18\x05 \x01(\x03R\x06change\x12%\n" +
	"\x0echange_percent\x18\x06 \x01(\x01R\rchangePercent\x12\x12\n" +
	"\x04open\x18\a \x01(\x03R\x04open\x12\x12\n" +
	"\x04high\x18\b \x01(\x03R\x04high\x12\x10\n" +
	"\x03low\x18\t \x01(\x03R\x03low\x12\x1d\n" +
	"\n" +
	"prev_close\x18\n" +
	" \x01(\x03R\tprevClose\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xdd\x01\n" +
	"\x10PortfolioSummary\x12\x1f\n" +
	"\vtotal_value\x18\x01 \x01(\x03R\n" +
	"totalValue\x12\x1d\n" +
	"\n" +
	"total_cost\x18\x02 \x01(\x03R\ttotalCost\x12!\n" +
	"\ftotal_profit\x18\x03 \x01(\x03R\vtotalProfit\x12!\n" +
	"\ftotal_return\x18\x04 \x01(\x01R\vtotalReturn\x12C\n" +
	"\bholdings\x18\x05 \x03(\v2'.familyledger.investment.v1.HoldingItemR\bholdings\"\xd8\x01\n" +
	"\vHoldingItem\x12#\n" +
	"\rinvestment_id\x18\x01 \x01(\tR\finvestmentId\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x01R\bquantity\x12#\n" +
	"\rcurrent_value\x18\x05 \x01(\x03R\fcurrentValue\x12\x16\n" +
	"\x06weight\x18\x06 \x01(\x01R\x06weight\x12\x1f\n" +
	"\vreturn_rate\x18\a \x01(\x01R\n" +
	"returnRate\"\\\n" +
	"\n" +
	"PricePoint\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x03R\x05price\"\x81\x01\n" +
	"\n" +
	"SymbolInfo\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12G\n" +
	"\vmarket_type\x18\x03 \x01(\x0e2&.familyledger.investment.v1.MarketTypeR\n" +
	"marketType\"\xab\x01\n" +
	"\x17CreateInvestmentRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12G\n" +
	"\vmarket_type\x18\x03 \x01(\x0e2&.familyledger.investment.v1.MarketTypeR\n" +
	"marketType\x12\x1b\n" +
	"\tfamily_id\x18\x04 \x01(\tR\bfamilyId\";\n" +
	"\x14GetInvestmentRequest\x12#\n" +
	"\rinvestment_id\x18\x01 \x01(\tR\finvestmentId\"~\n" +
	"\x16ListInvestmentsRequest\x12G\n" +
	"\vmarket_type\x18\x01 \x01(\x0e2&.familyledger.investment.v1.MarketTypeR\n" +
	"marketType\x12\x1b\n" +
	"\tfamily_id\x18\x02 \x01(\tR\bfamilyId\"c\n" +
	"\x17ListInvestmentsResponse\x12H\n" +
	"\vinvestments\x18\x01 \x03(\v2&.familyledger.investment.v1.InvestmentR\vinvestments\"R\n" +
	"\x17UpdateInvestmentRequest\x12#\n" +
	"\rinvestment_id\x18\x01 \x01(\tR\finvestmentId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\">\n" +
	"\x17DeleteInvestmentRequest\x12#\n" +
	"\rinvestment_id\x18\x01 \x01(\tR\finvestmentId\"\xfe\x01\n" +
	"\x12RecordTradeRequest\x12#\n" +
	"\rinvestment_id\x18\x01 \x01(\tR\finvestmentId\x12D\n" +
	"\n" +
	"trade_type\x18\x02 \x01(\x0e2%.familyledger.investment.v1.TradeTypeR\ttradeType\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x01R\bquantity\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x03R\x05price\x12\x10\n" +
	"\x03fee\x18\x05 \x01(\x03R\x03fee\x129\n" +
	"\n" +
	"trade_date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttradeDate\"8\n" +
	"\x11ListTradesRequest\x12#\n" +
	"\rinvestment_id\x18\x01 \x01(\tR\finvestmentId\"Y\n" +
	"\x12ListTradesResponse\x12C\n" +
	"\x06trades\x18\x01 \x03(\v2+.familyledger.investment.v1.InvestmentTradeR\x06trades\"9\n" +
	"\x1aGetPortfolioSummaryRequest\x12\x1b\n" +
	"\tfamily_id\x18\x01 \x01(\tR\bfamilyId\"r\n" +
	"\x0fGetQuoteRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12G\n" +
	"\vmarket_type\x18\x02 \x01(\x0e2&.familyledger.investment.v1.MarketTypeR\n" +
	"marketType\"`\n" +
	"\x15BatchGetQuotesRequest\x12G\n" +
	"\brequests\x18\x01 \x03(\v2+.familyledger.investment.v1.GetQuoteRequestR\brequests\"Y\n" +
	"\x16BatchGetQuotesResponse\x12?\n" +
	"\x06quotes\x18\x01 \x03(\v2'.familyledger.investment.v1.MarketQuoteR\x06quotes\"t\n" +
	"\x13SearchSymbolRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12G\n" +
	"\vmarket_type\x18\x02 \x01(\x0e2&.familyledger.investment.v1.MarketTypeR\n" +
	"marketType\"X\n" +
	"\x14SearchSymbolResponse\x12@\n" +
	"\asymbols\x18\x01 \x03(\v2&.familyledger.investment.v1.SymbolInfoR\asymbols\"\xeb\x01\n" +
	"\x16GetPriceHistoryRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12G\n" +
	"\vmarket_type\x18\x02 \x01(\x0e2&.familyledger.investment.v1.MarketTypeR\n" +
	"marketType\x129\n" +
	"\n" +
	"start_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\"\xb7\x01\n" +
	"\x14PriceHistoryResponse\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12G\n" +
	"\vmarket_type\x18\x02 \x01(\x0e2&.familyledger.investment.v1.MarketTypeR\n" +
	"marketType\x12>\n" +
	"\x06points\x18\x03 \x03(\v2&.familyledger.investment.v1.PricePointR\x06points\"Q\n" +
	"\rGetIRRRequest\x12#\n" +
	"\rinvestment_id\x18\x01 \x01(\tR\finvestmentId\x12\x1b\n" +
	"\tfamily_id\x18\x02 \x01(\tR\bfamilyId\"R\n" +
	"\bCashFlow\x12.\n" +
	"\x04date\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\"y\n" +
	"\vIRRResponse\x12%\n" +
	"\x0eannualized_irr\x18\x01 \x01(\x01R\rannualizedIrr\x12C\n" +
	"\n" +
	"cash_flows\x18\x02 \x03(\v2$.familyledger.investment.v1.CashFlowR\tcashFlows*\xc4\x01\n" +
	"\n" +
	"MarketType\x12\x1b\n" +
	"\x17MARKET_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13MARKET_TYPE_A_SHARE\x10\x01\x12\x18\n" +
	"\x14MARKET_TYPE_HK_STOCK\x10\x02\x12\x18\n" +
	"\x14MARKET_TYPE_US_STOCK\x10\x03\x12\x16\n" +
	"\x12MARKET_TYPE_CRYPTO\x10\x04\x12\x14\n" +
	"\x10MARKET_TYPE_FUND\x10\x05\x12\x1e\n" +
	"\x1aMARKET_TYPE_PRECIOUS_METAL\x10\x06*P\n" +
	"\tTradeType\x12\x1a\n" +
	"\x16TRADE_TYPE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eTRADE_TYPE_BUY\x10\x01\x12\x13\n" +
	"\x0fTRADE_TYPE_SELL\x10\x022\xfb\a\n" +
	"\x11InvestmentService\x12o\n" +
	"\x10CreateInvestment\x123.familyledger.investment.v1.CreateInvestmentRequest\x1a&.familyledger.investment.v1.Investment\x12i\n" +
	"\rGetInvestment\x120.familyledger.investment.v1.GetInvestmentRequest\x1a&.familyledger.investment.v1.Investment\x12z\n" +
	"\x0fListInvestments\x122.familyledger.investment.v1.ListInvestmentsRequest\x1a3.familyledger.investment.v1.ListInvestmentsResponse\x12o\n" +
	"\x10UpdateInvestment\x123.familyledger.investment.v1.UpdateInvestmentRequest\x1a&.familyledger.investment.v1.Investment\x12_\n" +
	"\x10DeleteInvestment\x123.familyledger.investment.v1.DeleteInvestmentRequest\x1a\x16.google.protobuf.Empty\x12j\n" +
	"\vRecordTrade\x12..familyledger.investment.v1.RecordTradeRequest\x1a+.familyledger.investment.v1.InvestmentTrade\x12k\n" +
	"\n" +
	"ListTrades\x12-.familyledger.investment.v1.ListTradesRequest\x1a..familyledger.investment.v1.ListTradesResponse\x12{\n" +
	"\x13GetPortfolioSummary\x126.familyledger.investment.v1.GetPortfolioSummaryRequest\x1a,.familyledger.investment.v1.PortfolioSummary\x12f\n" +
	"\x10GetInvestmentIRR\x12).familyledger.investment.v1.GetIRRRequest\x1a'.familyledger.investment.v1.IRRResponse2\xda\x03\n" +
	"\x11MarketDataService\x12`\n" +
	"\bGetQuote\x12+.familyledger.investment.v1.GetQuoteRequest\x1a'.familyledger.investment.v1.MarketQuote\x12w\n" +
	"\x0eBatchGetQuotes\x121.familyledger.investment.v1.BatchGetQuotesRequest\x1a2.familyledger.investment.v1.BatchGetQuotesResponse\x12q\n" +
	"\fSearchSymbol\x12/.familyledger.investment.v1.SearchSymbolRequest\x1a0.familyledger.investment.v1.SearchSymbolResponse\x12w\n" +
	"\x0fGetPriceHistory\x122.familyledger.investment.v1.GetPriceHistoryRequest\x1a0.familyledger.investment.v1.PriceHistoryResponseB1Z/github.com/familyledger/server/proto/investmentb\x06proto3"

var (
	file_investment_proto_rawDescOnce sync.Once
	file_investment_proto_rawDescData []byte
)

func file_investment_proto_rawDescGZIP() []byte {
	file_investment_proto_rawDescOnce.Do(func() {
		file_investment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_investment_proto_rawDesc), len(file_investment_proto_rawDesc)))
	})
	return file_investment_proto_rawDescData
}

var file_investment_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_investment_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_investment_proto_goTypes = []any{
	(MarketType)(0),                    // 0: familyledger.investment.v1.MarketType
	(TradeType)(0),                     // 1: familyledger.investment.v1.TradeType
	(*Investment)(nil),                 // 2: familyledger.investment.v1.Investment
	(*InvestmentTrade)(nil),            // 3: familyledger.investment.v1.InvestmentTrade
	(*MarketQuote)(nil),                // 4: familyledger.investment.v1.MarketQuote
	(*PortfolioSummary)(nil),           // 5: familyledger.investment.v1.PortfolioSummary
	(*HoldingItem)(nil),                // 6: familyledger.investment.v1.HoldingItem
	(*PricePoint)(nil),                 // 7: familyledger.investment.v1.PricePoint
	(*SymbolInfo)(nil),                 // 8: familyledger.investment.v1.SymbolInfo
	(*CreateInvestmentRequest)(nil),    // 9: familyledger.investment.v1.CreateInvestmentRequest
	(*GetInvestmentRequest)(nil),       // 10: familyledger.investment.v1.GetInvestmentRequest
	(*ListInvestmentsRequest)(nil),     // 11: familyledger.investment.v1.ListInvestmentsRequest
	(*ListInvestmentsResponse)(nil),    // 12: familyledger.investment.v1.ListInvestmentsResponse
	(*UpdateInvestmentRequest)(nil),    // 13: familyledger.investment.v1.UpdateInvestmentRequest
	(*DeleteInvestmentRequest)(nil),    // 14: familyledger.investment.v1.DeleteInvestmentRequest
	(*RecordTradeRequest)(nil),         // 15: familyledger.investment.v1.RecordTradeRequest
	(*ListTradesRequest)(nil),          // 16: familyledger.investment.v1.ListTradesRequest
	(*ListTradesResponse)(nil),         // 17: familyledger.investment.v1.ListTradesResponse
	(*GetPortfolioSummaryRequest)(nil), // 18: familyledger.investment.v1.GetPortfolioSummaryRequest
	(*GetQuoteRequest)(nil),            // 19: familyledger.investment.v1.GetQuoteRequest
	(*BatchGetQuotesRequest)(nil),      // 20: familyledger.investment.v1.BatchGetQuotesRequest
	(*BatchGetQuotesResponse)(nil),     // 21: familyledger.investment.v1.BatchGetQuotesResponse
	(*SearchSymbolRequest)(nil),        // 22: familyledger.investment.v1.SearchSymbolRequest
	(*SearchSymbolResponse)(nil),       // 23: familyledger.investment.v1.SearchSymbolResponse
	(*GetPriceHistoryRequest)(nil),     // 24: familyledger.investment.v1.GetPriceHistoryRequest
	(*PriceHistoryResponse)(nil),       // 25: familyledger.investment.v1.PriceHistoryResponse
	(*GetIRRRequest)(nil),              // 26: familyledger.investment.v1.GetIRRRequest
	(*CashFlow)(nil),                   // 27: familyledger.investment.v1.CashFlow
	(*IRRResponse)(nil),                // 28: familyledger.investment.v1.IRRResponse
	(*timestamppb.Timestamp)(nil),      // 29: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),              // 30: google.protobuf.Empty
}
var file_investment_proto_depIdxs = []int32{
	0,  // 0: familyledger.investment.v1.Investment.market_type:type_name -> familyledger.investment.v1.MarketType
	29, // 1: familyledger.investment.v1.Investment.created_at:type_name -> google.protobuf.Timestamp
	29, // 2: familyledger.investment.v1.Investment.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 3: familyledger.investment.v1.InvestmentTrade.trade_type:type_name -> familyledger.investment.v1.TradeType
	29, // 4: familyledger.investment.v1.InvestmentTrade.trade_date:type_name -> google.protobuf.Timestamp
	0,  // 5: familyledger.investment.v1.MarketQuote.market_type:type_name -> familyledger.investment.v1.MarketType
	29, // 6: familyledger.investment.v1.MarketQuote.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 7: familyledger.investment.v1.PortfolioSummary.holdings:type_name -> familyledger.investment.v1.HoldingItem
	29, // 8: familyledger.investment.v1.PricePoint.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 9: familyledger.investment.v1.SymbolInfo.market_type:type_name -> familyledger.investment.v1.MarketType
	0,  // 10: familyledger.investment.v1.CreateInvestmentRequest.market_type:type_name -> familyledger.investment.v1.MarketType
	0,  // 11: familyledger.investment.v1.ListInvestmentsRequest.market_type:type_name -> familyledger.investment.v1.MarketType
	2,  // 12: familyledger.investment.v1.ListInvestmentsResponse.investments:type_name -> familyledger.investment.v1.Investment
	1,  // 13: familyledger.investment.v1.RecordTradeRequest.trade_type:type_name -> familyledger.investment.v1.TradeType
	29, // 14: familyledger.investment.v1.RecordTradeRequest.trade_date:type_name -> google.protobuf.Timestamp
	3,  // 15: familyledger.investment.v1.ListTradesResponse.trades:type_name -> familyledger.investment.v1.InvestmentTrade
	0,  // 16: familyledger.investment.v1.GetQuoteRequest.market_type:type_name -> familyledger.investment.v1.MarketType
	19, // 17: familyledger.investment.v1.BatchGetQuotesRequest.requests:type_name -> familyledger.investment.v1.GetQuoteRequest
	4,  // 18: familyledger.investment.v1.BatchGetQuotesResponse.quotes:type_name -> familyledger.investment.v1.MarketQuote
	0,  // 19: familyledger.investment.v1.SearchSymbolRequest.market_type:type_name -> familyledger.investment.v1.MarketType
	8,  // 20: familyledger.investment.v1.SearchSymbolResponse.symbols:type_name -> familyledger.investment.v1.SymbolInfo
	0,  // 21: familyledger.investment.v1.GetPriceHistoryRequest.market_type:type_name -> familyledger.investment.v1.MarketType
	29, // 22: familyledger.investment.v1.GetPriceHistoryRequest.start_date:type_name -> google.protobuf.Timestamp
	29, // 23: familyledger.investment.v1.GetPriceHistoryRequest.end_date:type_name -> google.protobuf.Timestamp
	0,  // 24: familyledger.investment.v1.PriceHistoryResponse.market_type:type_name -> familyledger.investment.v1.MarketType
	7,  // 25: familyledger.investment.v1.PriceHistoryResponse.points:type_name -> familyledger.investment.v1.PricePoint
	29, // 26: familyledger.investment.v1.CashFlow.date:type_name -> google.protobuf.Timestamp
	27, // 27: familyledger.investment.v1.IRRResponse.cash_flows:type_name -> familyledger.investment.v1.CashFlow
	9,  // 28: familyledger.investment.v1.InvestmentService.CreateInvestment:input_type -> familyledger.investment.v1.CreateInvestmentRequest
	10, // 29: familyledger.investment.v1.InvestmentService.GetInvestment:input_type -> familyledger.investment.v1.GetInvestmentRequest
	11, // 30: familyledger.investment.v1.InvestmentService.ListInvestments:input_type -> familyledger.investment.v1.ListInvestmentsRequest
	13, // 31: familyledger.investment.v1.InvestmentService.UpdateInvestment:input_type -> familyledger.investment.v1.UpdateInvestmentRequest
	14, // 32: familyledger.investment.v1.InvestmentService.DeleteInvestment:input_type -> familyledger.investment.v1.DeleteInvestmentRequest
	15, // 33: familyledger.investment.v1.InvestmentService.RecordTrade:input_type -> familyledger.investment.v1.RecordTradeRequest
	16, // 34: familyledger.investment.v1.InvestmentService.ListTrades:input_type -> familyledger.investment.v1.ListTradesRequest
	18, // 35: familyledger.investment.v1.InvestmentService.GetPortfolioSummary:input_type -> familyledger.investment.v1.GetPortfolioSummaryRequest
	26, // 36: familyledger.investment.v1.InvestmentService.GetInvestmentIRR:input_type -> familyledger.investment.v1.GetIRRRequest
	19, // 37: familyledger.investment.v1.MarketDataService.GetQuote:input_type -> familyledger.investment.v1.GetQuoteRequest
	20, // 38: familyledger.investment.v1.MarketDataService.BatchGetQuotes:input_type -> familyledger.investment.v1.BatchGetQuotesRequest
	22, // 39: familyledger.investment.v1.MarketDataService.SearchSymbol:input_type -> familyledger.investment.v1.SearchSymbolRequest
	24, // 40: familyledger.investment.v1.MarketDataService.GetPriceHistory:input_type -> familyledger.investment.v1.GetPriceHistoryRequest
	2,  // 41: familyledger.investment.v1.InvestmentService.CreateInvestment:output_type -> familyledger.investment.v1.Investment
	2,  // 42: familyledger.investment.v1.InvestmentService.GetInvestment:output_type -> familyledger.investment.v1.Investment
	12, // 43: familyledger.investment.v1.InvestmentService.ListInvestments:output_type -> familyledger.investment.v1.ListInvestmentsResponse
	2,  // 44: familyledger.investment.v1.InvestmentService.UpdateInvestment:output_type -> familyledger.investment.v1.Investment
	30, // 45: familyledger.investment.v1.InvestmentService.DeleteInvestment:output_type -> google.protobuf.Empty
	3,  // 46: familyledger.investment.v1.InvestmentService.RecordTrade:output_type -> familyledger.investment.v1.InvestmentTrade
	17, // 47: familyledger.investment.v1.InvestmentService.ListTrades:output_type -> familyledger.investment.v1.ListTradesResponse
	5,  // 48: familyledger.investment.v1.InvestmentService.GetPortfolioSummary:output_type -> familyledger.investment.v1.PortfolioSummary
	28, // 49: familyledger.investment.v1.InvestmentService.GetInvestmentIRR:output_type -> familyledger.investment.v1.IRRResponse
	4,  // 50: familyledger.investment.v1.MarketDataService.GetQuote:output_type -> familyledger.investment.v1.MarketQuote
	21, // 51: familyledger.investment.v1.MarketDataService.BatchGetQuotes:output_type -> familyledger.investment.v1.BatchGetQuotesResponse
	23, // 52: familyledger.investment.v1.MarketDataService.SearchSymbol:output_type -> familyledger.investment.v1.SearchSymbolResponse
	25, // 53: familyledger.investment.v1.MarketDataService.GetPriceHistory:output_type -> familyledger.investment.v1.PriceHistoryResponse
	41, // [41:54] is the sub-list for method output_type
	28, // [28:41] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_investment_proto_init() }
func file_investment_proto_init() {
	if File_investment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_investment_proto_rawDesc), len(file_investment_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_investment_proto_goTypes,
		DependencyIndexes: file_investment_proto_depIdxs,
		EnumInfos:         file_investment_proto_enumTypes,
		MessageInfos:      file_investment_proto_msgTypes,
	}.Build()
	File_investment_proto = out.File
	file_investment_proto_goTypes = nil
	file_investment_proto_depIdxs = nil
}
