// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: import.proto

package importpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ParseCSVRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CsvData       []byte                 `protobuf:"bytes,1,opt,name=csv_data,json=csvData,proto3" json:"csv_data,omitempty"`
	Encoding      string                 `protobuf:"bytes,2,opt,name=encoding,proto3" json:"encoding,omitempty"` // utf8 / gbk
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseCSVRequest) Reset() {
	*x = ParseCSVRequest{}
	mi := &file_import_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseCSVRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseCSVRequest) ProtoMessage() {}

func (x *ParseCSVRequest) ProtoReflect() protoreflect.Message {
	mi := &file_import_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseCSVRequest.ProtoReflect.Descriptor instead.
func (*ParseCSVRequest) Descriptor() ([]byte, []int) {
	return file_import_proto_rawDescGZIP(), []int{0}
}

func (x *ParseCSVRequest) GetCsvData() []byte {
	if x != nil {
		return x.CsvData
	}
	return nil
}

func (x *ParseCSVRequest) GetEncoding() string {
	if x != nil {
		return x.Encoding
	}
	return ""
}

type ParseCSVResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Headers       []string               `protobuf:"bytes,1,rep,name=headers,proto3" json:"headers,omitempty"`
	PreviewRows   []*CSVRow              `protobuf:"bytes,2,rep,name=preview_rows,json=previewRows,proto3" json:"preview_rows,omitempty"` // 前 10 行预览
	TotalRows     int32                  `protobuf:"varint,3,opt,name=total_rows,json=totalRows,proto3" json:"total_rows,omitempty"`
	SessionId     string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // 临时存储 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseCSVResponse) Reset() {
	*x = ParseCSVResponse{}
	mi := &file_import_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseCSVResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseCSVResponse) ProtoMessage() {}

func (x *ParseCSVResponse) ProtoReflect() protoreflect.Message {
	mi := &file_import_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseCSVResponse.ProtoReflect.Descriptor instead.
func (*ParseCSVResponse) Descriptor() ([]byte, []int) {
	return file_import_proto_rawDescGZIP(), []int{1}
}

func (x *ParseCSVResponse) GetHeaders() []string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ParseCSVResponse) GetPreviewRows() []*CSVRow {
	if x != nil {
		return x.PreviewRows
	}
	return nil
}

func (x *ParseCSVResponse) GetTotalRows() int32 {
	if x != nil {
		return x.TotalRows
	}
	return 0
}

func (x *ParseCSVResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type CSVRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CSVRow) Reset() {
	*x = CSVRow{}
	mi := &file_import_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CSVRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSVRow) ProtoMessage() {}

func (x *CSVRow) ProtoReflect() protoreflect.Message {
	mi := &file_import_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSVRow.ProtoReflect.Descriptor instead.
func (*CSVRow) Descriptor() ([]byte, []int) {
	return file_import_proto_rawDescGZIP(), []int{2}
}

func (x *CSVRow) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type FieldMapping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CsvColumn     string                 `protobuf:"bytes,1,opt,name=csv_column,json=csvColumn,proto3" json:"csv_column,omitempty"`
	TargetField   string                 `protobuf:"bytes,2,opt,name=target_field,json=targetField,proto3" json:"target_field,omitempty"` // date, amount, type, category, note, account
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldMapping) Reset() {
	*x = FieldMapping{}
	mi := &file_import_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldMapping) ProtoMessage() {}

func (x *FieldMapping) ProtoReflect() protoreflect.Message {
	mi := &file_import_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldMapping.ProtoReflect.Descriptor instead.
func (*FieldMapping) Descriptor() ([]byte, []int) {
	return file_import_proto_rawDescGZIP(), []int{3}
}

func (x *FieldMapping) GetCsvColumn() string {
	if x != nil {
		return x.CsvColumn
	}
	return ""
}

func (x *FieldMapping) GetTargetField() string {
	if x != nil {
		return x.TargetField
	}
	return ""
}

type ConfirmImportRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SessionId        string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Mappings         []*FieldMapping        `protobuf:"bytes,2,rep,name=mappings,proto3" json:"mappings,omitempty"`
	DefaultAccountId string                 `protobuf:"bytes,3,opt,name=default_account_id,json=defaultAccountId,proto3" json:"default_account_id,omitempty"`
	UserId           string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ConfirmImportRequest) Reset() {
	*x = ConfirmImportRequest{}
	mi := &file_import_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmImportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmImportRequest) ProtoMessage() {}

func (x *ConfirmImportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_import_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmImportRequest.ProtoReflect.Descriptor instead.
func (*ConfirmImportRequest) Descriptor() ([]byte, []int) {
	return file_import_proto_rawDescGZIP(), []int{4}
}

func (x *ConfirmImportRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ConfirmImportRequest) GetMappings() []*FieldMapping {
	if x != nil {
		return x.Mappings
	}
	return nil
}

func (x *ConfirmImportRequest) GetDefaultAccountId() string {
	if x != nil {
		return x.DefaultAccountId
	}
	return ""
}

func (x *ConfirmImportRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ConfirmImportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImportedCount int32                  `protobuf:"varint,1,opt,name=imported_count,json=importedCount,proto3" json:"imported_count,omitempty"`
	SkippedCount  int32                  `protobuf:"varint,2,opt,name=skipped_count,json=skippedCount,proto3" json:"skipped_count,omitempty"`
	Errors        []string               `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmImportResponse) Reset() {
	*x = ConfirmImportResponse{}
	mi := &file_import_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmImportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmImportResponse) ProtoMessage() {}

func (x *ConfirmImportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_import_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmImportResponse.ProtoReflect.Descriptor instead.
func (*ConfirmImportResponse) Descriptor() ([]byte, []int) {
	return file_import_proto_rawDescGZIP(), []int{5}
}

func (x *ConfirmImportResponse) GetImportedCount() int32 {
	if x != nil {
		return x.ImportedCount
	}
	return 0
}

func (x *ConfirmImportResponse) GetSkippedCount() int32 {
	if x != nil {
		return x.SkippedCount
	}
	return 0
}

func (x *ConfirmImportResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

var File_import_proto protoreflect.FileDescriptor

const file_import_proto_rawDesc = "" +
	"\n" +
	"\fimport.proto\x12\x16familyledger.import.v1\"H\n" +
	"\x0fParseCSVRequest\x12\x19\n" +
	"\bcsv_data\x18\x01 \x01(\fR\acsvData\x12\x1a\n" +
	"\bencoding\x18\x02 \x01(\tR\bencoding\"\xad\x01\n" +
	"\x10ParseCSVResponse\x12\x18\n" +
	"\aheaders\x18\x01 \x03(\tR\aheaders\x12A\n" +
	"\fpreview_rows\x18\x02 \x03(\v2\x1e.familyledger.import.v1.CSVRowR\vpreviewRows\x12\x1d\n" +
	"\n" +
	"total_rows\x18\x03 \x01(\x05R\ttotalRows\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\" \n" +
	"\x06CSVRow\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"P\n" +
	"\fFieldMapping\x12\x1d\n" +
	"\n" +
	"csv_column\x18\x01 \x01(\tR\tcsvColumn\x12!\n" +
	"\ftarget_field\x18\x02 \x01(\tR\vtargetField\"\xbe\x01\n" +
	"\x14ConfirmImportRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12@\n" +
	"\bmappings\x18\x02 \x03(\v2$.familyledger.import.v1.FieldMappingR\bmappings\x12,\n" +
	"\x12default_account_id\x18\x03 \x01(\tR\x10defaultAccountId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\"{\n" +
	"\x15ConfirmImportResponse\x12%\n" +
	"\x0eimported_count\x18\x01 \x01(\x05R\rimportedCount\x12#\n" +
	"\rskipped_count\x18\x02 \x01(\x05R\fskippedCount\x12\x16\n" +
	"\x06errors\x18\x03 \x03(\tR\x06errors2\xdc\x01\n" +
	"\rImportService\x12]\n" +
	"\bParseCSV\x12'.familyledger.import.v1.ParseCSVRequest\x1a(.familyledger.import.v1.ParseCSVResponse\x12l\n" +
	"\rConfirmImport\x12,.familyledger.import.v1.ConfirmImportRequest\x1a-.familyledger.import.v1.ConfirmImportResponseB/Z-github.com/familyledger/server/proto/importpbb\x06proto3"

var (
	file_import_proto_rawDescOnce sync.Once
	file_import_proto_rawDescData []byte
)

func file_import_proto_rawDescGZIP() []byte {
	file_import_proto_rawDescOnce.Do(func() {
		file_import_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_import_proto_rawDesc), len(file_import_proto_rawDesc)))
	})
	return file_import_proto_rawDescData
}

var file_import_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_import_proto_goTypes = []any{
	(*ParseCSVRequest)(nil),       // 0: familyledger.import.v1.ParseCSVRequest
	(*ParseCSVResponse)(nil),      // 1: familyledger.import.v1.ParseCSVResponse
	(*CSVRow)(nil),                // 2: familyledger.import.v1.CSVRow
	(*FieldMapping)(nil),          // 3: familyledger.import.v1.FieldMapping
	(*ConfirmImportRequest)(nil),  // 4: familyledger.import.v1.ConfirmImportRequest
	(*ConfirmImportResponse)(nil), // 5: familyledger.import.v1.ConfirmImportResponse
}
var file_import_proto_depIdxs = []int32{
	2, // 0: familyledger.import.v1.ParseCSVResponse.preview_rows:type_name -> familyledger.import.v1.CSVRow
	3, // 1: familyledger.import.v1.ConfirmImportRequest.mappings:type_name -> familyledger.import.v1.FieldMapping
	0, // 2: familyledger.import.v1.ImportService.ParseCSV:input_type -> familyledger.import.v1.ParseCSVRequest
	4, // 3: familyledger.import.v1.ImportService.ConfirmImport:input_type -> familyledger.import.v1.ConfirmImportRequest
	1, // 4: familyledger.import.v1.ImportService.ParseCSV:output_type -> familyledger.import.v1.ParseCSVResponse
	5, // 5: familyledger.import.v1.ImportService.ConfirmImport:output_type -> familyledger.import.v1.ConfirmImportResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_import_proto_init() }
func file_import_proto_init() {
	if File_import_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_import_proto_rawDesc), len(file_import_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_import_proto_goTypes,
		DependencyIndexes: file_import_proto_depIdxs,
		MessageInfos:      file_import_proto_msgTypes,
	}.Build()
	File_import_proto = out.File
	file_import_proto_goTypes = nil
	file_import_proto_depIdxs = nil
}
