// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: import.proto

package importpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ImportService_ParseCSV_FullMethodName      = "/familyledger.import.v1.ImportService/ParseCSV"
	ImportService_ConfirmImport_FullMethodName = "/familyledger.import.v1.ImportService/ConfirmImport"
)

// ImportServiceClient is the client API for ImportService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ImportServiceClient interface {
	ParseCSV(ctx context.Context, in *ParseCSVRequest, opts ...grpc.CallOption) (*ParseCSVResponse, error)
	ConfirmImport(ctx context.Context, in *ConfirmImportRequest, opts ...grpc.CallOption) (*ConfirmImportResponse, error)
}

type importServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewImportServiceClient(cc grpc.ClientConnInterface) ImportServiceClient {
	return &importServiceClient{cc}
}

func (c *importServiceClient) ParseCSV(ctx context.Context, in *ParseCSVRequest, opts ...grpc.CallOption) (*ParseCSVResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParseCSVResponse)
	err := c.cc.Invoke(ctx, ImportService_ParseCSV_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *importServiceClient) ConfirmImport(ctx context.Context, in *ConfirmImportRequest, opts ...grpc.CallOption) (*ConfirmImportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmImportResponse)
	err := c.cc.Invoke(ctx, ImportService_ConfirmImport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImportServiceServer is the server API for ImportService service.
// All implementations must embed UnimplementedImportServiceServer
// for forward compatibility.
type ImportServiceServer interface {
	ParseCSV(context.Context, *ParseCSVRequest) (*ParseCSVResponse, error)
	ConfirmImport(context.Context, *ConfirmImportRequest) (*ConfirmImportResponse, error)
	mustEmbedUnimplementedImportServiceServer()
}

// UnimplementedImportServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedImportServiceServer struct{}

func (UnimplementedImportServiceServer) ParseCSV(context.Context, *ParseCSVRequest) (*ParseCSVResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ParseCSV not implemented")
}
func (UnimplementedImportServiceServer) ConfirmImport(context.Context, *ConfirmImportRequest) (*ConfirmImportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmImport not implemented")
}
func (UnimplementedImportServiceServer) mustEmbedUnimplementedImportServiceServer() {}
func (UnimplementedImportServiceServer) testEmbeddedByValue()                       {}

// UnsafeImportServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImportServiceServer will
// result in compilation errors.
type UnsafeImportServiceServer interface {
	mustEmbedUnimplementedImportServiceServer()
}

func RegisterImportServiceServer(s grpc.ServiceRegistrar, srv ImportServiceServer) {
	// If the following call panics, it indicates UnimplementedImportServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ImportService_ServiceDesc, srv)
}

func _ImportService_ParseCSV_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseCSVRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImportServiceServer).ParseCSV(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImportService_ParseCSV_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImportServiceServer).ParseCSV(ctx, req.(*ParseCSVRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImportService_ConfirmImport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmImportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImportServiceServer).ConfirmImport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImportService_ConfirmImport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImportServiceServer).ConfirmImport(ctx, req.(*ConfirmImportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ImportService_ServiceDesc is the grpc.ServiceDesc for ImportService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ImportService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "familyledger.import.v1.ImportService",
	HandlerType: (*ImportServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ParseCSV",
			Handler:    _ImportService_ParseCSV_Handler,
		},
		{
			MethodName: "ConfirmImport",
			Handler:    _ImportService_ConfirmImport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "import.proto",
}
