// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: sync.proto

package sync

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OperationType int32

const (
	OperationType_OPERATION_TYPE_UNSPECIFIED OperationType = 0
	OperationType_OPERATION_TYPE_CREATE      OperationType = 1
	OperationType_OPERATION_TYPE_UPDATE      OperationType = 2
	OperationType_OPERATION_TYPE_DELETE      OperationType = 3
)

// Enum value maps for OperationType.
var (
	OperationType_name = map[int32]string{
		0: "OPERATION_TYPE_UNSPECIFIED",
		1: "OPERATION_TYPE_CREATE",
		2: "OPERATION_TYPE_UPDATE",
		3: "OPERATION_TYPE_DELETE",
	}
	OperationType_value = map[string]int32{
		"OPERATION_TYPE_UNSPECIFIED": 0,
		"OPERATION_TYPE_CREATE":      1,
		"OPERATION_TYPE_UPDATE":      2,
		"OPERATION_TYPE_DELETE":      3,
	}
)

func (x OperationType) Enum() *OperationType {
	p := new(OperationType)
	*p = x
	return p
}

func (x OperationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationType) Descriptor() protoreflect.EnumDescriptor {
	return file_sync_proto_enumTypes[0].Descriptor()
}

func (OperationType) Type() protoreflect.EnumType {
	return &file_sync_proto_enumTypes[0]
}

func (x OperationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationType.Descriptor instead.
func (OperationType) EnumDescriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{0}
}

type SyncOperation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EntityType    string                 `protobuf:"bytes,2,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"` // "transaction", "account", "category"
	EntityId      string                 `protobuf:"bytes,3,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	OpType        OperationType          `protobuf:"varint,4,opt,name=op_type,json=opType,proto3,enum=familyledger.sync.v1.OperationType" json:"op_type,omitempty"`
	Payload       string                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"` // JSON payload
	ClientId      string                 `protobuf:"bytes,6,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncOperation) Reset() {
	*x = SyncOperation{}
	mi := &file_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncOperation) ProtoMessage() {}

func (x *SyncOperation) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncOperation.ProtoReflect.Descriptor instead.
func (*SyncOperation) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{0}
}

func (x *SyncOperation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SyncOperation) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *SyncOperation) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *SyncOperation) GetOpType() OperationType {
	if x != nil {
		return x.OpType
	}
	return OperationType_OPERATION_TYPE_UNSPECIFIED
}

func (x *SyncOperation) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *SyncOperation) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *SyncOperation) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type PushOperationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operations    []*SyncOperation       `protobuf:"bytes,1,rep,name=operations,proto3" json:"operations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushOperationsRequest) Reset() {
	*x = PushOperationsRequest{}
	mi := &file_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushOperationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushOperationsRequest) ProtoMessage() {}

func (x *PushOperationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushOperationsRequest.ProtoReflect.Descriptor instead.
func (*PushOperationsRequest) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{1}
}

func (x *PushOperationsRequest) GetOperations() []*SyncOperation {
	if x != nil {
		return x.Operations
	}
	return nil
}

type PushOperationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AcceptedCount int32                  `protobuf:"varint,1,opt,name=accepted_count,json=acceptedCount,proto3" json:"accepted_count,omitempty"`
	FailedIds     []string               `protobuf:"bytes,2,rep,name=failed_ids,json=failedIds,proto3" json:"failed_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushOperationsResponse) Reset() {
	*x = PushOperationsResponse{}
	mi := &file_sync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushOperationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushOperationsResponse) ProtoMessage() {}

func (x *PushOperationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushOperationsResponse.ProtoReflect.Descriptor instead.
func (*PushOperationsResponse) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{2}
}

func (x *PushOperationsResponse) GetAcceptedCount() int32 {
	if x != nil {
		return x.AcceptedCount
	}
	return 0
}

func (x *PushOperationsResponse) GetFailedIds() []string {
	if x != nil {
		return x.FailedIds
	}
	return nil
}

type PullChangesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Since         *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=since,proto3" json:"since,omitempty"` // 上次同步时间
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	FamilyId      string                 `protobuf:"bytes,3,opt,name=family_id,json=familyId,proto3" json:"family_id,omitempty"` // 可选：传入则拉取家庭模式下所有成员的操作
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullChangesRequest) Reset() {
	*x = PullChangesRequest{}
	mi := &file_sync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullChangesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullChangesRequest) ProtoMessage() {}

func (x *PullChangesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullChangesRequest.ProtoReflect.Descriptor instead.
func (*PullChangesRequest) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{3}
}

func (x *PullChangesRequest) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

func (x *PullChangesRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *PullChangesRequest) GetFamilyId() string {
	if x != nil {
		return x.FamilyId
	}
	return ""
}

type PullChangesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operations    []*SyncOperation       `protobuf:"bytes,1,rep,name=operations,proto3" json:"operations,omitempty"`
	ServerTime    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullChangesResponse) Reset() {
	*x = PullChangesResponse{}
	mi := &file_sync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullChangesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullChangesResponse) ProtoMessage() {}

func (x *PullChangesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullChangesResponse.ProtoReflect.Descriptor instead.
func (*PullChangesResponse) Descriptor() ([]byte, []int) {
	return file_sync_proto_rawDescGZIP(), []int{4}
}

func (x *PullChangesResponse) GetOperations() []*SyncOperation {
	if x != nil {
		return x.Operations
	}
	return nil
}

func (x *PullChangesResponse) GetServerTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ServerTime
	}
	return nil
}

var File_sync_proto protoreflect.FileDescriptor

const file_sync_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"sync.proto\x12\x14familyledger.sync.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8c\x02\n" +
	"\rSyncOperation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\ventity_type\x18\x02 \x01(\tR\n" +
	"entityType\x12\x1b\n" +
	"\tentity_id\x18\x03 \x01(\tR\bentityId\x12<\n" +
	"\aop_type\x18\x04 \x01(\x0e2#.familyledger.sync.v1.OperationTypeR\x06opType\x12\x18\n" +
	"\apayload\x18\x05 \x01(\tR\apayload\x12\x1b\n" +
	"\tclient_id\x18\x06 \x01(\tR\bclientId\x128\n" +
	"\ttimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\\\n" +
	"\x15PushOperationsRequest\x12C\n" +
	"\n" +
	"operations\x18\x01 \x03(\v2#.familyledger.sync.v1.SyncOperationR\n" +
	"operations\"^\n" +
	"\x16PushOperationsResponse\x12%\n" +
	"\x0eaccepted_count\x18\x01 \x01(\x05R\racceptedCount\x12\x1d\n" +
	"\n" +
	"failed_ids\x18\x02 \x03(\tR\tfailedIds\"\x80\x01\n" +
	"\x12PullChangesRequest\x120\n" +
	"\x05since\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x05since\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12\x1b\n" +
	"\tfamily_id\x18\x03 \x01(\tR\bfamilyId\"\x97\x01\n" +
	"\x13PullChangesResponse\x12C\n" +
	"\n" +
	"operations\x18\x01 \x03(\v2#.familyledger.sync.v1.SyncOperationR\n" +
	"operations\x12;\n" +
	"\vserver_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"serverTime*\x80\x01\n" +
	"\rOperationType\x12\x1e\n" +
	"\x1aOPERATION_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15OPERATION_TYPE_CREATE\x10\x01\x12\x19\n" +
	"\x15OPERATION_TYPE_UPDATE\x10\x02\x12\x19\n" +
	"\x15OPERATION_TYPE_DELETE\x10\x032\xde\x01\n" +
	"\vSyncService\x12k\n" +
	"\x0ePushOperations\x12+.familyledger.sync.v1.PushOperationsRequest\x1a,.familyledger.sync.v1.PushOperationsResponse\x12b\n" +
	"\vPullChanges\x12(.familyledger.sync.v1.PullChangesRequest\x1a).familyledger.sync.v1.PullChangesResponseB+Z)github.com/familyledger/server/proto/syncb\x06proto3"

var (
	file_sync_proto_rawDescOnce sync.Once
	file_sync_proto_rawDescData []byte
)

func file_sync_proto_rawDescGZIP() []byte {
	file_sync_proto_rawDescOnce.Do(func() {
		file_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sync_proto_rawDesc), len(file_sync_proto_rawDesc)))
	})
	return file_sync_proto_rawDescData
}

var file_sync_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_sync_proto_goTypes = []any{
	(OperationType)(0),             // 0: familyledger.sync.v1.OperationType
	(*SyncOperation)(nil),          // 1: familyledger.sync.v1.SyncOperation
	(*PushOperationsRequest)(nil),  // 2: familyledger.sync.v1.PushOperationsRequest
	(*PushOperationsResponse)(nil), // 3: familyledger.sync.v1.PushOperationsResponse
	(*PullChangesRequest)(nil),     // 4: familyledger.sync.v1.PullChangesRequest
	(*PullChangesResponse)(nil),    // 5: familyledger.sync.v1.PullChangesResponse
	(*timestamppb.Timestamp)(nil),  // 6: google.protobuf.Timestamp
}
var file_sync_proto_depIdxs = []int32{
	0, // 0: familyledger.sync.v1.SyncOperation.op_type:type_name -> familyledger.sync.v1.OperationType
	6, // 1: familyledger.sync.v1.SyncOperation.timestamp:type_name -> google.protobuf.Timestamp
	1, // 2: familyledger.sync.v1.PushOperationsRequest.operations:type_name -> familyledger.sync.v1.SyncOperation
	6, // 3: familyledger.sync.v1.PullChangesRequest.since:type_name -> google.protobuf.Timestamp
	1, // 4: familyledger.sync.v1.PullChangesResponse.operations:type_name -> familyledger.sync.v1.SyncOperation
	6, // 5: familyledger.sync.v1.PullChangesResponse.server_time:type_name -> google.protobuf.Timestamp
	2, // 6: familyledger.sync.v1.SyncService.PushOperations:input_type -> familyledger.sync.v1.PushOperationsRequest
	4, // 7: familyledger.sync.v1.SyncService.PullChanges:input_type -> familyledger.sync.v1.PullChangesRequest
	3, // 8: familyledger.sync.v1.SyncService.PushOperations:output_type -> familyledger.sync.v1.PushOperationsResponse
	5, // 9: familyledger.sync.v1.SyncService.PullChanges:output_type -> familyledger.sync.v1.PullChangesResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_sync_proto_init() }
func file_sync_proto_init() {
	if File_sync_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sync_proto_rawDesc), len(file_sync_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sync_proto_goTypes,
		DependencyIndexes: file_sync_proto_depIdxs,
		EnumInfos:         file_sync_proto_enumTypes,
		MessageInfos:      file_sync_proto_msgTypes,
	}.Build()
	File_sync_proto = out.File
	file_sync_proto_goTypes = nil
	file_sync_proto_depIdxs = nil
}
