// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: dashboard.proto

package dashboard

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetNetWorthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FamilyId      string                 `protobuf:"bytes,1,opt,name=family_id,json=familyId,proto3" json:"family_id,omitempty"` // 可选，空=个人
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNetWorthRequest) Reset() {
	*x = GetNetWorthRequest{}
	mi := &file_dashboard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNetWorthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNetWorthRequest) ProtoMessage() {}

func (x *GetNetWorthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNetWorthRequest.ProtoReflect.Descriptor instead.
func (*GetNetWorthRequest) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{0}
}

func (x *GetNetWorthRequest) GetFamilyId() string {
	if x != nil {
		return x.FamilyId
	}
	return ""
}

type NetWorth struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Total               int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`                                                            // 净资产总额（分）
	CashAndBank         int64                  `protobuf:"varint,2,opt,name=cash_and_bank,json=cashAndBank,proto3" json:"cash_and_bank,omitempty"`                           // 现金+银行账户
	InvestmentValue     int64                  `protobuf:"varint,3,opt,name=investment_value,json=investmentValue,proto3" json:"investment_value,omitempty"`                 // 投资市值
	FixedAssetValue     int64                  `protobuf:"varint,4,opt,name=fixed_asset_value,json=fixedAssetValue,proto3" json:"fixed_asset_value,omitempty"`               // 固定资产净值
	LoanBalance         int64                  `protobuf:"varint,5,opt,name=loan_balance,json=loanBalance,proto3" json:"loan_balance,omitempty"`                             // 贷款余额（负数）
	ChangeFromLastMonth int64                  `protobuf:"varint,6,opt,name=change_from_last_month,json=changeFromLastMonth,proto3" json:"change_from_last_month,omitempty"` // 较上月变化
	ChangePercent       float64                `protobuf:"fixed64,7,opt,name=change_percent,json=changePercent,proto3" json:"change_percent,omitempty"`                      // 变化百分比
	Composition         []*AssetComposition    `protobuf:"bytes,8,rep,name=composition,proto3" json:"composition,omitempty"`                                                 // 资产构成
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *NetWorth) Reset() {
	*x = NetWorth{}
	mi := &file_dashboard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetWorth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetWorth) ProtoMessage() {}

func (x *NetWorth) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetWorth.ProtoReflect.Descriptor instead.
func (*NetWorth) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{1}
}

func (x *NetWorth) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *NetWorth) GetCashAndBank() int64 {
	if x != nil {
		return x.CashAndBank
	}
	return 0
}

func (x *NetWorth) GetInvestmentValue() int64 {
	if x != nil {
		return x.InvestmentValue
	}
	return 0
}

func (x *NetWorth) GetFixedAssetValue() int64 {
	if x != nil {
		return x.FixedAssetValue
	}
	return 0
}

func (x *NetWorth) GetLoanBalance() int64 {
	if x != nil {
		return x.LoanBalance
	}
	return 0
}

func (x *NetWorth) GetChangeFromLastMonth() int64 {
	if x != nil {
		return x.ChangeFromLastMonth
	}
	return 0
}

func (x *NetWorth) GetChangePercent() float64 {
	if x != nil {
		return x.ChangePercent
	}
	return 0
}

func (x *NetWorth) GetComposition() []*AssetComposition {
	if x != nil {
		return x.Composition
	}
	return nil
}

type AssetComposition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"` // cash, investment, fixed_asset, loan
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`       // 显示名称
	Value         int64                  `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	Weight        float64                `protobuf:"fixed64,4,opt,name=weight,proto3" json:"weight,omitempty"` // 占比 0-1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetComposition) Reset() {
	*x = AssetComposition{}
	mi := &file_dashboard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetComposition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetComposition) ProtoMessage() {}

func (x *AssetComposition) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetComposition.ProtoReflect.Descriptor instead.
func (*AssetComposition) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{2}
}

func (x *AssetComposition) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *AssetComposition) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *AssetComposition) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *AssetComposition) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type TrendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FamilyId      string                 `protobuf:"bytes,2,opt,name=family_id,json=familyId,proto3" json:"family_id,omitempty"`
	Period        string                 `protobuf:"bytes,3,opt,name=period,proto3" json:"period,omitempty"` // monthly / yearly
	Count         int32                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`  // 最近几个月/年
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrendRequest) Reset() {
	*x = TrendRequest{}
	mi := &file_dashboard_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrendRequest) ProtoMessage() {}

func (x *TrendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrendRequest.ProtoReflect.Descriptor instead.
func (*TrendRequest) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{3}
}

func (x *TrendRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TrendRequest) GetFamilyId() string {
	if x != nil {
		return x.FamilyId
	}
	return ""
}

func (x *TrendRequest) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *TrendRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type TrendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*TrendPoint          `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrendResponse) Reset() {
	*x = TrendResponse{}
	mi := &file_dashboard_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrendResponse) ProtoMessage() {}

func (x *TrendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrendResponse.ProtoReflect.Descriptor instead.
func (*TrendResponse) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{4}
}

func (x *TrendResponse) GetPoints() []*TrendPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

type TrendPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"` // "2026-01" / "2026"
	Income        int64                  `protobuf:"varint,2,opt,name=income,proto3" json:"income,omitempty"`
	Expense       int64                  `protobuf:"varint,3,opt,name=expense,proto3" json:"expense,omitempty"`
	Net           int64                  `protobuf:"varint,4,opt,name=net,proto3" json:"net,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrendPoint) Reset() {
	*x = TrendPoint{}
	mi := &file_dashboard_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrendPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrendPoint) ProtoMessage() {}

func (x *TrendPoint) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrendPoint.ProtoReflect.Descriptor instead.
func (*TrendPoint) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{5}
}

func (x *TrendPoint) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *TrendPoint) GetIncome() int64 {
	if x != nil {
		return x.Income
	}
	return 0
}

func (x *TrendPoint) GetExpense() int64 {
	if x != nil {
		return x.Expense
	}
	return 0
}

func (x *TrendPoint) GetNet() int64 {
	if x != nil {
		return x.Net
	}
	return 0
}

type CategoryBreakdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FamilyId      string                 `protobuf:"bytes,2,opt,name=family_id,json=familyId,proto3" json:"family_id,omitempty"`
	Year          int32                  `protobuf:"varint,3,opt,name=year,proto3" json:"year,omitempty"`
	Month         int32                  `protobuf:"varint,4,opt,name=month,proto3" json:"month,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"` // expense / income
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryBreakdownRequest) Reset() {
	*x = CategoryBreakdownRequest{}
	mi := &file_dashboard_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryBreakdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryBreakdownRequest) ProtoMessage() {}

func (x *CategoryBreakdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryBreakdownRequest.ProtoReflect.Descriptor instead.
func (*CategoryBreakdownRequest) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{6}
}

func (x *CategoryBreakdownRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CategoryBreakdownRequest) GetFamilyId() string {
	if x != nil {
		return x.FamilyId
	}
	return ""
}

func (x *CategoryBreakdownRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *CategoryBreakdownRequest) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *CategoryBreakdownRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type CategoryBreakdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Items         []*CategoryItem        `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryBreakdownResponse) Reset() {
	*x = CategoryBreakdownResponse{}
	mi := &file_dashboard_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryBreakdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryBreakdownResponse) ProtoMessage() {}

func (x *CategoryBreakdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryBreakdownResponse.ProtoReflect.Descriptor instead.
func (*CategoryBreakdownResponse) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{7}
}

func (x *CategoryBreakdownResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *CategoryBreakdownResponse) GetItems() []*CategoryItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type CategoryItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    string                 `protobuf:"bytes,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	CategoryName  string                 `protobuf:"bytes,2,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	Icon          string                 `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	Amount        int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Weight        float64                `protobuf:"fixed64,5,opt,name=weight,proto3" json:"weight,omitempty"`
	Children      []*CategoryItem        `protobuf:"bytes,6,rep,name=children,proto3" json:"children,omitempty"`              // subcategory breakdown
	IconKey       string                 `protobuf:"bytes,7,opt,name=icon_key,json=iconKey,proto3" json:"icon_key,omitempty"` // material icon key (e.g. "food_breakfast")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryItem) Reset() {
	*x = CategoryItem{}
	mi := &file_dashboard_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryItem) ProtoMessage() {}

func (x *CategoryItem) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryItem.ProtoReflect.Descriptor instead.
func (*CategoryItem) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{8}
}

func (x *CategoryItem) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *CategoryItem) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *CategoryItem) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *CategoryItem) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CategoryItem) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *CategoryItem) GetChildren() []*CategoryItem {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *CategoryItem) GetIconKey() string {
	if x != nil {
		return x.IconKey
	}
	return ""
}

type BudgetSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FamilyId      string                 `protobuf:"bytes,1,opt,name=family_id,json=familyId,proto3" json:"family_id,omitempty"`
	Year          int32                  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	Month         int32                  `protobuf:"varint,3,opt,name=month,proto3" json:"month,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BudgetSummaryRequest) Reset() {
	*x = BudgetSummaryRequest{}
	mi := &file_dashboard_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BudgetSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BudgetSummaryRequest) ProtoMessage() {}

func (x *BudgetSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BudgetSummaryRequest.ProtoReflect.Descriptor instead.
func (*BudgetSummaryRequest) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{9}
}

func (x *BudgetSummaryRequest) GetFamilyId() string {
	if x != nil {
		return x.FamilyId
	}
	return ""
}

func (x *BudgetSummaryRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *BudgetSummaryRequest) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

type BudgetSummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalBudget   int64                  `protobuf:"varint,1,opt,name=total_budget,json=totalBudget,proto3" json:"total_budget,omitempty"`
	TotalSpent    int64                  `protobuf:"varint,2,opt,name=total_spent,json=totalSpent,proto3" json:"total_spent,omitempty"`
	ExecutionRate float64                `protobuf:"fixed64,3,opt,name=execution_rate,json=executionRate,proto3" json:"execution_rate,omitempty"`
	Categories    []*CategoryBudgetItem  `protobuf:"bytes,4,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BudgetSummaryResponse) Reset() {
	*x = BudgetSummaryResponse{}
	mi := &file_dashboard_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BudgetSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BudgetSummaryResponse) ProtoMessage() {}

func (x *BudgetSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BudgetSummaryResponse.ProtoReflect.Descriptor instead.
func (*BudgetSummaryResponse) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{10}
}

func (x *BudgetSummaryResponse) GetTotalBudget() int64 {
	if x != nil {
		return x.TotalBudget
	}
	return 0
}

func (x *BudgetSummaryResponse) GetTotalSpent() int64 {
	if x != nil {
		return x.TotalSpent
	}
	return 0
}

func (x *BudgetSummaryResponse) GetExecutionRate() float64 {
	if x != nil {
		return x.ExecutionRate
	}
	return 0
}

func (x *BudgetSummaryResponse) GetCategories() []*CategoryBudgetItem {
	if x != nil {
		return x.Categories
	}
	return nil
}

type CategoryBudgetItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    string                 `protobuf:"bytes,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	CategoryName  string                 `protobuf:"bytes,2,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	BudgetAmount  int64                  `protobuf:"varint,3,opt,name=budget_amount,json=budgetAmount,proto3" json:"budget_amount,omitempty"`
	SpentAmount   int64                  `protobuf:"varint,4,opt,name=spent_amount,json=spentAmount,proto3" json:"spent_amount,omitempty"`
	ExecutionRate float64                `protobuf:"fixed64,5,opt,name=execution_rate,json=executionRate,proto3" json:"execution_rate,omitempty"`
	Children      []*CategoryBudgetItem  `protobuf:"bytes,6,rep,name=children,proto3" json:"children,omitempty"` // subcategory budget breakdown
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryBudgetItem) Reset() {
	*x = CategoryBudgetItem{}
	mi := &file_dashboard_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryBudgetItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryBudgetItem) ProtoMessage() {}

func (x *CategoryBudgetItem) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryBudgetItem.ProtoReflect.Descriptor instead.
func (*CategoryBudgetItem) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{11}
}

func (x *CategoryBudgetItem) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *CategoryBudgetItem) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *CategoryBudgetItem) GetBudgetAmount() int64 {
	if x != nil {
		return x.BudgetAmount
	}
	return 0
}

func (x *CategoryBudgetItem) GetSpentAmount() int64 {
	if x != nil {
		return x.SpentAmount
	}
	return 0
}

func (x *CategoryBudgetItem) GetExecutionRate() float64 {
	if x != nil {
		return x.ExecutionRate
	}
	return 0
}

func (x *CategoryBudgetItem) GetChildren() []*CategoryBudgetItem {
	if x != nil {
		return x.Children
	}
	return nil
}

var File_dashboard_proto protoreflect.FileDescriptor

const file_dashboard_proto_rawDesc = "" +
	"\n" +
	"\x0fdashboard.proto\x12\x19familyledger.dashboard.v1\"1\n" +
	"\x12GetNetWorthRequest\x12\x1b\n" +
	"\tfamily_id\x18\x01 \x01(\tR\bfamilyId\"\xe9\x02\n" +
	"\bNetWorth\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12\"\n" +
	"\rcash_and_bank\x18\x02 \x01(\x03R\vcashAndBank\x12)\n" +
	"\x10investment_value\x18\x03 \x01(\x03R\x0finvestmentValue\x12*\n" +
	"\x11fixed_asset_value\x18\x04 \x01(\x03R\x0ffixedAssetValue\x12!\n" +
	"\floan_balance\x18\x05 \x01(\x03R\vloanBalance\x123\n" +
	"\x16change_from_last_month\x18\x06 \x01(\x03R\x13changeFromLastMonth\x12%\n" +
	"\x0echange_percent\x18\a \x01(\x01R\rchangePercent\x12M\n" +
	"\vcomposition\x18\b \x03(\v2+.familyledger.dashboard.v1.AssetCompositionR\vcomposition\"r\n" +
	"\x10AssetComposition\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x03R\x05value\x12\x16\n" +
	"\x06weight\x18\x04 \x01(\x01R\x06weight\"r\n" +
	"\fTrendRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tfamily_id\x18\x02 \x01(\tR\bfamilyId\x12\x16\n" +
	"\x06period\x18\x03 \x01(\tR\x06period\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x05R\x05count\"N\n" +
	"\rTrendResponse\x12=\n" +
	"\x06points\x18\x01 \x03(\v2%.familyledger.dashboard.v1.TrendPointR\x06points\"f\n" +
	"\n" +
	"TrendPoint\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x16\n" +
	"\x06income\x18\x02 \x01(\x03R\x06income\x12\x18\n" +
	"\aexpense\x18\x03 \x01(\x03R\aexpense\x12\x10\n" +
	"\x03net\x18\x04 \x01(\x03R\x03net\"\x8e\x01\n" +
	"\x18CategoryBreakdownRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tfamily_id\x18\x02 \x01(\tR\bfamilyId\x12\x12\n" +
	"\x04year\x18\x03 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x04 \x01(\x05R\x05month\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\"p\n" +
	"\x19CategoryBreakdownResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12=\n" +
	"\x05items\x18\x02 \x03(\v2'.familyledger.dashboard.v1.CategoryItemR\x05items\"\xf8\x01\n" +
	"\fCategoryItem\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\tR\n" +
	"categoryId\x12#\n" +
	"\rcategory_name\x18\x02 \x01(\tR\fcategoryName\x12\x12\n" +
	"\x04icon\x18\x03 \x01(\tR\x04icon\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12\x16\n" +
	"\x06weight\x18\x05 \x01(\x01R\x06weight\x12C\n" +
	"\bchildren\x18\x06 \x03(\v2'.familyledger.dashboard.v1.CategoryItemR\bchildren\x12\x19\n" +
	"\bicon_key\x18\a \x01(\tR\aiconKey\"]\n" +
	"\x14BudgetSummaryRequest\x12\x1b\n" +
	"\tfamily_id\x18\x01 \x01(\tR\bfamilyId\x12\x12\n" +
	"\x04year\x18\x02 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x03 \x01(\x05R\x05month\"\xd1\x01\n" +
	"\x15BudgetSummaryResponse\x12!\n" +
	"\ftotal_budget\x18\x01 \x01(\x03R\vtotalBudget\x12\x1f\n" +
	"\vtotal_spent\x18\x02 \x01(\x03R\n" +
	"totalSpent\x12%\n" +
	"\x0eexecution_rate\x18\x03 \x01(\x01R\rexecutionRate\x12M\n" +
	"\n" +
	"categories\x18\x04 \x03(\v2-.familyledger.dashboard.v1.CategoryBudgetItemR\n" +
	"categories\"\x94\x02\n" +
	"\x12CategoryBudgetItem\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\tR\n" +
	"categoryId\x12#\n" +
	"\rcategory_name\x18\x02 \x01(\tR\fcategoryName\x12#\n" +
	"\rbudget_amount\x18\x03 \x01(\x03R\fbudgetAmount\x12!\n" +
	"\fspent_amount\x18\x04 \x01(\x03R\vspentAmount\x12%\n" +
	"\x0eexecution_rate\x18\x05 \x01(\x01R\rexecutionRate\x12I\n" +
	"\bchildren\x18\x06 \x03(\v2-.familyledger.dashboard.v1.CategoryBudgetItemR\bchildren2\xc3\x04\n" +
	"\x10DashboardService\x12a\n" +
	"\vGetNetWorth\x12-.familyledger.dashboard.v1.GetNetWorthRequest\x1a#.familyledger.dashboard.v1.NetWorth\x12j\n" +
	"\x15GetIncomeExpenseTrend\x12'.familyledger.dashboard.v1.TrendRequest\x1a(.familyledger.dashboard.v1.TrendResponse\x12\x81\x01\n" +
	"\x14GetCategoryBreakdown\x123.familyledger.dashboard.v1.CategoryBreakdownRequest\x1a4.familyledger.dashboard.v1.CategoryBreakdownResponse\x12u\n" +
	"\x10GetBudgetSummary\x12/.familyledger.dashboard.v1.BudgetSummaryRequest\x1a0.familyledger.dashboard.v1.BudgetSummaryResponse\x12e\n" +
	"\x10GetNetWorthTrend\x12'.familyledger.dashboard.v1.TrendRequest\x1a(.familyledger.dashboard.v1.TrendResponseB0Z.github.com/familyledger/server/proto/dashboardb\x06proto3"

var (
	file_dashboard_proto_rawDescOnce sync.Once
	file_dashboard_proto_rawDescData []byte
)

func file_dashboard_proto_rawDescGZIP() []byte {
	file_dashboard_proto_rawDescOnce.Do(func() {
		file_dashboard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dashboard_proto_rawDesc), len(file_dashboard_proto_rawDesc)))
	})
	return file_dashboard_proto_rawDescData
}

var file_dashboard_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_dashboard_proto_goTypes = []any{
	(*GetNetWorthRequest)(nil),        // 0: familyledger.dashboard.v1.GetNetWorthRequest
	(*NetWorth)(nil),                  // 1: familyledger.dashboard.v1.NetWorth
	(*AssetComposition)(nil),          // 2: familyledger.dashboard.v1.AssetComposition
	(*TrendRequest)(nil),              // 3: familyledger.dashboard.v1.TrendRequest
	(*TrendResponse)(nil),             // 4: familyledger.dashboard.v1.TrendResponse
	(*TrendPoint)(nil),                // 5: familyledger.dashboard.v1.TrendPoint
	(*CategoryBreakdownRequest)(nil),  // 6: familyledger.dashboard.v1.CategoryBreakdownRequest
	(*CategoryBreakdownResponse)(nil), // 7: familyledger.dashboard.v1.CategoryBreakdownResponse
	(*CategoryItem)(nil),              // 8: familyledger.dashboard.v1.CategoryItem
	(*BudgetSummaryRequest)(nil),      // 9: familyledger.dashboard.v1.BudgetSummaryRequest
	(*BudgetSummaryResponse)(nil),     // 10: familyledger.dashboard.v1.BudgetSummaryResponse
	(*CategoryBudgetItem)(nil),        // 11: familyledger.dashboard.v1.CategoryBudgetItem
}
var file_dashboard_proto_depIdxs = []int32{
	2,  // 0: familyledger.dashboard.v1.NetWorth.composition:type_name -> familyledger.dashboard.v1.AssetComposition
	5,  // 1: familyledger.dashboard.v1.TrendResponse.points:type_name -> familyledger.dashboard.v1.TrendPoint
	8,  // 2: familyledger.dashboard.v1.CategoryBreakdownResponse.items:type_name -> familyledger.dashboard.v1.CategoryItem
	8,  // 3: familyledger.dashboard.v1.CategoryItem.children:type_name -> familyledger.dashboard.v1.CategoryItem
	11, // 4: familyledger.dashboard.v1.BudgetSummaryResponse.categories:type_name -> familyledger.dashboard.v1.CategoryBudgetItem
	11, // 5: familyledger.dashboard.v1.CategoryBudgetItem.children:type_name -> familyledger.dashboard.v1.CategoryBudgetItem
	0,  // 6: familyledger.dashboard.v1.DashboardService.GetNetWorth:input_type -> familyledger.dashboard.v1.GetNetWorthRequest
	3,  // 7: familyledger.dashboard.v1.DashboardService.GetIncomeExpenseTrend:input_type -> familyledger.dashboard.v1.TrendRequest
	6,  // 8: familyledger.dashboard.v1.DashboardService.GetCategoryBreakdown:input_type -> familyledger.dashboard.v1.CategoryBreakdownRequest
	9,  // 9: familyledger.dashboard.v1.DashboardService.GetBudgetSummary:input_type -> familyledger.dashboard.v1.BudgetSummaryRequest
	3,  // 10: familyledger.dashboard.v1.DashboardService.GetNetWorthTrend:input_type -> familyledger.dashboard.v1.TrendRequest
	1,  // 11: familyledger.dashboard.v1.DashboardService.GetNetWorth:output_type -> familyledger.dashboard.v1.NetWorth
	4,  // 12: familyledger.dashboard.v1.DashboardService.GetIncomeExpenseTrend:output_type -> familyledger.dashboard.v1.TrendResponse
	7,  // 13: familyledger.dashboard.v1.DashboardService.GetCategoryBreakdown:output_type -> familyledger.dashboard.v1.CategoryBreakdownResponse
	10, // 14: familyledger.dashboard.v1.DashboardService.GetBudgetSummary:output_type -> familyledger.dashboard.v1.BudgetSummaryResponse
	4,  // 15: familyledger.dashboard.v1.DashboardService.GetNetWorthTrend:output_type -> familyledger.dashboard.v1.TrendResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_dashboard_proto_init() }
func file_dashboard_proto_init() {
	if File_dashboard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dashboard_proto_rawDesc), len(file_dashboard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dashboard_proto_goTypes,
		DependencyIndexes: file_dashboard_proto_depIdxs,
		MessageInfos:      file_dashboard_proto_msgTypes,
	}.Build()
	File_dashboard_proto = out.File
	file_dashboard_proto_goTypes = nil
	file_dashboard_proto_depIdxs = nil
}
