// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: asset.proto

package asset

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AssetType int32

const (
	AssetType_ASSET_TYPE_UNSPECIFIED AssetType = 0
	AssetType_ASSET_TYPE_REAL_ESTATE AssetType = 1 // 房产
	AssetType_ASSET_TYPE_VEHICLE     AssetType = 2 // 车辆
	AssetType_ASSET_TYPE_ELECTRONICS AssetType = 3 // 电子设备
	AssetType_ASSET_TYPE_FURNITURE   AssetType = 4 // 家具家电
	AssetType_ASSET_TYPE_JEWELRY     AssetType = 5 // 珠宝收藏
	AssetType_ASSET_TYPE_OTHER       AssetType = 6
)

// Enum value maps for AssetType.
var (
	AssetType_name = map[int32]string{
		0: "ASSET_TYPE_UNSPECIFIED",
		1: "ASSET_TYPE_REAL_ESTATE",
		2: "ASSET_TYPE_VEHICLE",
		3: "ASSET_TYPE_ELECTRONICS",
		4: "ASSET_TYPE_FURNITURE",
		5: "ASSET_TYPE_JEWELRY",
		6: "ASSET_TYPE_OTHER",
	}
	AssetType_value = map[string]int32{
		"ASSET_TYPE_UNSPECIFIED": 0,
		"ASSET_TYPE_REAL_ESTATE": 1,
		"ASSET_TYPE_VEHICLE":     2,
		"ASSET_TYPE_ELECTRONICS": 3,
		"ASSET_TYPE_FURNITURE":   4,
		"ASSET_TYPE_JEWELRY":     5,
		"ASSET_TYPE_OTHER":       6,
	}
)

func (x AssetType) Enum() *AssetType {
	p := new(AssetType)
	*p = x
	return p
}

func (x AssetType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AssetType) Descriptor() protoreflect.EnumDescriptor {
	return file_asset_proto_enumTypes[0].Descriptor()
}

func (AssetType) Type() protoreflect.EnumType {
	return &file_asset_proto_enumTypes[0]
}

func (x AssetType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AssetType.Descriptor instead.
func (AssetType) EnumDescriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{0}
}

type DepreciationMethod int32

const (
	DepreciationMethod_DEPRECIATION_METHOD_UNSPECIFIED      DepreciationMethod = 0
	DepreciationMethod_DEPRECIATION_METHOD_STRAIGHT_LINE    DepreciationMethod = 1 // 直线法
	DepreciationMethod_DEPRECIATION_METHOD_DOUBLE_DECLINING DepreciationMethod = 2 // 双倍余额递减法
	DepreciationMethod_DEPRECIATION_METHOD_NONE             DepreciationMethod = 3 // 不折旧（如房产可能升值）
)

// Enum value maps for DepreciationMethod.
var (
	DepreciationMethod_name = map[int32]string{
		0: "DEPRECIATION_METHOD_UNSPECIFIED",
		1: "DEPRECIATION_METHOD_STRAIGHT_LINE",
		2: "DEPRECIATION_METHOD_DOUBLE_DECLINING",
		3: "DEPRECIATION_METHOD_NONE",
	}
	DepreciationMethod_value = map[string]int32{
		"DEPRECIATION_METHOD_UNSPECIFIED":      0,
		"DEPRECIATION_METHOD_STRAIGHT_LINE":    1,
		"DEPRECIATION_METHOD_DOUBLE_DECLINING": 2,
		"DEPRECIATION_METHOD_NONE":             3,
	}
)

func (x DepreciationMethod) Enum() *DepreciationMethod {
	p := new(DepreciationMethod)
	*p = x
	return p
}

func (x DepreciationMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DepreciationMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_asset_proto_enumTypes[1].Descriptor()
}

func (DepreciationMethod) Type() protoreflect.EnumType {
	return &file_asset_proto_enumTypes[1]
}

func (x DepreciationMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DepreciationMethod.Descriptor instead.
func (DepreciationMethod) EnumDescriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{1}
}

type Asset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	AssetType     AssetType              `protobuf:"varint,4,opt,name=asset_type,json=assetType,proto3,enum=familyledger.asset.v1.AssetType" json:"asset_type,omitempty"`
	PurchasePrice int64                  `protobuf:"varint,5,opt,name=purchase_price,json=purchasePrice,proto3" json:"purchase_price,omitempty"` // 购入价（分）
	CurrentValue  int64                  `protobuf:"varint,6,opt,name=current_value,json=currentValue,proto3" json:"current_value,omitempty"`    // 当前净值（分）
	PurchaseDate  *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=purchase_date,json=purchaseDate,proto3" json:"purchase_date,omitempty"`
	Description   string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	FamilyId      string                 `protobuf:"bytes,11,opt,name=family_id,json=familyId,proto3" json:"family_id,omitempty"` // 家庭 ID（空 = 个人资产）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Asset) Reset() {
	*x = Asset{}
	mi := &file_asset_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Asset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Asset) ProtoMessage() {}

func (x *Asset) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Asset.ProtoReflect.Descriptor instead.
func (*Asset) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{0}
}

func (x *Asset) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Asset) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Asset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Asset) GetAssetType() AssetType {
	if x != nil {
		return x.AssetType
	}
	return AssetType_ASSET_TYPE_UNSPECIFIED
}

func (x *Asset) GetPurchasePrice() int64 {
	if x != nil {
		return x.PurchasePrice
	}
	return 0
}

func (x *Asset) GetCurrentValue() int64 {
	if x != nil {
		return x.CurrentValue
	}
	return 0
}

func (x *Asset) GetPurchaseDate() *timestamppb.Timestamp {
	if x != nil {
		return x.PurchaseDate
	}
	return nil
}

func (x *Asset) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Asset) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Asset) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Asset) GetFamilyId() string {
	if x != nil {
		return x.FamilyId
	}
	return ""
}

type AssetValuation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AssetId       string                 `protobuf:"bytes,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	Value         int64                  `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`  // 估值（分）
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"` // manual / depreciation / market
	ValuationDate *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=valuation_date,json=valuationDate,proto3" json:"valuation_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetValuation) Reset() {
	*x = AssetValuation{}
	mi := &file_asset_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetValuation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetValuation) ProtoMessage() {}

func (x *AssetValuation) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetValuation.ProtoReflect.Descriptor instead.
func (*AssetValuation) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{1}
}

func (x *AssetValuation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AssetValuation) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *AssetValuation) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *AssetValuation) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *AssetValuation) GetValuationDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ValuationDate
	}
	return nil
}

type DepreciationRule struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AssetId         string                 `protobuf:"bytes,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	Method          DepreciationMethod     `protobuf:"varint,3,opt,name=method,proto3,enum=familyledger.asset.v1.DepreciationMethod" json:"method,omitempty"`
	UsefulLifeYears int32                  `protobuf:"varint,4,opt,name=useful_life_years,json=usefulLifeYears,proto3" json:"useful_life_years,omitempty"` // 使用年限
	SalvageRate     float64                `protobuf:"fixed64,5,opt,name=salvage_rate,json=salvageRate,proto3" json:"salvage_rate,omitempty"`              // 残值率 0-1
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DepreciationRule) Reset() {
	*x = DepreciationRule{}
	mi := &file_asset_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepreciationRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepreciationRule) ProtoMessage() {}

func (x *DepreciationRule) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepreciationRule.ProtoReflect.Descriptor instead.
func (*DepreciationRule) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{2}
}

func (x *DepreciationRule) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DepreciationRule) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *DepreciationRule) GetMethod() DepreciationMethod {
	if x != nil {
		return x.Method
	}
	return DepreciationMethod_DEPRECIATION_METHOD_UNSPECIFIED
}

func (x *DepreciationRule) GetUsefulLifeYears() int32 {
	if x != nil {
		return x.UsefulLifeYears
	}
	return 0
}

func (x *DepreciationRule) GetSalvageRate() float64 {
	if x != nil {
		return x.SalvageRate
	}
	return 0
}

func (x *DepreciationRule) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateAssetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	AssetType     AssetType              `protobuf:"varint,2,opt,name=asset_type,json=assetType,proto3,enum=familyledger.asset.v1.AssetType" json:"asset_type,omitempty"`
	PurchasePrice int64                  `protobuf:"varint,3,opt,name=purchase_price,json=purchasePrice,proto3" json:"purchase_price,omitempty"`
	PurchaseDate  *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=purchase_date,json=purchaseDate,proto3" json:"purchase_date,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	FamilyId      string                 `protobuf:"bytes,6,opt,name=family_id,json=familyId,proto3" json:"family_id,omitempty"` // 家庭 ID（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAssetRequest) Reset() {
	*x = CreateAssetRequest{}
	mi := &file_asset_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAssetRequest) ProtoMessage() {}

func (x *CreateAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAssetRequest.ProtoReflect.Descriptor instead.
func (*CreateAssetRequest) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{3}
}

func (x *CreateAssetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAssetRequest) GetAssetType() AssetType {
	if x != nil {
		return x.AssetType
	}
	return AssetType_ASSET_TYPE_UNSPECIFIED
}

func (x *CreateAssetRequest) GetPurchasePrice() int64 {
	if x != nil {
		return x.PurchasePrice
	}
	return 0
}

func (x *CreateAssetRequest) GetPurchaseDate() *timestamppb.Timestamp {
	if x != nil {
		return x.PurchaseDate
	}
	return nil
}

func (x *CreateAssetRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateAssetRequest) GetFamilyId() string {
	if x != nil {
		return x.FamilyId
	}
	return ""
}

type GetAssetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetId       string                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssetRequest) Reset() {
	*x = GetAssetRequest{}
	mi := &file_asset_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssetRequest) ProtoMessage() {}

func (x *GetAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssetRequest.ProtoReflect.Descriptor instead.
func (*GetAssetRequest) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{4}
}

func (x *GetAssetRequest) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

type ListAssetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetType     AssetType              `protobuf:"varint,1,opt,name=asset_type,json=assetType,proto3,enum=familyledger.asset.v1.AssetType" json:"asset_type,omitempty"` // optional filter
	FamilyId      string                 `protobuf:"bytes,2,opt,name=family_id,json=familyId,proto3" json:"family_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAssetsRequest) Reset() {
	*x = ListAssetsRequest{}
	mi := &file_asset_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAssetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAssetsRequest) ProtoMessage() {}

func (x *ListAssetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAssetsRequest.ProtoReflect.Descriptor instead.
func (*ListAssetsRequest) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{5}
}

func (x *ListAssetsRequest) GetAssetType() AssetType {
	if x != nil {
		return x.AssetType
	}
	return AssetType_ASSET_TYPE_UNSPECIFIED
}

func (x *ListAssetsRequest) GetFamilyId() string {
	if x != nil {
		return x.FamilyId
	}
	return ""
}

type ListAssetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assets        []*Asset               `protobuf:"bytes,1,rep,name=assets,proto3" json:"assets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAssetsResponse) Reset() {
	*x = ListAssetsResponse{}
	mi := &file_asset_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAssetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAssetsResponse) ProtoMessage() {}

func (x *ListAssetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAssetsResponse.ProtoReflect.Descriptor instead.
func (*ListAssetsResponse) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{6}
}

func (x *ListAssetsResponse) GetAssets() []*Asset {
	if x != nil {
		return x.Assets
	}
	return nil
}

type UpdateAssetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetId       string                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAssetRequest) Reset() {
	*x = UpdateAssetRequest{}
	mi := &file_asset_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAssetRequest) ProtoMessage() {}

func (x *UpdateAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAssetRequest.ProtoReflect.Descriptor instead.
func (*UpdateAssetRequest) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateAssetRequest) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *UpdateAssetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateAssetRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type DeleteAssetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetId       string                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAssetRequest) Reset() {
	*x = DeleteAssetRequest{}
	mi := &file_asset_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAssetRequest) ProtoMessage() {}

func (x *DeleteAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAssetRequest.ProtoReflect.Descriptor instead.
func (*DeleteAssetRequest) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteAssetRequest) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

type UpdateValuationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetId       string                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	Value         int64                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"` // manual / market
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateValuationRequest) Reset() {
	*x = UpdateValuationRequest{}
	mi := &file_asset_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateValuationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateValuationRequest) ProtoMessage() {}

func (x *UpdateValuationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateValuationRequest.ProtoReflect.Descriptor instead.
func (*UpdateValuationRequest) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateValuationRequest) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *UpdateValuationRequest) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *UpdateValuationRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type ListValuationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetId       string                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListValuationsRequest) Reset() {
	*x = ListValuationsRequest{}
	mi := &file_asset_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListValuationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListValuationsRequest) ProtoMessage() {}

func (x *ListValuationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListValuationsRequest.ProtoReflect.Descriptor instead.
func (*ListValuationsRequest) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{10}
}

func (x *ListValuationsRequest) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

type ListValuationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valuations    []*AssetValuation      `protobuf:"bytes,1,rep,name=valuations,proto3" json:"valuations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListValuationsResponse) Reset() {
	*x = ListValuationsResponse{}
	mi := &file_asset_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListValuationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListValuationsResponse) ProtoMessage() {}

func (x *ListValuationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListValuationsResponse.ProtoReflect.Descriptor instead.
func (*ListValuationsResponse) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{11}
}

func (x *ListValuationsResponse) GetValuations() []*AssetValuation {
	if x != nil {
		return x.Valuations
	}
	return nil
}

type SetDepreciationRuleRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AssetId         string                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	Method          DepreciationMethod     `protobuf:"varint,2,opt,name=method,proto3,enum=familyledger.asset.v1.DepreciationMethod" json:"method,omitempty"`
	UsefulLifeYears int32                  `protobuf:"varint,3,opt,name=useful_life_years,json=usefulLifeYears,proto3" json:"useful_life_years,omitempty"` // 0 = use preset
	SalvageRate     float64                `protobuf:"fixed64,4,opt,name=salvage_rate,json=salvageRate,proto3" json:"salvage_rate,omitempty"`              // 0 = use preset
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SetDepreciationRuleRequest) Reset() {
	*x = SetDepreciationRuleRequest{}
	mi := &file_asset_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDepreciationRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDepreciationRuleRequest) ProtoMessage() {}

func (x *SetDepreciationRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDepreciationRuleRequest.ProtoReflect.Descriptor instead.
func (*SetDepreciationRuleRequest) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{12}
}

func (x *SetDepreciationRuleRequest) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *SetDepreciationRuleRequest) GetMethod() DepreciationMethod {
	if x != nil {
		return x.Method
	}
	return DepreciationMethod_DEPRECIATION_METHOD_UNSPECIFIED
}

func (x *SetDepreciationRuleRequest) GetUsefulLifeYears() int32 {
	if x != nil {
		return x.UsefulLifeYears
	}
	return 0
}

func (x *SetDepreciationRuleRequest) GetSalvageRate() float64 {
	if x != nil {
		return x.SalvageRate
	}
	return 0
}

type RunDepreciationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetId       string                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunDepreciationRequest) Reset() {
	*x = RunDepreciationRequest{}
	mi := &file_asset_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunDepreciationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunDepreciationRequest) ProtoMessage() {}

func (x *RunDepreciationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_asset_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunDepreciationRequest.ProtoReflect.Descriptor instead.
func (*RunDepreciationRequest) Descriptor() ([]byte, []int) {
	return file_asset_proto_rawDescGZIP(), []int{13}
}

func (x *RunDepreciationRequest) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

var File_asset_proto protoreflect.FileDescriptor

const file_asset_proto_rawDesc = "" +
	"\n" +
	"\vasset.proto\x12\x15familyledger.asset.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xc7\x03\n" +
	"\x05Asset\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12?\n" +
	"\n" +
	"asset_type\x18\x04 \x01(\x0e2 .familyledger.asset.v1.AssetTypeR\tassetType\x12%\n" +
	"\x0epurchase_price\x18\x05 \x01(\x03R\rpurchasePrice\x12#\n" +
	"\rcurrent_value\x18\x06 \x01(\x03R\fcurrentValue\x12?\n" +
	"\rpurchase_date\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\fpurchaseDate\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1b\n" +
	"\tfamily_id\x18\v \x01(\tR\bfamilyId\"\xac\x01\n" +
	"\x0eAssetValuation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\basset_id\x18\x02 \x01(\tR\aassetId\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x03R\x05value\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12A\n" +
	"\x0evaluation_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\rvaluationDate\"\x8a\x02\n" +
	"\x10DepreciationRule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\basset_id\x18\x02 \x01(\tR\aassetId\x12A\n" +
	"\x06method\x18\x03 \x01(\x0e2).familyledger.asset.v1.DepreciationMethodR\x06method\x12*\n" +
	"\x11useful_life_years\x18\x04 \x01(\x05R\x0fusefulLifeYears\x12!\n" +
	"\fsalvage_rate\x18\x05 \x01(\x01R\vsalvageRate\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x90\x02\n" +
	"\x12CreateAssetRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12?\n" +
	"\n" +
	"asset_type\x18\x02 \x01(\x0e2 .familyledger.asset.v1.AssetTypeR\tassetType\x12%\n" +
	"\x0epurchase_price\x18\x03 \x01(\x03R\rpurchasePrice\x12?\n" +
	"\rpurchase_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\fpurchaseDate\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1b\n" +
	"\tfamily_id\x18\x06 \x01(\tR\bfamilyId\",\n" +
	"\x0fGetAssetRequest\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\tR\aassetId\"q\n" +
	"\x11ListAssetsRequest\x12?\n" +
	"\n" +
	"asset_type\x18\x01 \x01(\x0e2 .familyledger.asset.v1.AssetTypeR\tassetType\x12\x1b\n" +
	"\tfamily_id\x18\x02 \x01(\tR\bfamilyId\"J\n" +
	"\x12ListAssetsResponse\x124\n" +
	"\x06assets\x18\x01 \x03(\v2\x1c.familyledger.asset.v1.AssetR\x06assets\"e\n" +
	"\x12UpdateAssetRequest\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\tR\aassetId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"/\n" +
	"\x12DeleteAssetRequest\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\tR\aassetId\"a\n" +
	"\x16UpdateValuationRequest\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\tR\aassetId\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\"2\n" +
	"\x15ListValuationsRequest\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\tR\aassetId\"_\n" +
	"\x16ListValuationsResponse\x12E\n" +
	"\n" +
	"valuations\x18\x01 \x03(\v2%.familyledger.asset.v1.AssetValuationR\n" +
	"valuations\"\xc9\x01\n" +
	"\x1aSetDepreciationRuleRequest\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\tR\aassetId\x12A\n" +
	"\x06method\x18\x02 \x01(\x0e2).familyledger.asset.v1.DepreciationMethodR\x06method\x12*\n" +
	"\x11useful_life_years\x18\x03 \x01(\x05R\x0fusefulLifeYears\x12!\n" +
	"\fsalvage_rate\x18\x04 \x01(\x01R\vsalvageRate\"3\n" +
	"\x16RunDepreciationRequest\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\tR\aassetId*\xbf\x01\n" +
	"\tAssetType\x12\x1a\n" +
	"\x16ASSET_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16ASSET_TYPE_REAL_ESTATE\x10\x01\x12\x16\n" +
	"\x12ASSET_TYPE_VEHICLE\x10\x02\x12\x1a\n" +
	"\x16ASSET_TYPE_ELECTRONICS\x10\x03\x12\x18\n" +
	"\x14ASSET_TYPE_FURNITURE\x10\x04\x12\x16\n" +
	"\x12ASSET_TYPE_JEWELRY\x10\x05\x12\x14\n" +
	"\x10ASSET_TYPE_OTHER\x10\x06*\xa8\x01\n" +
	"\x12DepreciationMethod\x12#\n" +
	"\x1fDEPRECIATION_METHOD_UNSPECIFIED\x10\x00\x12%\n" +
	"!DEPRECIATION_METHOD_STRAIGHT_LINE\x10\x01\x12(\n" +
	"$DEPRECIATION_METHOD_DOUBLE_DECLINING\x10\x02\x12\x1c\n" +
	"\x18DEPRECIATION_METHOD_NONE\x10\x032\xf0\x06\n" +
	"\fAssetService\x12V\n" +
	"\vCreateAsset\x12).familyledger.asset.v1.CreateAssetRequest\x1a\x1c.familyledger.asset.v1.Asset\x12P\n" +
	"\bGetAsset\x12&.familyledger.asset.v1.GetAssetRequest\x1a\x1c.familyledger.asset.v1.Asset\x12a\n" +
	"\n" +
	"ListAssets\x12(.familyledger.asset.v1.ListAssetsRequest\x1a).familyledger.asset.v1.ListAssetsResponse\x12V\n" +
	"\vUpdateAsset\x12).familyledger.asset.v1.UpdateAssetRequest\x1a\x1c.familyledger.asset.v1.Asset\x12P\n" +
	"\vDeleteAsset\x12).familyledger.asset.v1.DeleteAssetRequest\x1a\x16.google.protobuf.Empty\x12g\n" +
	"\x0fUpdateValuation\x12-.familyledger.asset.v1.UpdateValuationRequest\x1a%.familyledger.asset.v1.AssetValuation\x12m\n" +
	"\x0eListValuations\x12,.familyledger.asset.v1.ListValuationsRequest\x1a-.familyledger.asset.v1.ListValuationsResponse\x12q\n" +
	"\x13SetDepreciationRule\x121.familyledger.asset.v1.SetDepreciationRuleRequest\x1a'.familyledger.asset.v1.DepreciationRule\x12^\n" +
	"\x0fRunDepreciation\x12-.familyledger.asset.v1.RunDepreciationRequest\x1a\x1c.familyledger.asset.v1.AssetB,Z*github.com/familyledger/server/proto/assetb\x06proto3"

var (
	file_asset_proto_rawDescOnce sync.Once
	file_asset_proto_rawDescData []byte
)

func file_asset_proto_rawDescGZIP() []byte {
	file_asset_proto_rawDescOnce.Do(func() {
		file_asset_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_asset_proto_rawDesc), len(file_asset_proto_rawDesc)))
	})
	return file_asset_proto_rawDescData
}

var file_asset_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_asset_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_asset_proto_goTypes = []any{
	(AssetType)(0),                     // 0: familyledger.asset.v1.AssetType
	(DepreciationMethod)(0),            // 1: familyledger.asset.v1.DepreciationMethod
	(*Asset)(nil),                      // 2: familyledger.asset.v1.Asset
	(*AssetValuation)(nil),             // 3: familyledger.asset.v1.AssetValuation
	(*DepreciationRule)(nil),           // 4: familyledger.asset.v1.DepreciationRule
	(*CreateAssetRequest)(nil),         // 5: familyledger.asset.v1.CreateAssetRequest
	(*GetAssetRequest)(nil),            // 6: familyledger.asset.v1.GetAssetRequest
	(*ListAssetsRequest)(nil),          // 7: familyledger.asset.v1.ListAssetsRequest
	(*ListAssetsResponse)(nil),         // 8: familyledger.asset.v1.ListAssetsResponse
	(*UpdateAssetRequest)(nil),         // 9: familyledger.asset.v1.UpdateAssetRequest
	(*DeleteAssetRequest)(nil),         // 10: familyledger.asset.v1.DeleteAssetRequest
	(*UpdateValuationRequest)(nil),     // 11: familyledger.asset.v1.UpdateValuationRequest
	(*ListValuationsRequest)(nil),      // 12: familyledger.asset.v1.ListValuationsRequest
	(*ListValuationsResponse)(nil),     // 13: familyledger.asset.v1.ListValuationsResponse
	(*SetDepreciationRuleRequest)(nil), // 14: familyledger.asset.v1.SetDepreciationRuleRequest
	(*RunDepreciationRequest)(nil),     // 15: familyledger.asset.v1.RunDepreciationRequest
	(*timestamppb.Timestamp)(nil),      // 16: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),              // 17: google.protobuf.Empty
}
var file_asset_proto_depIdxs = []int32{
	0,  // 0: familyledger.asset.v1.Asset.asset_type:type_name -> familyledger.asset.v1.AssetType
	16, // 1: familyledger.asset.v1.Asset.purchase_date:type_name -> google.protobuf.Timestamp
	16, // 2: familyledger.asset.v1.Asset.created_at:type_name -> google.protobuf.Timestamp
	16, // 3: familyledger.asset.v1.Asset.updated_at:type_name -> google.protobuf.Timestamp
	16, // 4: familyledger.asset.v1.AssetValuation.valuation_date:type_name -> google.protobuf.Timestamp
	1,  // 5: familyledger.asset.v1.DepreciationRule.method:type_name -> familyledger.asset.v1.DepreciationMethod
	16, // 6: familyledger.asset.v1.DepreciationRule.created_at:type_name -> google.protobuf.Timestamp
	0,  // 7: familyledger.asset.v1.CreateAssetRequest.asset_type:type_name -> familyledger.asset.v1.AssetType
	16, // 8: familyledger.asset.v1.CreateAssetRequest.purchase_date:type_name -> google.protobuf.Timestamp
	0,  // 9: familyledger.asset.v1.ListAssetsRequest.asset_type:type_name -> familyledger.asset.v1.AssetType
	2,  // 10: familyledger.asset.v1.ListAssetsResponse.assets:type_name -> familyledger.asset.v1.Asset
	3,  // 11: familyledger.asset.v1.ListValuationsResponse.valuations:type_name -> familyledger.asset.v1.AssetValuation
	1,  // 12: familyledger.asset.v1.SetDepreciationRuleRequest.method:type_name -> familyledger.asset.v1.DepreciationMethod
	5,  // 13: familyledger.asset.v1.AssetService.CreateAsset:input_type -> familyledger.asset.v1.CreateAssetRequest
	6,  // 14: familyledger.asset.v1.AssetService.GetAsset:input_type -> familyledger.asset.v1.GetAssetRequest
	7,  // 15: familyledger.asset.v1.AssetService.ListAssets:input_type -> familyledger.asset.v1.ListAssetsRequest
	9,  // 16: familyledger.asset.v1.AssetService.UpdateAsset:input_type -> familyledger.asset.v1.UpdateAssetRequest
	10, // 17: familyledger.asset.v1.AssetService.DeleteAsset:input_type -> familyledger.asset.v1.DeleteAssetRequest
	11, // 18: familyledger.asset.v1.AssetService.UpdateValuation:input_type -> familyledger.asset.v1.UpdateValuationRequest
	12, // 19: familyledger.asset.v1.AssetService.ListValuations:input_type -> familyledger.asset.v1.ListValuationsRequest
	14, // 20: familyledger.asset.v1.AssetService.SetDepreciationRule:input_type -> familyledger.asset.v1.SetDepreciationRuleRequest
	15, // 21: familyledger.asset.v1.AssetService.RunDepreciation:input_type -> familyledger.asset.v1.RunDepreciationRequest
	2,  // 22: familyledger.asset.v1.AssetService.CreateAsset:output_type -> familyledger.asset.v1.Asset
	2,  // 23: familyledger.asset.v1.AssetService.GetAsset:output_type -> familyledger.asset.v1.Asset
	8,  // 24: familyledger.asset.v1.AssetService.ListAssets:output_type -> familyledger.asset.v1.ListAssetsResponse
	2,  // 25: familyledger.asset.v1.AssetService.UpdateAsset:output_type -> familyledger.asset.v1.Asset
	17, // 26: familyledger.asset.v1.AssetService.DeleteAsset:output_type -> google.protobuf.Empty
	3,  // 27: familyledger.asset.v1.AssetService.UpdateValuation:output_type -> familyledger.asset.v1.AssetValuation
	13, // 28: familyledger.asset.v1.AssetService.ListValuations:output_type -> familyledger.asset.v1.ListValuationsResponse
	4,  // 29: familyledger.asset.v1.AssetService.SetDepreciationRule:output_type -> familyledger.asset.v1.DepreciationRule
	2,  // 30: familyledger.asset.v1.AssetService.RunDepreciation:output_type -> familyledger.asset.v1.Asset
	22, // [22:31] is the sub-list for method output_type
	13, // [13:22] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_asset_proto_init() }
func file_asset_proto_init() {
	if File_asset_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_asset_proto_rawDesc), len(file_asset_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_asset_proto_goTypes,
		DependencyIndexes: file_asset_proto_depIdxs,
		EnumInfos:         file_asset_proto_enumTypes,
		MessageInfos:      file_asset_proto_msgTypes,
	}.Build()
	File_asset_proto = out.File
	file_asset_proto_goTypes = nil
	file_asset_proto_depIdxs = nil
}
