// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/notify.proto

package notify

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotificationSettings struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	BudgetAlert        bool                   `protobuf:"varint,1,opt,name=budget_alert,json=budgetAlert,proto3" json:"budget_alert,omitempty"`
	BudgetWarning      bool                   `protobuf:"varint,2,opt,name=budget_warning,json=budgetWarning,proto3" json:"budget_warning,omitempty"`
	DailySummary       bool                   `protobuf:"varint,3,opt,name=daily_summary,json=dailySummary,proto3" json:"daily_summary,omitempty"`
	LoanReminder       bool                   `protobuf:"varint,4,opt,name=loan_reminder,json=loanReminder,proto3" json:"loan_reminder,omitempty"`
	ReminderDaysBefore int32                  `protobuf:"varint,5,opt,name=reminder_days_before,json=reminderDaysBefore,proto3" json:"reminder_days_before,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *NotificationSettings) Reset() {
	*x = NotificationSettings{}
	mi := &file_proto_notify_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationSettings) ProtoMessage() {}

func (x *NotificationSettings) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notify_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationSettings.ProtoReflect.Descriptor instead.
func (*NotificationSettings) Descriptor() ([]byte, []int) {
	return file_proto_notify_proto_rawDescGZIP(), []int{0}
}

func (x *NotificationSettings) GetBudgetAlert() bool {
	if x != nil {
		return x.BudgetAlert
	}
	return false
}

func (x *NotificationSettings) GetBudgetWarning() bool {
	if x != nil {
		return x.BudgetWarning
	}
	return false
}

func (x *NotificationSettings) GetDailySummary() bool {
	if x != nil {
		return x.DailySummary
	}
	return false
}

func (x *NotificationSettings) GetLoanReminder() bool {
	if x != nil {
		return x.LoanReminder
	}
	return false
}

func (x *NotificationSettings) GetReminderDaysBefore() int32 {
	if x != nil {
		return x.ReminderDaysBefore
	}
	return 0
}

type Notification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	DataJson      string                 `protobuf:"bytes,6,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"`
	IsRead        bool                   `protobuf:"varint,7,opt,name=is_read,json=isRead,proto3" json:"is_read,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_proto_notify_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notify_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_proto_notify_proto_rawDescGZIP(), []int{1}
}

func (x *Notification) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Notification) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Notification) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Notification) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Notification) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Notification) GetDataJson() string {
	if x != nil {
		return x.DataJson
	}
	return ""
}

func (x *Notification) GetIsRead() bool {
	if x != nil {
		return x.IsRead
	}
	return false
}

func (x *Notification) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type RegisterDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceToken   string                 `protobuf:"bytes,1,opt,name=device_token,json=deviceToken,proto3" json:"device_token,omitempty"`
	Platform      string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	DeviceName    string                 `protobuf:"bytes,3,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDeviceRequest) Reset() {
	*x = RegisterDeviceRequest{}
	mi := &file_proto_notify_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDeviceRequest) ProtoMessage() {}

func (x *RegisterDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notify_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDeviceRequest.ProtoReflect.Descriptor instead.
func (*RegisterDeviceRequest) Descriptor() ([]byte, []int) {
	return file_proto_notify_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterDeviceRequest) GetDeviceToken() string {
	if x != nil {
		return x.DeviceToken
	}
	return ""
}

func (x *RegisterDeviceRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *RegisterDeviceRequest) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

type RegisterDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDeviceResponse) Reset() {
	*x = RegisterDeviceResponse{}
	mi := &file_proto_notify_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDeviceResponse) ProtoMessage() {}

func (x *RegisterDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notify_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDeviceResponse.ProtoReflect.Descriptor instead.
func (*RegisterDeviceResponse) Descriptor() ([]byte, []int) {
	return file_proto_notify_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterDeviceResponse) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type UnregisterDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterDeviceRequest) Reset() {
	*x = UnregisterDeviceRequest{}
	mi := &file_proto_notify_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterDeviceRequest) ProtoMessage() {}

func (x *UnregisterDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notify_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterDeviceRequest.ProtoReflect.Descriptor instead.
func (*UnregisterDeviceRequest) Descriptor() ([]byte, []int) {
	return file_proto_notify_proto_rawDescGZIP(), []int{4}
}

func (x *UnregisterDeviceRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type UnregisterDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterDeviceResponse) Reset() {
	*x = UnregisterDeviceResponse{}
	mi := &file_proto_notify_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterDeviceResponse) ProtoMessage() {}

func (x *UnregisterDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notify_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterDeviceResponse.ProtoReflect.Descriptor instead.
func (*UnregisterDeviceResponse) Descriptor() ([]byte, []int) {
	return file_proto_notify_proto_rawDescGZIP(), []int{5}
}

type GetNotificationSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationSettingsRequest) Reset() {
	*x = GetNotificationSettingsRequest{}
	mi := &file_proto_notify_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationSettingsRequest) ProtoMessage() {}

func (x *GetNotificationSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notify_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationSettingsRequest.ProtoReflect.Descriptor instead.
func (*GetNotificationSettingsRequest) Descriptor() ([]byte, []int) {
	return file_proto_notify_proto_rawDescGZIP(), []int{6}
}

type GetNotificationSettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      *NotificationSettings  `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationSettingsResponse) Reset() {
	*x = GetNotificationSettingsResponse{}
	mi := &file_proto_notify_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationSettingsResponse) ProtoMessage() {}

func (x *GetNotificationSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notify_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationSettingsResponse.ProtoReflect.Descriptor instead.
func (*GetNotificationSettingsResponse) Descriptor() ([]byte, []int) {
	return file_proto_notify_proto_rawDescGZIP(), []int{7}
}

func (x *GetNotificationSettingsResponse) GetSettings() *NotificationSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type UpdateNotificationSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      *NotificationSettings  `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNotificationSettingsRequest) Reset() {
	*x = UpdateNotificationSettingsRequest{}
	mi := &file_proto_notify_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNotificationSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNotificationSettingsRequest) ProtoMessage() {}

func (x *UpdateNotificationSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notify_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNotificationSettingsRequest.ProtoReflect.Descriptor instead.
func (*UpdateNotificationSettingsRequest) Descriptor() ([]byte, []int) {
	return file_proto_notify_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateNotificationSettingsRequest) GetSettings() *NotificationSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type UpdateNotificationSettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNotificationSettingsResponse) Reset() {
	*x = UpdateNotificationSettingsResponse{}
	mi := &file_proto_notify_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNotificationSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNotificationSettingsResponse) ProtoMessage() {}

func (x *UpdateNotificationSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notify_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNotificationSettingsResponse.ProtoReflect.Descriptor instead.
func (*UpdateNotificationSettingsResponse) Descriptor() ([]byte, []int) {
	return file_proto_notify_proto_rawDescGZIP(), []int{9}
}

type ListNotificationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotificationsRequest) Reset() {
	*x = ListNotificationsRequest{}
	mi := &file_proto_notify_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationsRequest) ProtoMessage() {}

func (x *ListNotificationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notify_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationsRequest.ProtoReflect.Descriptor instead.
func (*ListNotificationsRequest) Descriptor() ([]byte, []int) {
	return file_proto_notify_proto_rawDescGZIP(), []int{10}
}

func (x *ListNotificationsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListNotificationsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListNotificationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notifications []*Notification        `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotificationsResponse) Reset() {
	*x = ListNotificationsResponse{}
	mi := &file_proto_notify_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationsResponse) ProtoMessage() {}

func (x *ListNotificationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notify_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationsResponse.ProtoReflect.Descriptor instead.
func (*ListNotificationsResponse) Descriptor() ([]byte, []int) {
	return file_proto_notify_proto_rawDescGZIP(), []int{11}
}

func (x *ListNotificationsResponse) GetNotifications() []*Notification {
	if x != nil {
		return x.Notifications
	}
	return nil
}

func (x *ListNotificationsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type MarkAsReadRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NotificationIds []string               `protobuf:"bytes,1,rep,name=notification_ids,json=notificationIds,proto3" json:"notification_ids,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MarkAsReadRequest) Reset() {
	*x = MarkAsReadRequest{}
	mi := &file_proto_notify_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAsReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAsReadRequest) ProtoMessage() {}

func (x *MarkAsReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notify_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAsReadRequest.ProtoReflect.Descriptor instead.
func (*MarkAsReadRequest) Descriptor() ([]byte, []int) {
	return file_proto_notify_proto_rawDescGZIP(), []int{12}
}

func (x *MarkAsReadRequest) GetNotificationIds() []string {
	if x != nil {
		return x.NotificationIds
	}
	return nil
}

type MarkAsReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAsReadResponse) Reset() {
	*x = MarkAsReadResponse{}
	mi := &file_proto_notify_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAsReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAsReadResponse) ProtoMessage() {}

func (x *MarkAsReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notify_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAsReadResponse.ProtoReflect.Descriptor instead.
func (*MarkAsReadResponse) Descriptor() ([]byte, []int) {
	return file_proto_notify_proto_rawDescGZIP(), []int{13}
}

type Reminder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FamilyId      string                 `protobuf:"bytes,3,opt,name=family_id,json=familyId,proto3" json:"family_id,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	RemindAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=remind_at,json=remindAt,proto3" json:"remind_at,omitempty"`
	RepeatRule    string                 `protobuf:"bytes,7,opt,name=repeat_rule,json=repeatRule,proto3" json:"repeat_rule,omitempty"` // none, daily, weekly, monthly, yearly
	RepeatEndAt   *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=repeat_end_at,json=repeatEndAt,proto3" json:"repeat_end_at,omitempty"`
	IsActive      bool                   `protobuf:"varint,9,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reminder) Reset() {
	*x = Reminder{}
	mi := &file_proto_notify_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reminder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reminder) ProtoMessage() {}

func (x *Reminder) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notify_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reminder.ProtoReflect.Descriptor instead.
func (*Reminder) Descriptor() ([]byte, []int) {
	return file_proto_notify_proto_rawDescGZIP(), []int{14}
}

func (x *Reminder) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Reminder) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Reminder) GetFamilyId() string {
	if x != nil {
		return x.FamilyId
	}
	return ""
}

func (x *Reminder) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Reminder) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Reminder) GetRemindAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RemindAt
	}
	return nil
}

func (x *Reminder) GetRepeatRule() string {
	if x != nil {
		return x.RepeatRule
	}
	return ""
}

func (x *Reminder) GetRepeatEndAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RepeatEndAt
	}
	return nil
}

func (x *Reminder) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Reminder) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Reminder) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateReminderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	RemindAt      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=remind_at,json=remindAt,proto3" json:"remind_at,omitempty"`
	RepeatRule    string                 `protobuf:"bytes,4,opt,name=repeat_rule,json=repeatRule,proto3" json:"repeat_rule,omitempty"` // none, daily, weekly, monthly, yearly
	RepeatEndAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=repeat_end_at,json=repeatEndAt,proto3" json:"repeat_end_at,omitempty"`
	FamilyId      string                 `protobuf:"bytes,6,opt,name=family_id,json=familyId,proto3" json:"family_id,omitempty"` // optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReminderRequest) Reset() {
	*x = CreateReminderRequest{}
	mi := &file_proto_notify_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReminderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReminderRequest) ProtoMessage() {}

func (x *CreateReminderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notify_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReminderRequest.ProtoReflect.Descriptor instead.
func (*CreateReminderRequest) Descriptor() ([]byte, []int) {
	return file_proto_notify_proto_rawDescGZIP(), []int{15}
}

func (x *CreateReminderRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateReminderRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateReminderRequest) GetRemindAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RemindAt
	}
	return nil
}

func (x *CreateReminderRequest) GetRepeatRule() string {
	if x != nil {
		return x.RepeatRule
	}
	return ""
}

func (x *CreateReminderRequest) GetRepeatEndAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RepeatEndAt
	}
	return nil
}

func (x *CreateReminderRequest) GetFamilyId() string {
	if x != nil {
		return x.FamilyId
	}
	return ""
}

type ListRemindersRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FamilyId        string                 `protobuf:"bytes,1,opt,name=family_id,json=familyId,proto3" json:"family_id,omitempty"` // optional: empty = personal reminders only
	IncludeInactive bool                   `protobuf:"varint,2,opt,name=include_inactive,json=includeInactive,proto3" json:"include_inactive,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListRemindersRequest) Reset() {
	*x = ListRemindersRequest{}
	mi := &file_proto_notify_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRemindersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRemindersRequest) ProtoMessage() {}

func (x *ListRemindersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notify_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRemindersRequest.ProtoReflect.Descriptor instead.
func (*ListRemindersRequest) Descriptor() ([]byte, []int) {
	return file_proto_notify_proto_rawDescGZIP(), []int{16}
}

func (x *ListRemindersRequest) GetFamilyId() string {
	if x != nil {
		return x.FamilyId
	}
	return ""
}

func (x *ListRemindersRequest) GetIncludeInactive() bool {
	if x != nil {
		return x.IncludeInactive
	}
	return false
}

type ListRemindersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reminders     []*Reminder            `protobuf:"bytes,1,rep,name=reminders,proto3" json:"reminders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRemindersResponse) Reset() {
	*x = ListRemindersResponse{}
	mi := &file_proto_notify_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRemindersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRemindersResponse) ProtoMessage() {}

func (x *ListRemindersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notify_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRemindersResponse.ProtoReflect.Descriptor instead.
func (*ListRemindersResponse) Descriptor() ([]byte, []int) {
	return file_proto_notify_proto_rawDescGZIP(), []int{17}
}

func (x *ListRemindersResponse) GetReminders() []*Reminder {
	if x != nil {
		return x.Reminders
	}
	return nil
}

type UpdateReminderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReminderId    string                 `protobuf:"bytes,1,opt,name=reminder_id,json=reminderId,proto3" json:"reminder_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	RemindAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=remind_at,json=remindAt,proto3" json:"remind_at,omitempty"`
	RepeatRule    string                 `protobuf:"bytes,5,opt,name=repeat_rule,json=repeatRule,proto3" json:"repeat_rule,omitempty"`
	RepeatEndAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=repeat_end_at,json=repeatEndAt,proto3" json:"repeat_end_at,omitempty"`
	IsActive      bool                   `protobuf:"varint,7,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateReminderRequest) Reset() {
	*x = UpdateReminderRequest{}
	mi := &file_proto_notify_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReminderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReminderRequest) ProtoMessage() {}

func (x *UpdateReminderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notify_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReminderRequest.ProtoReflect.Descriptor instead.
func (*UpdateReminderRequest) Descriptor() ([]byte, []int) {
	return file_proto_notify_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateReminderRequest) GetReminderId() string {
	if x != nil {
		return x.ReminderId
	}
	return ""
}

func (x *UpdateReminderRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateReminderRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateReminderRequest) GetRemindAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RemindAt
	}
	return nil
}

func (x *UpdateReminderRequest) GetRepeatRule() string {
	if x != nil {
		return x.RepeatRule
	}
	return ""
}

func (x *UpdateReminderRequest) GetRepeatEndAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RepeatEndAt
	}
	return nil
}

func (x *UpdateReminderRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type DeleteReminderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReminderId    string                 `protobuf:"bytes,1,opt,name=reminder_id,json=reminderId,proto3" json:"reminder_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReminderRequest) Reset() {
	*x = DeleteReminderRequest{}
	mi := &file_proto_notify_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReminderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReminderRequest) ProtoMessage() {}

func (x *DeleteReminderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notify_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReminderRequest.ProtoReflect.Descriptor instead.
func (*DeleteReminderRequest) Descriptor() ([]byte, []int) {
	return file_proto_notify_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteReminderRequest) GetReminderId() string {
	if x != nil {
		return x.ReminderId
	}
	return ""
}

var File_proto_notify_proto protoreflect.FileDescriptor

const file_proto_notify_proto_rawDesc = "" +
	"\n" +
	"\x12proto/notify.proto\x12\x16familyledger.notify.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xdc\x01\n" +
	"\x14NotificationSettings\x12!\n" +
	"\fbudget_alert\x18\x01 \x01(\bR\vbudgetAlert\x12%\n" +
	"\x0ebudget_warning\x18\x02 \x01(\bR\rbudgetWarning\x12#\n" +
	"\rdaily_summary\x18\x03 \x01(\bR\fdailySummary\x12#\n" +
	"\rloan_reminder\x18\x04 \x01(\bR\floanReminder\x120\n" +
	"\x14reminder_days_before\x18\x05 \x01(\x05R\x12reminderDaysBefore\"\xe6\x01\n" +
	"\fNotification\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x05 \x01(\tR\x04body\x12\x1b\n" +
	"\tdata_json\x18\x06 \x01(\tR\bdataJson\x12\x17\n" +
	"\ais_read\x18\a \x01(\bR\x06isRead\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"w\n" +
	"\x15RegisterDeviceRequest\x12!\n" +
	"\fdevice_token\x18\x01 \x01(\tR\vdeviceToken\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x12\x1f\n" +
	"\vdevice_name\x18\x03 \x01(\tR\n" +
	"deviceName\"5\n" +
	"\x16RegisterDeviceResponse\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\"6\n" +
	"\x17UnregisterDeviceRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\"\x1a\n" +
	"\x18UnregisterDeviceResponse\" \n" +
	"\x1eGetNotificationSettingsRequest\"k\n" +
	"\x1fGetNotificationSettingsResponse\x12H\n" +
	"\bsettings\x18\x01 \x01(\v2,.familyledger.notify.v1.NotificationSettingsR\bsettings\"m\n" +
	"!UpdateNotificationSettingsRequest\x12H\n" +
	"\bsettings\x18\x01 \x01(\v2,.familyledger.notify.v1.NotificationSettingsR\bsettings\"$\n" +
	"\"UpdateNotificationSettingsResponse\"K\n" +
	"\x18ListNotificationsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"\x88\x01\n" +
	"\x19ListNotificationsResponse\x12J\n" +
	"\rnotifications\x18\x01 \x03(\v2$.familyledger.notify.v1.NotificationR\rnotifications\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\">\n" +
	"\x11MarkAsReadRequest\x12)\n" +
	"\x10notification_ids\x18\x01 \x03(\tR\x0fnotificationIds\"\x14\n" +
	"\x12MarkAsReadResponse\"\xb5\x03\n" +
	"\bReminder\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tfamily_id\x18\x03 \x01(\tR\bfamilyId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x127\n" +
	"\tremind_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bremindAt\x12\x1f\n" +
	"\vrepeat_rule\x18\a \x01(\tR\n" +
	"repeatRule\x12>\n" +
	"\rrepeat_end_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vrepeatEndAt\x12\x1b\n" +
	"\tis_active\x18\t \x01(\bR\bisActive\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x86\x02\n" +
	"\x15CreateReminderRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x127\n" +
	"\tremind_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bremindAt\x12\x1f\n" +
	"\vrepeat_rule\x18\x04 \x01(\tR\n" +
	"repeatRule\x12>\n" +
	"\rrepeat_end_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vrepeatEndAt\x12\x1b\n" +
	"\tfamily_id\x18\x06 \x01(\tR\bfamilyId\"^\n" +
	"\x14ListRemindersRequest\x12\x1b\n" +
	"\tfamily_id\x18\x01 \x01(\tR\bfamilyId\x12)\n" +
	"\x10include_inactive\x18\x02 \x01(\bR\x0fincludeInactive\"W\n" +
	"\x15ListRemindersResponse\x12>\n" +
	"\treminders\x18\x01 \x03(\v2 .familyledger.notify.v1.ReminderR\treminders\"\xa7\x02\n" +
	"\x15UpdateReminderRequest\x12\x1f\n" +
	"\vreminder_id\x18\x01 \x01(\tR\n" +
	"reminderId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x127\n" +
	"\tremind_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bremindAt\x12\x1f\n" +
	"\vrepeat_rule\x18\x05 \x01(\tR\n" +
	"repeatRule\x12>\n" +
	"\rrepeat_end_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vrepeatEndAt\x12\x1b\n" +
	"\tis_active\x18\a \x01(\bR\bisActive\"8\n" +
	"\x15DeleteReminderRequest\x12\x1f\n" +
	"\vreminder_id\x18\x01 \x01(\tR\n" +
	"reminderId2\x86\t\n" +
	"\rNotifyService\x12o\n" +
	"\x0eRegisterDevice\x12-.familyledger.notify.v1.RegisterDeviceRequest\x1a..familyledger.notify.v1.RegisterDeviceResponse\x12u\n" +
	"\x10UnregisterDevice\x12/.familyledger.notify.v1.UnregisterDeviceRequest\x1a0.familyledger.notify.v1.UnregisterDeviceResponse\x12\x8a\x01\n" +
	"\x17GetNotificationSettings\x126.familyledger.notify.v1.GetNotificationSettingsRequest\x1a7.familyledger.notify.v1.GetNotificationSettingsResponse\x12\x93\x01\n" +
	"\x1aUpdateNotificationSettings\x129.familyledger.notify.v1.UpdateNotificationSettingsRequest\x1a:.familyledger.notify.v1.UpdateNotificationSettingsResponse\x12x\n" +
	"\x11ListNotifications\x120.familyledger.notify.v1.ListNotificationsRequest\x1a1.familyledger.notify.v1.ListNotificationsResponse\x12c\n" +
	"\n" +
	"MarkAsRead\x12).familyledger.notify.v1.MarkAsReadRequest\x1a*.familyledger.notify.v1.MarkAsReadResponse\x12a\n" +
	"\x0eCreateReminder\x12-.familyledger.notify.v1.CreateReminderRequest\x1a .familyledger.notify.v1.Reminder\x12l\n" +
	"\rListReminders\x12,.familyledger.notify.v1.ListRemindersRequest\x1a-.familyledger.notify.v1.ListRemindersResponse\x12a\n" +
	"\x0eUpdateReminder\x12-.familyledger.notify.v1.UpdateReminderRequest\x1a .familyledger.notify.v1.Reminder\x12W\n" +
	"\x0eDeleteReminder\x12-.familyledger.notify.v1.DeleteReminderRequest\x1a\x16.google.protobuf.EmptyB-Z+github.com/familyledger/server/proto/notifyb\x06proto3"

var (
	file_proto_notify_proto_rawDescOnce sync.Once
	file_proto_notify_proto_rawDescData []byte
)

func file_proto_notify_proto_rawDescGZIP() []byte {
	file_proto_notify_proto_rawDescOnce.Do(func() {
		file_proto_notify_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_notify_proto_rawDesc), len(file_proto_notify_proto_rawDesc)))
	})
	return file_proto_notify_proto_rawDescData
}

var file_proto_notify_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_proto_notify_proto_goTypes = []any{
	(*NotificationSettings)(nil),               // 0: familyledger.notify.v1.NotificationSettings
	(*Notification)(nil),                       // 1: familyledger.notify.v1.Notification
	(*RegisterDeviceRequest)(nil),              // 2: familyledger.notify.v1.RegisterDeviceRequest
	(*RegisterDeviceResponse)(nil),             // 3: familyledger.notify.v1.RegisterDeviceResponse
	(*UnregisterDeviceRequest)(nil),            // 4: familyledger.notify.v1.UnregisterDeviceRequest
	(*UnregisterDeviceResponse)(nil),           // 5: familyledger.notify.v1.UnregisterDeviceResponse
	(*GetNotificationSettingsRequest)(nil),     // 6: familyledger.notify.v1.GetNotificationSettingsRequest
	(*GetNotificationSettingsResponse)(nil),    // 7: familyledger.notify.v1.GetNotificationSettingsResponse
	(*UpdateNotificationSettingsRequest)(nil),  // 8: familyledger.notify.v1.UpdateNotificationSettingsRequest
	(*UpdateNotificationSettingsResponse)(nil), // 9: familyledger.notify.v1.UpdateNotificationSettingsResponse
	(*ListNotificationsRequest)(nil),           // 10: familyledger.notify.v1.ListNotificationsRequest
	(*ListNotificationsResponse)(nil),          // 11: familyledger.notify.v1.ListNotificationsResponse
	(*MarkAsReadRequest)(nil),                  // 12: familyledger.notify.v1.MarkAsReadRequest
	(*MarkAsReadResponse)(nil),                 // 13: familyledger.notify.v1.MarkAsReadResponse
	(*Reminder)(nil),                           // 14: familyledger.notify.v1.Reminder
	(*CreateReminderRequest)(nil),              // 15: familyledger.notify.v1.CreateReminderRequest
	(*ListRemindersRequest)(nil),               // 16: familyledger.notify.v1.ListRemindersRequest
	(*ListRemindersResponse)(nil),              // 17: familyledger.notify.v1.ListRemindersResponse
	(*UpdateReminderRequest)(nil),              // 18: familyledger.notify.v1.UpdateReminderRequest
	(*DeleteReminderRequest)(nil),              // 19: familyledger.notify.v1.DeleteReminderRequest
	(*timestamppb.Timestamp)(nil),              // 20: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                      // 21: google.protobuf.Empty
}
var file_proto_notify_proto_depIdxs = []int32{
	20, // 0: familyledger.notify.v1.Notification.created_at:type_name -> google.protobuf.Timestamp
	0,  // 1: familyledger.notify.v1.GetNotificationSettingsResponse.settings:type_name -> familyledger.notify.v1.NotificationSettings
	0,  // 2: familyledger.notify.v1.UpdateNotificationSettingsRequest.settings:type_name -> familyledger.notify.v1.NotificationSettings
	1,  // 3: familyledger.notify.v1.ListNotificationsResponse.notifications:type_name -> familyledger.notify.v1.Notification
	20, // 4: familyledger.notify.v1.Reminder.remind_at:type_name -> google.protobuf.Timestamp
	20, // 5: familyledger.notify.v1.Reminder.repeat_end_at:type_name -> google.protobuf.Timestamp
	20, // 6: familyledger.notify.v1.Reminder.created_at:type_name -> google.protobuf.Timestamp
	20, // 7: familyledger.notify.v1.Reminder.updated_at:type_name -> google.protobuf.Timestamp
	20, // 8: familyledger.notify.v1.CreateReminderRequest.remind_at:type_name -> google.protobuf.Timestamp
	20, // 9: familyledger.notify.v1.CreateReminderRequest.repeat_end_at:type_name -> google.protobuf.Timestamp
	14, // 10: familyledger.notify.v1.ListRemindersResponse.reminders:type_name -> familyledger.notify.v1.Reminder
	20, // 11: familyledger.notify.v1.UpdateReminderRequest.remind_at:type_name -> google.protobuf.Timestamp
	20, // 12: familyledger.notify.v1.UpdateReminderRequest.repeat_end_at:type_name -> google.protobuf.Timestamp
	2,  // 13: familyledger.notify.v1.NotifyService.RegisterDevice:input_type -> familyledger.notify.v1.RegisterDeviceRequest
	4,  // 14: familyledger.notify.v1.NotifyService.UnregisterDevice:input_type -> familyledger.notify.v1.UnregisterDeviceRequest
	6,  // 15: familyledger.notify.v1.NotifyService.GetNotificationSettings:input_type -> familyledger.notify.v1.GetNotificationSettingsRequest
	8,  // 16: familyledger.notify.v1.NotifyService.UpdateNotificationSettings:input_type -> familyledger.notify.v1.UpdateNotificationSettingsRequest
	10, // 17: familyledger.notify.v1.NotifyService.ListNotifications:input_type -> familyledger.notify.v1.ListNotificationsRequest
	12, // 18: familyledger.notify.v1.NotifyService.MarkAsRead:input_type -> familyledger.notify.v1.MarkAsReadRequest
	15, // 19: familyledger.notify.v1.NotifyService.CreateReminder:input_type -> familyledger.notify.v1.CreateReminderRequest
	16, // 20: familyledger.notify.v1.NotifyService.ListReminders:input_type -> familyledger.notify.v1.ListRemindersRequest
	18, // 21: familyledger.notify.v1.NotifyService.UpdateReminder:input_type -> familyledger.notify.v1.UpdateReminderRequest
	19, // 22: familyledger.notify.v1.NotifyService.DeleteReminder:input_type -> familyledger.notify.v1.DeleteReminderRequest
	3,  // 23: familyledger.notify.v1.NotifyService.RegisterDevice:output_type -> familyledger.notify.v1.RegisterDeviceResponse
	5,  // 24: familyledger.notify.v1.NotifyService.UnregisterDevice:output_type -> familyledger.notify.v1.UnregisterDeviceResponse
	7,  // 25: familyledger.notify.v1.NotifyService.GetNotificationSettings:output_type -> familyledger.notify.v1.GetNotificationSettingsResponse
	9,  // 26: familyledger.notify.v1.NotifyService.UpdateNotificationSettings:output_type -> familyledger.notify.v1.UpdateNotificationSettingsResponse
	11, // 27: familyledger.notify.v1.NotifyService.ListNotifications:output_type -> familyledger.notify.v1.ListNotificationsResponse
	13, // 28: familyledger.notify.v1.NotifyService.MarkAsRead:output_type -> familyledger.notify.v1.MarkAsReadResponse
	14, // 29: familyledger.notify.v1.NotifyService.CreateReminder:output_type -> familyledger.notify.v1.Reminder
	17, // 30: familyledger.notify.v1.NotifyService.ListReminders:output_type -> familyledger.notify.v1.ListRemindersResponse
	14, // 31: familyledger.notify.v1.NotifyService.UpdateReminder:output_type -> familyledger.notify.v1.Reminder
	21, // 32: familyledger.notify.v1.NotifyService.DeleteReminder:output_type -> google.protobuf.Empty
	23, // [23:33] is the sub-list for method output_type
	13, // [13:23] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proto_notify_proto_init() }
func file_proto_notify_proto_init() {
	if File_proto_notify_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_notify_proto_rawDesc), len(file_proto_notify_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_notify_proto_goTypes,
		DependencyIndexes: file_proto_notify_proto_depIdxs,
		MessageInfos:      file_proto_notify_proto_msgTypes,
	}.Build()
	File_proto_notify_proto = out.File
	file_proto_notify_proto_goTypes = nil
	file_proto_notify_proto_depIdxs = nil
}
