// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: family.proto

package family

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FamilyService_CreateFamily_FullMethodName         = "/familyledger.family.v1.FamilyService/CreateFamily"
	FamilyService_JoinFamily_FullMethodName           = "/familyledger.family.v1.FamilyService/JoinFamily"
	FamilyService_GetFamily_FullMethodName            = "/familyledger.family.v1.FamilyService/GetFamily"
	FamilyService_ListMyFamilies_FullMethodName       = "/familyledger.family.v1.FamilyService/ListMyFamilies"
	FamilyService_GenerateInviteCode_FullMethodName   = "/familyledger.family.v1.FamilyService/GenerateInviteCode"
	FamilyService_SetMemberRole_FullMethodName        = "/familyledger.family.v1.FamilyService/SetMemberRole"
	FamilyService_SetMemberPermissions_FullMethodName = "/familyledger.family.v1.FamilyService/SetMemberPermissions"
	FamilyService_ListFamilyMembers_FullMethodName    = "/familyledger.family.v1.FamilyService/ListFamilyMembers"
	FamilyService_LeaveFamily_FullMethodName          = "/familyledger.family.v1.FamilyService/LeaveFamily"
	FamilyService_TransferOwnership_FullMethodName    = "/familyledger.family.v1.FamilyService/TransferOwnership"
	FamilyService_DeleteFamily_FullMethodName         = "/familyledger.family.v1.FamilyService/DeleteFamily"
	FamilyService_GetAuditLog_FullMethodName          = "/familyledger.family.v1.FamilyService/GetAuditLog"
)

// FamilyServiceClient is the client API for FamilyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FamilyServiceClient interface {
	CreateFamily(ctx context.Context, in *CreateFamilyRequest, opts ...grpc.CallOption) (*CreateFamilyResponse, error)
	JoinFamily(ctx context.Context, in *JoinFamilyRequest, opts ...grpc.CallOption) (*JoinFamilyResponse, error)
	GetFamily(ctx context.Context, in *GetFamilyRequest, opts ...grpc.CallOption) (*GetFamilyResponse, error)
	ListMyFamilies(ctx context.Context, in *ListMyFamiliesRequest, opts ...grpc.CallOption) (*ListMyFamiliesResponse, error)
	GenerateInviteCode(ctx context.Context, in *GenerateInviteCodeRequest, opts ...grpc.CallOption) (*GenerateInviteCodeResponse, error)
	SetMemberRole(ctx context.Context, in *SetMemberRoleRequest, opts ...grpc.CallOption) (*SetMemberRoleResponse, error)
	SetMemberPermissions(ctx context.Context, in *SetMemberPermissionsRequest, opts ...grpc.CallOption) (*SetMemberPermissionsResponse, error)
	ListFamilyMembers(ctx context.Context, in *ListFamilyMembersRequest, opts ...grpc.CallOption) (*ListFamilyMembersResponse, error)
	LeaveFamily(ctx context.Context, in *LeaveFamilyRequest, opts ...grpc.CallOption) (*LeaveFamilyResponse, error)
	TransferOwnership(ctx context.Context, in *TransferOwnershipRequest, opts ...grpc.CallOption) (*TransferOwnershipResponse, error)
	DeleteFamily(ctx context.Context, in *DeleteFamilyRequest, opts ...grpc.CallOption) (*DeleteFamilyResponse, error)
	GetAuditLog(ctx context.Context, in *GetAuditLogRequest, opts ...grpc.CallOption) (*GetAuditLogResponse, error)
}

type familyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFamilyServiceClient(cc grpc.ClientConnInterface) FamilyServiceClient {
	return &familyServiceClient{cc}
}

func (c *familyServiceClient) CreateFamily(ctx context.Context, in *CreateFamilyRequest, opts ...grpc.CallOption) (*CreateFamilyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateFamilyResponse)
	err := c.cc.Invoke(ctx, FamilyService_CreateFamily_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *familyServiceClient) JoinFamily(ctx context.Context, in *JoinFamilyRequest, opts ...grpc.CallOption) (*JoinFamilyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinFamilyResponse)
	err := c.cc.Invoke(ctx, FamilyService_JoinFamily_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *familyServiceClient) GetFamily(ctx context.Context, in *GetFamilyRequest, opts ...grpc.CallOption) (*GetFamilyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFamilyResponse)
	err := c.cc.Invoke(ctx, FamilyService_GetFamily_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *familyServiceClient) ListMyFamilies(ctx context.Context, in *ListMyFamiliesRequest, opts ...grpc.CallOption) (*ListMyFamiliesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMyFamiliesResponse)
	err := c.cc.Invoke(ctx, FamilyService_ListMyFamilies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *familyServiceClient) GenerateInviteCode(ctx context.Context, in *GenerateInviteCodeRequest, opts ...grpc.CallOption) (*GenerateInviteCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateInviteCodeResponse)
	err := c.cc.Invoke(ctx, FamilyService_GenerateInviteCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *familyServiceClient) SetMemberRole(ctx context.Context, in *SetMemberRoleRequest, opts ...grpc.CallOption) (*SetMemberRoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetMemberRoleResponse)
	err := c.cc.Invoke(ctx, FamilyService_SetMemberRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *familyServiceClient) SetMemberPermissions(ctx context.Context, in *SetMemberPermissionsRequest, opts ...grpc.CallOption) (*SetMemberPermissionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetMemberPermissionsResponse)
	err := c.cc.Invoke(ctx, FamilyService_SetMemberPermissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *familyServiceClient) ListFamilyMembers(ctx context.Context, in *ListFamilyMembersRequest, opts ...grpc.CallOption) (*ListFamilyMembersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFamilyMembersResponse)
	err := c.cc.Invoke(ctx, FamilyService_ListFamilyMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *familyServiceClient) LeaveFamily(ctx context.Context, in *LeaveFamilyRequest, opts ...grpc.CallOption) (*LeaveFamilyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeaveFamilyResponse)
	err := c.cc.Invoke(ctx, FamilyService_LeaveFamily_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *familyServiceClient) TransferOwnership(ctx context.Context, in *TransferOwnershipRequest, opts ...grpc.CallOption) (*TransferOwnershipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferOwnershipResponse)
	err := c.cc.Invoke(ctx, FamilyService_TransferOwnership_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *familyServiceClient) DeleteFamily(ctx context.Context, in *DeleteFamilyRequest, opts ...grpc.CallOption) (*DeleteFamilyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFamilyResponse)
	err := c.cc.Invoke(ctx, FamilyService_DeleteFamily_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *familyServiceClient) GetAuditLog(ctx context.Context, in *GetAuditLogRequest, opts ...grpc.CallOption) (*GetAuditLogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAuditLogResponse)
	err := c.cc.Invoke(ctx, FamilyService_GetAuditLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FamilyServiceServer is the server API for FamilyService service.
// All implementations must embed UnimplementedFamilyServiceServer
// for forward compatibility.
type FamilyServiceServer interface {
	CreateFamily(context.Context, *CreateFamilyRequest) (*CreateFamilyResponse, error)
	JoinFamily(context.Context, *JoinFamilyRequest) (*JoinFamilyResponse, error)
	GetFamily(context.Context, *GetFamilyRequest) (*GetFamilyResponse, error)
	ListMyFamilies(context.Context, *ListMyFamiliesRequest) (*ListMyFamiliesResponse, error)
	GenerateInviteCode(context.Context, *GenerateInviteCodeRequest) (*GenerateInviteCodeResponse, error)
	SetMemberRole(context.Context, *SetMemberRoleRequest) (*SetMemberRoleResponse, error)
	SetMemberPermissions(context.Context, *SetMemberPermissionsRequest) (*SetMemberPermissionsResponse, error)
	ListFamilyMembers(context.Context, *ListFamilyMembersRequest) (*ListFamilyMembersResponse, error)
	LeaveFamily(context.Context, *LeaveFamilyRequest) (*LeaveFamilyResponse, error)
	TransferOwnership(context.Context, *TransferOwnershipRequest) (*TransferOwnershipResponse, error)
	DeleteFamily(context.Context, *DeleteFamilyRequest) (*DeleteFamilyResponse, error)
	GetAuditLog(context.Context, *GetAuditLogRequest) (*GetAuditLogResponse, error)
	mustEmbedUnimplementedFamilyServiceServer()
}

// UnimplementedFamilyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFamilyServiceServer struct{}

func (UnimplementedFamilyServiceServer) CreateFamily(context.Context, *CreateFamilyRequest) (*CreateFamilyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateFamily not implemented")
}
func (UnimplementedFamilyServiceServer) JoinFamily(context.Context, *JoinFamilyRequest) (*JoinFamilyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method JoinFamily not implemented")
}
func (UnimplementedFamilyServiceServer) GetFamily(context.Context, *GetFamilyRequest) (*GetFamilyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFamily not implemented")
}
func (UnimplementedFamilyServiceServer) ListMyFamilies(context.Context, *ListMyFamiliesRequest) (*ListMyFamiliesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMyFamilies not implemented")
}
func (UnimplementedFamilyServiceServer) GenerateInviteCode(context.Context, *GenerateInviteCodeRequest) (*GenerateInviteCodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateInviteCode not implemented")
}
func (UnimplementedFamilyServiceServer) SetMemberRole(context.Context, *SetMemberRoleRequest) (*SetMemberRoleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetMemberRole not implemented")
}
func (UnimplementedFamilyServiceServer) SetMemberPermissions(context.Context, *SetMemberPermissionsRequest) (*SetMemberPermissionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetMemberPermissions not implemented")
}
func (UnimplementedFamilyServiceServer) ListFamilyMembers(context.Context, *ListFamilyMembersRequest) (*ListFamilyMembersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFamilyMembers not implemented")
}
func (UnimplementedFamilyServiceServer) LeaveFamily(context.Context, *LeaveFamilyRequest) (*LeaveFamilyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LeaveFamily not implemented")
}
func (UnimplementedFamilyServiceServer) TransferOwnership(context.Context, *TransferOwnershipRequest) (*TransferOwnershipResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TransferOwnership not implemented")
}
func (UnimplementedFamilyServiceServer) DeleteFamily(context.Context, *DeleteFamilyRequest) (*DeleteFamilyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFamily not implemented")
}
func (UnimplementedFamilyServiceServer) GetAuditLog(context.Context, *GetAuditLogRequest) (*GetAuditLogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAuditLog not implemented")
}
func (UnimplementedFamilyServiceServer) mustEmbedUnimplementedFamilyServiceServer() {}
func (UnimplementedFamilyServiceServer) testEmbeddedByValue()                       {}

// UnsafeFamilyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FamilyServiceServer will
// result in compilation errors.
type UnsafeFamilyServiceServer interface {
	mustEmbedUnimplementedFamilyServiceServer()
}

func RegisterFamilyServiceServer(s grpc.ServiceRegistrar, srv FamilyServiceServer) {
	// If the following call panics, it indicates UnimplementedFamilyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FamilyService_ServiceDesc, srv)
}

func _FamilyService_CreateFamily_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFamilyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FamilyServiceServer).CreateFamily(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FamilyService_CreateFamily_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FamilyServiceServer).CreateFamily(ctx, req.(*CreateFamilyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FamilyService_JoinFamily_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinFamilyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FamilyServiceServer).JoinFamily(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FamilyService_JoinFamily_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FamilyServiceServer).JoinFamily(ctx, req.(*JoinFamilyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FamilyService_GetFamily_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFamilyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FamilyServiceServer).GetFamily(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FamilyService_GetFamily_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FamilyServiceServer).GetFamily(ctx, req.(*GetFamilyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FamilyService_ListMyFamilies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMyFamiliesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FamilyServiceServer).ListMyFamilies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FamilyService_ListMyFamilies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FamilyServiceServer).ListMyFamilies(ctx, req.(*ListMyFamiliesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FamilyService_GenerateInviteCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateInviteCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FamilyServiceServer).GenerateInviteCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FamilyService_GenerateInviteCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FamilyServiceServer).GenerateInviteCode(ctx, req.(*GenerateInviteCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FamilyService_SetMemberRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetMemberRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FamilyServiceServer).SetMemberRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FamilyService_SetMemberRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FamilyServiceServer).SetMemberRole(ctx, req.(*SetMemberRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FamilyService_SetMemberPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetMemberPermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FamilyServiceServer).SetMemberPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FamilyService_SetMemberPermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FamilyServiceServer).SetMemberPermissions(ctx, req.(*SetMemberPermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FamilyService_ListFamilyMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFamilyMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FamilyServiceServer).ListFamilyMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FamilyService_ListFamilyMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FamilyServiceServer).ListFamilyMembers(ctx, req.(*ListFamilyMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FamilyService_LeaveFamily_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaveFamilyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FamilyServiceServer).LeaveFamily(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FamilyService_LeaveFamily_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FamilyServiceServer).LeaveFamily(ctx, req.(*LeaveFamilyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FamilyService_TransferOwnership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferOwnershipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FamilyServiceServer).TransferOwnership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FamilyService_TransferOwnership_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FamilyServiceServer).TransferOwnership(ctx, req.(*TransferOwnershipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FamilyService_DeleteFamily_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFamilyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FamilyServiceServer).DeleteFamily(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FamilyService_DeleteFamily_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FamilyServiceServer).DeleteFamily(ctx, req.(*DeleteFamilyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FamilyService_GetAuditLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAuditLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FamilyServiceServer).GetAuditLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FamilyService_GetAuditLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FamilyServiceServer).GetAuditLog(ctx, req.(*GetAuditLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FamilyService_ServiceDesc is the grpc.ServiceDesc for FamilyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FamilyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "familyledger.family.v1.FamilyService",
	HandlerType: (*FamilyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateFamily",
			Handler:    _FamilyService_CreateFamily_Handler,
		},
		{
			MethodName: "JoinFamily",
			Handler:    _FamilyService_JoinFamily_Handler,
		},
		{
			MethodName: "GetFamily",
			Handler:    _FamilyService_GetFamily_Handler,
		},
		{
			MethodName: "ListMyFamilies",
			Handler:    _FamilyService_ListMyFamilies_Handler,
		},
		{
			MethodName: "GenerateInviteCode",
			Handler:    _FamilyService_GenerateInviteCode_Handler,
		},
		{
			MethodName: "SetMemberRole",
			Handler:    _FamilyService_SetMemberRole_Handler,
		},
		{
			MethodName: "SetMemberPermissions",
			Handler:    _FamilyService_SetMemberPermissions_Handler,
		},
		{
			MethodName: "ListFamilyMembers",
			Handler:    _FamilyService_ListFamilyMembers_Handler,
		},
		{
			MethodName: "LeaveFamily",
			Handler:    _FamilyService_LeaveFamily_Handler,
		},
		{
			MethodName: "TransferOwnership",
			Handler:    _FamilyService_TransferOwnership_Handler,
		},
		{
			MethodName: "DeleteFamily",
			Handler:    _FamilyService_DeleteFamily_Handler,
		},
		{
			MethodName: "GetAuditLog",
			Handler:    _FamilyService_GetAuditLog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "family.proto",
}
