// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: family.proto

package family

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FamilyRole int32

const (
	FamilyRole_FAMILY_ROLE_UNSPECIFIED FamilyRole = 0
	FamilyRole_FAMILY_ROLE_OWNER       FamilyRole = 1
	FamilyRole_FAMILY_ROLE_ADMIN       FamilyRole = 2
	FamilyRole_FAMILY_ROLE_MEMBER      FamilyRole = 3
)

// Enum value maps for FamilyRole.
var (
	FamilyRole_name = map[int32]string{
		0: "FAMILY_ROLE_UNSPECIFIED",
		1: "FAMILY_ROLE_OWNER",
		2: "FAMILY_ROLE_ADMIN",
		3: "FAMILY_ROLE_MEMBER",
	}
	FamilyRole_value = map[string]int32{
		"FAMILY_ROLE_UNSPECIFIED": 0,
		"FAMILY_ROLE_OWNER":       1,
		"FAMILY_ROLE_ADMIN":       2,
		"FAMILY_ROLE_MEMBER":      3,
	}
)

func (x FamilyRole) Enum() *FamilyRole {
	p := new(FamilyRole)
	*p = x
	return p
}

func (x FamilyRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FamilyRole) Descriptor() protoreflect.EnumDescriptor {
	return file_family_proto_enumTypes[0].Descriptor()
}

func (FamilyRole) Type() protoreflect.EnumType {
	return &file_family_proto_enumTypes[0]
}

func (x FamilyRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FamilyRole.Descriptor instead.
func (FamilyRole) EnumDescriptor() ([]byte, []int) {
	return file_family_proto_rawDescGZIP(), []int{0}
}

type MemberPermissions struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CanView           bool                   `protobuf:"varint,1,opt,name=can_view,json=canView,proto3" json:"can_view,omitempty"`
	CanCreate         bool                   `protobuf:"varint,2,opt,name=can_create,json=canCreate,proto3" json:"can_create,omitempty"`
	CanEdit           bool                   `protobuf:"varint,3,opt,name=can_edit,json=canEdit,proto3" json:"can_edit,omitempty"`
	CanDelete         bool                   `protobuf:"varint,4,opt,name=can_delete,json=canDelete,proto3" json:"can_delete,omitempty"`
	CanManageAccounts bool                   `protobuf:"varint,5,opt,name=can_manage_accounts,json=canManageAccounts,proto3" json:"can_manage_accounts,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MemberPermissions) Reset() {
	*x = MemberPermissions{}
	mi := &file_family_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberPermissions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberPermissions) ProtoMessage() {}

func (x *MemberPermissions) ProtoReflect() protoreflect.Message {
	mi := &file_family_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberPermissions.ProtoReflect.Descriptor instead.
func (*MemberPermissions) Descriptor() ([]byte, []int) {
	return file_family_proto_rawDescGZIP(), []int{0}
}

func (x *MemberPermissions) GetCanView() bool {
	if x != nil {
		return x.CanView
	}
	return false
}

func (x *MemberPermissions) GetCanCreate() bool {
	if x != nil {
		return x.CanCreate
	}
	return false
}

func (x *MemberPermissions) GetCanEdit() bool {
	if x != nil {
		return x.CanEdit
	}
	return false
}

func (x *MemberPermissions) GetCanDelete() bool {
	if x != nil {
		return x.CanDelete
	}
	return false
}

func (x *MemberPermissions) GetCanManageAccounts() bool {
	if x != nil {
		return x.CanManageAccounts
	}
	return false
}

type Family struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OwnerId         string                 `protobuf:"bytes,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	InviteCode      string                 `protobuf:"bytes,4,opt,name=invite_code,json=inviteCode,proto3" json:"invite_code,omitempty"`
	InviteExpiresAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=invite_expires_at,json=inviteExpiresAt,proto3" json:"invite_expires_at,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Family) Reset() {
	*x = Family{}
	mi := &file_family_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Family) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Family) ProtoMessage() {}

func (x *Family) ProtoReflect() protoreflect.Message {
	mi := &file_family_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Family.ProtoReflect.Descriptor instead.
func (*Family) Descriptor() ([]byte, []int) {
	return file_family_proto_rawDescGZIP(), []int{1}
}

func (x *Family) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Family) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Family) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Family) GetInviteCode() string {
	if x != nil {
		return x.InviteCode
	}
	return ""
}

func (x *Family) GetInviteExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.InviteExpiresAt
	}
	return nil
}

func (x *Family) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Family) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type FamilyMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Role          FamilyRole             `protobuf:"varint,4,opt,name=role,proto3,enum=familyledger.family.v1.FamilyRole" json:"role,omitempty"`
	Permissions   *MemberPermissions     `protobuf:"bytes,5,opt,name=permissions,proto3" json:"permissions,omitempty"`
	JoinedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FamilyMember) Reset() {
	*x = FamilyMember{}
	mi := &file_family_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FamilyMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FamilyMember) ProtoMessage() {}

func (x *FamilyMember) ProtoReflect() protoreflect.Message {
	mi := &file_family_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FamilyMember.ProtoReflect.Descriptor instead.
func (*FamilyMember) Descriptor() ([]byte, []int) {
	return file_family_proto_rawDescGZIP(), []int{2}
}

func (x *FamilyMember) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FamilyMember) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FamilyMember) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *FamilyMember) GetRole() FamilyRole {
	if x != nil {
		return x.Role
	}
	return FamilyRole_FAMILY_ROLE_UNSPECIFIED
}

func (x *FamilyMember) GetPermissions() *MemberPermissions {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *FamilyMember) GetJoinedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.JoinedAt
	}
	return nil
}

// CreateFamily
type CreateFamilyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFamilyRequest) Reset() {
	*x = CreateFamilyRequest{}
	mi := &file_family_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFamilyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFamilyRequest) ProtoMessage() {}

func (x *CreateFamilyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_family_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFamilyRequest.ProtoReflect.Descriptor instead.
func (*CreateFamilyRequest) Descriptor() ([]byte, []int) {
	return file_family_proto_rawDescGZIP(), []int{3}
}

func (x *CreateFamilyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateFamilyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Family        *Family                `protobuf:"bytes,1,opt,name=family,proto3" json:"family,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFamilyResponse) Reset() {
	*x = CreateFamilyResponse{}
	mi := &file_family_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFamilyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFamilyResponse) ProtoMessage() {}

func (x *CreateFamilyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_family_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFamilyResponse.ProtoReflect.Descriptor instead.
func (*CreateFamilyResponse) Descriptor() ([]byte, []int) {
	return file_family_proto_rawDescGZIP(), []int{4}
}

func (x *CreateFamilyResponse) GetFamily() *Family {
	if x != nil {
		return x.Family
	}
	return nil
}

// JoinFamily
type JoinFamilyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InviteCode    string                 `protobuf:"bytes,1,opt,name=invite_code,json=inviteCode,proto3" json:"invite_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinFamilyRequest) Reset() {
	*x = JoinFamilyRequest{}
	mi := &file_family_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinFamilyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinFamilyRequest) ProtoMessage() {}

func (x *JoinFamilyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_family_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinFamilyRequest.ProtoReflect.Descriptor instead.
func (*JoinFamilyRequest) Descriptor() ([]byte, []int) {
	return file_family_proto_rawDescGZIP(), []int{5}
}

func (x *JoinFamilyRequest) GetInviteCode() string {
	if x != nil {
		return x.InviteCode
	}
	return ""
}

type JoinFamilyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Family        *Family                `protobuf:"bytes,1,opt,name=family,proto3" json:"family,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinFamilyResponse) Reset() {
	*x = JoinFamilyResponse{}
	mi := &file_family_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinFamilyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinFamilyResponse) ProtoMessage() {}

func (x *JoinFamilyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_family_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinFamilyResponse.ProtoReflect.Descriptor instead.
func (*JoinFamilyResponse) Descriptor() ([]byte, []int) {
	return file_family_proto_rawDescGZIP(), []int{6}
}

func (x *JoinFamilyResponse) GetFamily() *Family {
	if x != nil {
		return x.Family
	}
	return nil
}

// GetFamily
type GetFamilyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FamilyId      string                 `protobuf:"bytes,1,opt,name=family_id,json=familyId,proto3" json:"family_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFamilyRequest) Reset() {
	*x = GetFamilyRequest{}
	mi := &file_family_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFamilyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFamilyRequest) ProtoMessage() {}

func (x *GetFamilyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_family_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFamilyRequest.ProtoReflect.Descriptor instead.
func (*GetFamilyRequest) Descriptor() ([]byte, []int) {
	return file_family_proto_rawDescGZIP(), []int{7}
}

func (x *GetFamilyRequest) GetFamilyId() string {
	if x != nil {
		return x.FamilyId
	}
	return ""
}

type GetFamilyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Family        *Family                `protobuf:"bytes,1,opt,name=family,proto3" json:"family,omitempty"`
	Members       []*FamilyMember        `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFamilyResponse) Reset() {
	*x = GetFamilyResponse{}
	mi := &file_family_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFamilyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFamilyResponse) ProtoMessage() {}

func (x *GetFamilyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_family_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFamilyResponse.ProtoReflect.Descriptor instead.
func (*GetFamilyResponse) Descriptor() ([]byte, []int) {
	return file_family_proto_rawDescGZIP(), []int{8}
}

func (x *GetFamilyResponse) GetFamily() *Family {
	if x != nil {
		return x.Family
	}
	return nil
}

func (x *GetFamilyResponse) GetMembers() []*FamilyMember {
	if x != nil {
		return x.Members
	}
	return nil
}

// GenerateInviteCode
type GenerateInviteCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FamilyId      string                 `protobuf:"bytes,1,opt,name=family_id,json=familyId,proto3" json:"family_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateInviteCodeRequest) Reset() {
	*x = GenerateInviteCodeRequest{}
	mi := &file_family_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateInviteCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateInviteCodeRequest) ProtoMessage() {}

func (x *GenerateInviteCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_family_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateInviteCodeRequest.ProtoReflect.Descriptor instead.
func (*GenerateInviteCodeRequest) Descriptor() ([]byte, []int) {
	return file_family_proto_rawDescGZIP(), []int{9}
}

func (x *GenerateInviteCodeRequest) GetFamilyId() string {
	if x != nil {
		return x.FamilyId
	}
	return ""
}

type GenerateInviteCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InviteCode    string                 `protobuf:"bytes,1,opt,name=invite_code,json=inviteCode,proto3" json:"invite_code,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateInviteCodeResponse) Reset() {
	*x = GenerateInviteCodeResponse{}
	mi := &file_family_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateInviteCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateInviteCodeResponse) ProtoMessage() {}

func (x *GenerateInviteCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_family_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateInviteCodeResponse.ProtoReflect.Descriptor instead.
func (*GenerateInviteCodeResponse) Descriptor() ([]byte, []int) {
	return file_family_proto_rawDescGZIP(), []int{10}
}

func (x *GenerateInviteCodeResponse) GetInviteCode() string {
	if x != nil {
		return x.InviteCode
	}
	return ""
}

func (x *GenerateInviteCodeResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

// SetMemberRole
type SetMemberRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FamilyId      string                 `protobuf:"bytes,1,opt,name=family_id,json=familyId,proto3" json:"family_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          FamilyRole             `protobuf:"varint,3,opt,name=role,proto3,enum=familyledger.family.v1.FamilyRole" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetMemberRoleRequest) Reset() {
	*x = SetMemberRoleRequest{}
	mi := &file_family_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetMemberRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMemberRoleRequest) ProtoMessage() {}

func (x *SetMemberRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_family_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetMemberRoleRequest.ProtoReflect.Descriptor instead.
func (*SetMemberRoleRequest) Descriptor() ([]byte, []int) {
	return file_family_proto_rawDescGZIP(), []int{11}
}

func (x *SetMemberRoleRequest) GetFamilyId() string {
	if x != nil {
		return x.FamilyId
	}
	return ""
}

func (x *SetMemberRoleRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SetMemberRoleRequest) GetRole() FamilyRole {
	if x != nil {
		return x.Role
	}
	return FamilyRole_FAMILY_ROLE_UNSPECIFIED
}

type SetMemberRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetMemberRoleResponse) Reset() {
	*x = SetMemberRoleResponse{}
	mi := &file_family_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetMemberRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMemberRoleResponse) ProtoMessage() {}

func (x *SetMemberRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_family_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetMemberRoleResponse.ProtoReflect.Descriptor instead.
func (*SetMemberRoleResponse) Descriptor() ([]byte, []int) {
	return file_family_proto_rawDescGZIP(), []int{12}
}

// SetMemberPermissions
type SetMemberPermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FamilyId      string                 `protobuf:"bytes,1,opt,name=family_id,json=familyId,proto3" json:"family_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Permissions   *MemberPermissions     `protobuf:"bytes,3,opt,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetMemberPermissionsRequest) Reset() {
	*x = SetMemberPermissionsRequest{}
	mi := &file_family_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetMemberPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMemberPermissionsRequest) ProtoMessage() {}

func (x *SetMemberPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_family_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetMemberPermissionsRequest.ProtoReflect.Descriptor instead.
func (*SetMemberPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_family_proto_rawDescGZIP(), []int{13}
}

func (x *SetMemberPermissionsRequest) GetFamilyId() string {
	if x != nil {
		return x.FamilyId
	}
	return ""
}

func (x *SetMemberPermissionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SetMemberPermissionsRequest) GetPermissions() *MemberPermissions {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type SetMemberPermissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetMemberPermissionsResponse) Reset() {
	*x = SetMemberPermissionsResponse{}
	mi := &file_family_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetMemberPermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMemberPermissionsResponse) ProtoMessage() {}

func (x *SetMemberPermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_family_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetMemberPermissionsResponse.ProtoReflect.Descriptor instead.
func (*SetMemberPermissionsResponse) Descriptor() ([]byte, []int) {
	return file_family_proto_rawDescGZIP(), []int{14}
}

// ListFamilyMembers
type ListFamilyMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FamilyId      string                 `protobuf:"bytes,1,opt,name=family_id,json=familyId,proto3" json:"family_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFamilyMembersRequest) Reset() {
	*x = ListFamilyMembersRequest{}
	mi := &file_family_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFamilyMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFamilyMembersRequest) ProtoMessage() {}

func (x *ListFamilyMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_family_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFamilyMembersRequest.ProtoReflect.Descriptor instead.
func (*ListFamilyMembersRequest) Descriptor() ([]byte, []int) {
	return file_family_proto_rawDescGZIP(), []int{15}
}

func (x *ListFamilyMembersRequest) GetFamilyId() string {
	if x != nil {
		return x.FamilyId
	}
	return ""
}

type ListFamilyMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*FamilyMember        `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFamilyMembersResponse) Reset() {
	*x = ListFamilyMembersResponse{}
	mi := &file_family_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFamilyMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFamilyMembersResponse) ProtoMessage() {}

func (x *ListFamilyMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_family_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFamilyMembersResponse.ProtoReflect.Descriptor instead.
func (*ListFamilyMembersResponse) Descriptor() ([]byte, []int) {
	return file_family_proto_rawDescGZIP(), []int{16}
}

func (x *ListFamilyMembersResponse) GetMembers() []*FamilyMember {
	if x != nil {
		return x.Members
	}
	return nil
}

// LeaveFamily
type LeaveFamilyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FamilyId      string                 `protobuf:"bytes,1,opt,name=family_id,json=familyId,proto3" json:"family_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveFamilyRequest) Reset() {
	*x = LeaveFamilyRequest{}
	mi := &file_family_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveFamilyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveFamilyRequest) ProtoMessage() {}

func (x *LeaveFamilyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_family_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveFamilyRequest.ProtoReflect.Descriptor instead.
func (*LeaveFamilyRequest) Descriptor() ([]byte, []int) {
	return file_family_proto_rawDescGZIP(), []int{17}
}

func (x *LeaveFamilyRequest) GetFamilyId() string {
	if x != nil {
		return x.FamilyId
	}
	return ""
}

type LeaveFamilyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveFamilyResponse) Reset() {
	*x = LeaveFamilyResponse{}
	mi := &file_family_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveFamilyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveFamilyResponse) ProtoMessage() {}

func (x *LeaveFamilyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_family_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveFamilyResponse.ProtoReflect.Descriptor instead.
func (*LeaveFamilyResponse) Descriptor() ([]byte, []int) {
	return file_family_proto_rawDescGZIP(), []int{18}
}

// TransferOwnership
type TransferOwnershipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FamilyId      string                 `protobuf:"bytes,1,opt,name=family_id,json=familyId,proto3" json:"family_id,omitempty"`
	NewOwnerId    string                 `protobuf:"bytes,2,opt,name=new_owner_id,json=newOwnerId,proto3" json:"new_owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferOwnershipRequest) Reset() {
	*x = TransferOwnershipRequest{}
	mi := &file_family_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferOwnershipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferOwnershipRequest) ProtoMessage() {}

func (x *TransferOwnershipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_family_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferOwnershipRequest.ProtoReflect.Descriptor instead.
func (*TransferOwnershipRequest) Descriptor() ([]byte, []int) {
	return file_family_proto_rawDescGZIP(), []int{19}
}

func (x *TransferOwnershipRequest) GetFamilyId() string {
	if x != nil {
		return x.FamilyId
	}
	return ""
}

func (x *TransferOwnershipRequest) GetNewOwnerId() string {
	if x != nil {
		return x.NewOwnerId
	}
	return ""
}

type TransferOwnershipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferOwnershipResponse) Reset() {
	*x = TransferOwnershipResponse{}
	mi := &file_family_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferOwnershipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferOwnershipResponse) ProtoMessage() {}

func (x *TransferOwnershipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_family_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferOwnershipResponse.ProtoReflect.Descriptor instead.
func (*TransferOwnershipResponse) Descriptor() ([]byte, []int) {
	return file_family_proto_rawDescGZIP(), []int{20}
}

// DeleteFamily
type DeleteFamilyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FamilyId      string                 `protobuf:"bytes,1,opt,name=family_id,json=familyId,proto3" json:"family_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFamilyRequest) Reset() {
	*x = DeleteFamilyRequest{}
	mi := &file_family_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFamilyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFamilyRequest) ProtoMessage() {}

func (x *DeleteFamilyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_family_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFamilyRequest.ProtoReflect.Descriptor instead.
func (*DeleteFamilyRequest) Descriptor() ([]byte, []int) {
	return file_family_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteFamilyRequest) GetFamilyId() string {
	if x != nil {
		return x.FamilyId
	}
	return ""
}

type DeleteFamilyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFamilyResponse) Reset() {
	*x = DeleteFamilyResponse{}
	mi := &file_family_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFamilyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFamilyResponse) ProtoMessage() {}

func (x *DeleteFamilyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_family_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFamilyResponse.ProtoReflect.Descriptor instead.
func (*DeleteFamilyResponse) Descriptor() ([]byte, []int) {
	return file_family_proto_rawDescGZIP(), []int{22}
}

// GetAuditLog
type GetAuditLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FamilyId      string                 `protobuf:"bytes,1,opt,name=family_id,json=familyId,proto3" json:"family_id,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	EntityType    string                 `protobuf:"bytes,4,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"` // optional filter: 'transaction', 'account', 'loan', etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuditLogRequest) Reset() {
	*x = GetAuditLogRequest{}
	mi := &file_family_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuditLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuditLogRequest) ProtoMessage() {}

func (x *GetAuditLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_family_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuditLogRequest.ProtoReflect.Descriptor instead.
func (*GetAuditLogRequest) Descriptor() ([]byte, []int) {
	return file_family_proto_rawDescGZIP(), []int{23}
}

func (x *GetAuditLogRequest) GetFamilyId() string {
	if x != nil {
		return x.FamilyId
	}
	return ""
}

func (x *GetAuditLogRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetAuditLogRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *GetAuditLogRequest) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

type GetAuditLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*AuditEntry          `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuditLogResponse) Reset() {
	*x = GetAuditLogResponse{}
	mi := &file_family_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuditLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuditLogResponse) ProtoMessage() {}

func (x *GetAuditLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_family_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuditLogResponse.ProtoReflect.Descriptor instead.
func (*GetAuditLogResponse) Descriptor() ([]byte, []int) {
	return file_family_proto_rawDescGZIP(), []int{24}
}

func (x *GetAuditLogResponse) GetEntries() []*AuditEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *GetAuditLogResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type AuditEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName      string                 `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Action        string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"` // 'create', 'update', 'delete'
	EntityType    string                 `protobuf:"bytes,5,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	EntityId      string                 `protobuf:"bytes,6,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	ChangesJson   string                 `protobuf:"bytes,7,opt,name=changes_json,json=changesJson,proto3" json:"changes_json,omitempty"` // JSON: {"field": {"old": x, "new": y}}
	CreatedAt     int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`      // Unix timestamp (seconds)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditEntry) Reset() {
	*x = AuditEntry{}
	mi := &file_family_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditEntry) ProtoMessage() {}

func (x *AuditEntry) ProtoReflect() protoreflect.Message {
	mi := &file_family_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditEntry.ProtoReflect.Descriptor instead.
func (*AuditEntry) Descriptor() ([]byte, []int) {
	return file_family_proto_rawDescGZIP(), []int{25}
}

func (x *AuditEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuditEntry) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AuditEntry) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *AuditEntry) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuditEntry) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *AuditEntry) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *AuditEntry) GetChangesJson() string {
	if x != nil {
		return x.ChangesJson
	}
	return ""
}

func (x *AuditEntry) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// ListMyFamilies — returns all families the current user belongs to
type ListMyFamiliesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyFamiliesRequest) Reset() {
	*x = ListMyFamiliesRequest{}
	mi := &file_family_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyFamiliesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyFamiliesRequest) ProtoMessage() {}

func (x *ListMyFamiliesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_family_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyFamiliesRequest.ProtoReflect.Descriptor instead.
func (*ListMyFamiliesRequest) Descriptor() ([]byte, []int) {
	return file_family_proto_rawDescGZIP(), []int{26}
}

type ListMyFamiliesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Families      []*Family              `protobuf:"bytes,1,rep,name=families,proto3" json:"families,omitempty"`
	Memberships   []*FamilyMember        `protobuf:"bytes,2,rep,name=memberships,proto3" json:"memberships,omitempty"` // user's membership info for each family
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyFamiliesResponse) Reset() {
	*x = ListMyFamiliesResponse{}
	mi := &file_family_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyFamiliesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyFamiliesResponse) ProtoMessage() {}

func (x *ListMyFamiliesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_family_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyFamiliesResponse.ProtoReflect.Descriptor instead.
func (*ListMyFamiliesResponse) Descriptor() ([]byte, []int) {
	return file_family_proto_rawDescGZIP(), []int{27}
}

func (x *ListMyFamiliesResponse) GetFamilies() []*Family {
	if x != nil {
		return x.Families
	}
	return nil
}

func (x *ListMyFamiliesResponse) GetMemberships() []*FamilyMember {
	if x != nil {
		return x.Memberships
	}
	return nil
}

var File_family_proto protoreflect.FileDescriptor

const file_family_proto_rawDesc = "" +
	"\n" +
	"\ffamily.proto\x12\x16familyledger.family.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb7\x01\n" +
	"\x11MemberPermissions\x12\x19\n" +
	"\bcan_view\x18\x01 \x01(\bR\acanView\x12\x1d\n" +
	"\n" +
	"can_create\x18\x02 \x01(\bR\tcanCreate\x12\x19\n" +
	"\bcan_edit\x18\x03 \x01(\bR\acanEdit\x12\x1d\n" +
	"\n" +
	"can_delete\x18\x04 \x01(\bR\tcanDelete\x12.\n" +
	"\x13can_manage_accounts\x18\x05 \x01(\bR\x11canManageAccounts\"\xa6\x02\n" +
	"\x06Family\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\tR\aownerId\x12\x1f\n" +
	"\vinvite_code\x18\x04 \x01(\tR\n" +
	"inviteCode\x12F\n" +
	"\x11invite_expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x0finviteExpiresAt\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x8b\x02\n" +
	"\fFamilyMember\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x126\n" +
	"\x04role\x18\x04 \x01(\x0e2\".familyledger.family.v1.FamilyRoleR\x04role\x12K\n" +
	"\vpermissions\x18\x05 \x01(\v2).familyledger.family.v1.MemberPermissionsR\vpermissions\x127\n" +
	"\tjoined_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bjoinedAt\")\n" +
	"\x13CreateFamilyRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"N\n" +
	"\x14CreateFamilyResponse\x126\n" +
	"\x06family\x18\x01 \x01(\v2\x1e.familyledger.family.v1.FamilyR\x06family\"4\n" +
	"\x11JoinFamilyRequest\x12\x1f\n" +
	"\vinvite_code\x18\x01 \x01(\tR\n" +
	"inviteCode\"L\n" +
	"\x12JoinFamilyResponse\x126\n" +
	"\x06family\x18\x01 \x01(\v2\x1e.familyledger.family.v1.FamilyR\x06family\"/\n" +
	"\x10GetFamilyRequest\x12\x1b\n" +
	"\tfamily_id\x18\x01 \x01(\tR\bfamilyId\"\x8b\x01\n" +
	"\x11GetFamilyResponse\x126\n" +
	"\x06family\x18\x01 \x01(\v2\x1e.familyledger.family.v1.FamilyR\x06family\x12>\n" +
	"\amembers\x18\x02 \x03(\v2$.familyledger.family.v1.FamilyMemberR\amembers\"8\n" +
	"\x19GenerateInviteCodeRequest\x12\x1b\n" +
	"\tfamily_id\x18\x01 \x01(\tR\bfamilyId\"x\n" +
	"\x1aGenerateInviteCodeResponse\x12\x1f\n" +
	"\vinvite_code\x18\x01 \x01(\tR\n" +
	"inviteCode\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\x84\x01\n" +
	"\x14SetMemberRoleRequest\x12\x1b\n" +
	"\tfamily_id\x18\x01 \x01(\tR\bfamilyId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x126\n" +
	"\x04role\x18\x03 \x01(\x0e2\".familyledger.family.v1.FamilyRoleR\x04role\"\x17\n" +
	"\x15SetMemberRoleResponse\"\xa0\x01\n" +
	"\x1bSetMemberPermissionsRequest\x12\x1b\n" +
	"\tfamily_id\x18\x01 \x01(\tR\bfamilyId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12K\n" +
	"\vpermissions\x18\x03 \x01(\v2).familyledger.family.v1.MemberPermissionsR\vpermissions\"\x1e\n" +
	"\x1cSetMemberPermissionsResponse\"7\n" +
	"\x18ListFamilyMembersRequest\x12\x1b\n" +
	"\tfamily_id\x18\x01 \x01(\tR\bfamilyId\"[\n" +
	"\x19ListFamilyMembersResponse\x12>\n" +
	"\amembers\x18\x01 \x03(\v2$.familyledger.family.v1.FamilyMemberR\amembers\"1\n" +
	"\x12LeaveFamilyRequest\x12\x1b\n" +
	"\tfamily_id\x18\x01 \x01(\tR\bfamilyId\"\x15\n" +
	"\x13LeaveFamilyResponse\"Y\n" +
	"\x18TransferOwnershipRequest\x12\x1b\n" +
	"\tfamily_id\x18\x01 \x01(\tR\bfamilyId\x12 \n" +
	"\fnew_owner_id\x18\x02 \x01(\tR\n" +
	"newOwnerId\"\x1b\n" +
	"\x19TransferOwnershipResponse\"2\n" +
	"\x13DeleteFamilyRequest\x12\x1b\n" +
	"\tfamily_id\x18\x01 \x01(\tR\bfamilyId\"\x16\n" +
	"\x14DeleteFamilyResponse\"\x8e\x01\n" +
	"\x12GetAuditLogRequest\x12\x1b\n" +
	"\tfamily_id\x18\x01 \x01(\tR\bfamilyId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\x12\x1f\n" +
	"\ventity_type\x18\x04 \x01(\tR\n" +
	"entityType\"{\n" +
	"\x13GetAuditLogResponse\x12<\n" +
	"\aentries\x18\x01 \x03(\v2\".familyledger.family.v1.AuditEntryR\aentries\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xea\x01\n" +
	"\n" +
	"AuditEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tuser_name\x18\x03 \x01(\tR\buserName\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12\x1f\n" +
	"\ventity_type\x18\x05 \x01(\tR\n" +
	"entityType\x12\x1b\n" +
	"\tentity_id\x18\x06 \x01(\tR\bentityId\x12!\n" +
	"\fchanges_json\x18\a \x01(\tR\vchangesJson\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\"\x17\n" +
	"\x15ListMyFamiliesRequest\"\x9c\x01\n" +
	"\x16ListMyFamiliesResponse\x12:\n" +
	"\bfamilies\x18\x01 \x03(\v2\x1e.familyledger.family.v1.FamilyR\bfamilies\x12F\n" +
	"\vmemberships\x18\x02 \x03(\v2$.familyledger.family.v1.FamilyMemberR\vmemberships*o\n" +
	"\n" +
	"FamilyRole\x12\x1b\n" +
	"\x17FAMILY_ROLE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11FAMILY_ROLE_OWNER\x10\x01\x12\x15\n" +
	"\x11FAMILY_ROLE_ADMIN\x10\x02\x12\x16\n" +
	"\x12FAMILY_ROLE_MEMBER\x10\x032\xd0\n" +
	"\n" +
	"\rFamilyService\x12i\n" +
	"\fCreateFamily\x12+.familyledger.family.v1.CreateFamilyRequest\x1a,.familyledger.family.v1.CreateFamilyResponse\x12c\n" +
	"\n" +
	"JoinFamily\x12).familyledger.family.v1.JoinFamilyRequest\x1a*.familyledger.family.v1.JoinFamilyResponse\x12`\n" +
	"\tGetFamily\x12(.familyledger.family.v1.GetFamilyRequest\x1a).familyledger.family.v1.GetFamilyResponse\x12o\n" +
	"\x0eListMyFamilies\x12-.familyledger.family.v1.ListMyFamiliesRequest\x1a..familyledger.family.v1.ListMyFamiliesResponse\x12{\n" +
	"\x12GenerateInviteCode\x121.familyledger.family.v1.GenerateInviteCodeRequest\x1a2.familyledger.family.v1.GenerateInviteCodeResponse\x12l\n" +
	"\rSetMemberRole\x12,.familyledger.family.v1.SetMemberRoleRequest\x1a-.familyledger.family.v1.SetMemberRoleResponse\x12\x81\x01\n" +
	"\x14SetMemberPermissions\x123.familyledger.family.v1.SetMemberPermissionsRequest\x1a4.familyledger.family.v1.SetMemberPermissionsResponse\x12x\n" +
	"\x11ListFamilyMembers\x120.familyledger.family.v1.ListFamilyMembersRequest\x1a1.familyledger.family.v1.ListFamilyMembersResponse\x12f\n" +
	"\vLeaveFamily\x12*.familyledger.family.v1.LeaveFamilyRequest\x1a+.familyledger.family.v1.LeaveFamilyResponse\x12x\n" +
	"\x11TransferOwnership\x120.familyledger.family.v1.TransferOwnershipRequest\x1a1.familyledger.family.v1.TransferOwnershipResponse\x12i\n" +
	"\fDeleteFamily\x12+.familyledger.family.v1.DeleteFamilyRequest\x1a,.familyledger.family.v1.DeleteFamilyResponse\x12f\n" +
	"\vGetAuditLog\x12*.familyledger.family.v1.GetAuditLogRequest\x1a+.familyledger.family.v1.GetAuditLogResponseB-Z+github.com/familyledger/server/proto/familyb\x06proto3"

var (
	file_family_proto_rawDescOnce sync.Once
	file_family_proto_rawDescData []byte
)

func file_family_proto_rawDescGZIP() []byte {
	file_family_proto_rawDescOnce.Do(func() {
		file_family_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_family_proto_rawDesc), len(file_family_proto_rawDesc)))
	})
	return file_family_proto_rawDescData
}

var file_family_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_family_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_family_proto_goTypes = []any{
	(FamilyRole)(0),                      // 0: familyledger.family.v1.FamilyRole
	(*MemberPermissions)(nil),            // 1: familyledger.family.v1.MemberPermissions
	(*Family)(nil),                       // 2: familyledger.family.v1.Family
	(*FamilyMember)(nil),                 // 3: familyledger.family.v1.FamilyMember
	(*CreateFamilyRequest)(nil),          // 4: familyledger.family.v1.CreateFamilyRequest
	(*CreateFamilyResponse)(nil),         // 5: familyledger.family.v1.CreateFamilyResponse
	(*JoinFamilyRequest)(nil),            // 6: familyledger.family.v1.JoinFamilyRequest
	(*JoinFamilyResponse)(nil),           // 7: familyledger.family.v1.JoinFamilyResponse
	(*GetFamilyRequest)(nil),             // 8: familyledger.family.v1.GetFamilyRequest
	(*GetFamilyResponse)(nil),            // 9: familyledger.family.v1.GetFamilyResponse
	(*GenerateInviteCodeRequest)(nil),    // 10: familyledger.family.v1.GenerateInviteCodeRequest
	(*GenerateInviteCodeResponse)(nil),   // 11: familyledger.family.v1.GenerateInviteCodeResponse
	(*SetMemberRoleRequest)(nil),         // 12: familyledger.family.v1.SetMemberRoleRequest
	(*SetMemberRoleResponse)(nil),        // 13: familyledger.family.v1.SetMemberRoleResponse
	(*SetMemberPermissionsRequest)(nil),  // 14: familyledger.family.v1.SetMemberPermissionsRequest
	(*SetMemberPermissionsResponse)(nil), // 15: familyledger.family.v1.SetMemberPermissionsResponse
	(*ListFamilyMembersRequest)(nil),     // 16: familyledger.family.v1.ListFamilyMembersRequest
	(*ListFamilyMembersResponse)(nil),    // 17: familyledger.family.v1.ListFamilyMembersResponse
	(*LeaveFamilyRequest)(nil),           // 18: familyledger.family.v1.LeaveFamilyRequest
	(*LeaveFamilyResponse)(nil),          // 19: familyledger.family.v1.LeaveFamilyResponse
	(*TransferOwnershipRequest)(nil),     // 20: familyledger.family.v1.TransferOwnershipRequest
	(*TransferOwnershipResponse)(nil),    // 21: familyledger.family.v1.TransferOwnershipResponse
	(*DeleteFamilyRequest)(nil),          // 22: familyledger.family.v1.DeleteFamilyRequest
	(*DeleteFamilyResponse)(nil),         // 23: familyledger.family.v1.DeleteFamilyResponse
	(*GetAuditLogRequest)(nil),           // 24: familyledger.family.v1.GetAuditLogRequest
	(*GetAuditLogResponse)(nil),          // 25: familyledger.family.v1.GetAuditLogResponse
	(*AuditEntry)(nil),                   // 26: familyledger.family.v1.AuditEntry
	(*ListMyFamiliesRequest)(nil),        // 27: familyledger.family.v1.ListMyFamiliesRequest
	(*ListMyFamiliesResponse)(nil),       // 28: familyledger.family.v1.ListMyFamiliesResponse
	(*timestamppb.Timestamp)(nil),        // 29: google.protobuf.Timestamp
}
var file_family_proto_depIdxs = []int32{
	29, // 0: familyledger.family.v1.Family.invite_expires_at:type_name -> google.protobuf.Timestamp
	29, // 1: familyledger.family.v1.Family.created_at:type_name -> google.protobuf.Timestamp
	29, // 2: familyledger.family.v1.Family.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 3: familyledger.family.v1.FamilyMember.role:type_name -> familyledger.family.v1.FamilyRole
	1,  // 4: familyledger.family.v1.FamilyMember.permissions:type_name -> familyledger.family.v1.MemberPermissions
	29, // 5: familyledger.family.v1.FamilyMember.joined_at:type_name -> google.protobuf.Timestamp
	2,  // 6: familyledger.family.v1.CreateFamilyResponse.family:type_name -> familyledger.family.v1.Family
	2,  // 7: familyledger.family.v1.JoinFamilyResponse.family:type_name -> familyledger.family.v1.Family
	2,  // 8: familyledger.family.v1.GetFamilyResponse.family:type_name -> familyledger.family.v1.Family
	3,  // 9: familyledger.family.v1.GetFamilyResponse.members:type_name -> familyledger.family.v1.FamilyMember
	29, // 10: familyledger.family.v1.GenerateInviteCodeResponse.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 11: familyledger.family.v1.SetMemberRoleRequest.role:type_name -> familyledger.family.v1.FamilyRole
	1,  // 12: familyledger.family.v1.SetMemberPermissionsRequest.permissions:type_name -> familyledger.family.v1.MemberPermissions
	3,  // 13: familyledger.family.v1.ListFamilyMembersResponse.members:type_name -> familyledger.family.v1.FamilyMember
	26, // 14: familyledger.family.v1.GetAuditLogResponse.entries:type_name -> familyledger.family.v1.AuditEntry
	2,  // 15: familyledger.family.v1.ListMyFamiliesResponse.families:type_name -> familyledger.family.v1.Family
	3,  // 16: familyledger.family.v1.ListMyFamiliesResponse.memberships:type_name -> familyledger.family.v1.FamilyMember
	4,  // 17: familyledger.family.v1.FamilyService.CreateFamily:input_type -> familyledger.family.v1.CreateFamilyRequest
	6,  // 18: familyledger.family.v1.FamilyService.JoinFamily:input_type -> familyledger.family.v1.JoinFamilyRequest
	8,  // 19: familyledger.family.v1.FamilyService.GetFamily:input_type -> familyledger.family.v1.GetFamilyRequest
	27, // 20: familyledger.family.v1.FamilyService.ListMyFamilies:input_type -> familyledger.family.v1.ListMyFamiliesRequest
	10, // 21: familyledger.family.v1.FamilyService.GenerateInviteCode:input_type -> familyledger.family.v1.GenerateInviteCodeRequest
	12, // 22: familyledger.family.v1.FamilyService.SetMemberRole:input_type -> familyledger.family.v1.SetMemberRoleRequest
	14, // 23: familyledger.family.v1.FamilyService.SetMemberPermissions:input_type -> familyledger.family.v1.SetMemberPermissionsRequest
	16, // 24: familyledger.family.v1.FamilyService.ListFamilyMembers:input_type -> familyledger.family.v1.ListFamilyMembersRequest
	18, // 25: familyledger.family.v1.FamilyService.LeaveFamily:input_type -> familyledger.family.v1.LeaveFamilyRequest
	20, // 26: familyledger.family.v1.FamilyService.TransferOwnership:input_type -> familyledger.family.v1.TransferOwnershipRequest
	22, // 27: familyledger.family.v1.FamilyService.DeleteFamily:input_type -> familyledger.family.v1.DeleteFamilyRequest
	24, // 28: familyledger.family.v1.FamilyService.GetAuditLog:input_type -> familyledger.family.v1.GetAuditLogRequest
	5,  // 29: familyledger.family.v1.FamilyService.CreateFamily:output_type -> familyledger.family.v1.CreateFamilyResponse
	7,  // 30: familyledger.family.v1.FamilyService.JoinFamily:output_type -> familyledger.family.v1.JoinFamilyResponse
	9,  // 31: familyledger.family.v1.FamilyService.GetFamily:output_type -> familyledger.family.v1.GetFamilyResponse
	28, // 32: familyledger.family.v1.FamilyService.ListMyFamilies:output_type -> familyledger.family.v1.ListMyFamiliesResponse
	11, // 33: familyledger.family.v1.FamilyService.GenerateInviteCode:output_type -> familyledger.family.v1.GenerateInviteCodeResponse
	13, // 34: familyledger.family.v1.FamilyService.SetMemberRole:output_type -> familyledger.family.v1.SetMemberRoleResponse
	15, // 35: familyledger.family.v1.FamilyService.SetMemberPermissions:output_type -> familyledger.family.v1.SetMemberPermissionsResponse
	17, // 36: familyledger.family.v1.FamilyService.ListFamilyMembers:output_type -> familyledger.family.v1.ListFamilyMembersResponse
	19, // 37: familyledger.family.v1.FamilyService.LeaveFamily:output_type -> familyledger.family.v1.LeaveFamilyResponse
	21, // 38: familyledger.family.v1.FamilyService.TransferOwnership:output_type -> familyledger.family.v1.TransferOwnershipResponse
	23, // 39: familyledger.family.v1.FamilyService.DeleteFamily:output_type -> familyledger.family.v1.DeleteFamilyResponse
	25, // 40: familyledger.family.v1.FamilyService.GetAuditLog:output_type -> familyledger.family.v1.GetAuditLogResponse
	29, // [29:41] is the sub-list for method output_type
	17, // [17:29] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_family_proto_init() }
func file_family_proto_init() {
	if File_family_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_family_proto_rawDesc), len(file_family_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_family_proto_goTypes,
		DependencyIndexes: file_family_proto_depIdxs,
		EnumInfos:         file_family_proto_enumTypes,
		MessageInfos:      file_family_proto_msgTypes,
	}.Build()
	File_family_proto = out.File
	file_family_proto_goTypes = nil
	file_family_proto_depIdxs = nil
}
