// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: loan.proto

package loan

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LoanService_CreateLoan_FullMethodName              = "/familyledger.loan.v1.LoanService/CreateLoan"
	LoanService_GetLoan_FullMethodName                 = "/familyledger.loan.v1.LoanService/GetLoan"
	LoanService_ListLoans_FullMethodName               = "/familyledger.loan.v1.LoanService/ListLoans"
	LoanService_UpdateLoan_FullMethodName              = "/familyledger.loan.v1.LoanService/UpdateLoan"
	LoanService_DeleteLoan_FullMethodName              = "/familyledger.loan.v1.LoanService/DeleteLoan"
	LoanService_GetLoanSchedule_FullMethodName         = "/familyledger.loan.v1.LoanService/GetLoanSchedule"
	LoanService_SimulatePrepayment_FullMethodName      = "/familyledger.loan.v1.LoanService/SimulatePrepayment"
	LoanService_ExecutePrepayment_FullMethodName       = "/familyledger.loan.v1.LoanService/ExecutePrepayment"
	LoanService_RecordRateChange_FullMethodName        = "/familyledger.loan.v1.LoanService/RecordRateChange"
	LoanService_RecordPayment_FullMethodName           = "/familyledger.loan.v1.LoanService/RecordPayment"
	LoanService_CreateLoanGroup_FullMethodName         = "/familyledger.loan.v1.LoanService/CreateLoanGroup"
	LoanService_GetLoanGroup_FullMethodName            = "/familyledger.loan.v1.LoanService/GetLoanGroup"
	LoanService_ListLoanGroups_FullMethodName          = "/familyledger.loan.v1.LoanService/ListLoanGroups"
	LoanService_SimulateGroupPrepayment_FullMethodName = "/familyledger.loan.v1.LoanService/SimulateGroupPrepayment"
	LoanService_ExecuteGroupPrepayment_FullMethodName  = "/familyledger.loan.v1.LoanService/ExecuteGroupPrepayment"
)

// LoanServiceClient is the client API for LoanService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LoanServiceClient interface {
	CreateLoan(ctx context.Context, in *CreateLoanRequest, opts ...grpc.CallOption) (*Loan, error)
	GetLoan(ctx context.Context, in *GetLoanRequest, opts ...grpc.CallOption) (*Loan, error)
	ListLoans(ctx context.Context, in *ListLoansRequest, opts ...grpc.CallOption) (*ListLoansResponse, error)
	UpdateLoan(ctx context.Context, in *UpdateLoanRequest, opts ...grpc.CallOption) (*Loan, error)
	DeleteLoan(ctx context.Context, in *DeleteLoanRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetLoanSchedule(ctx context.Context, in *GetLoanScheduleRequest, opts ...grpc.CallOption) (*LoanScheduleResponse, error)
	SimulatePrepayment(ctx context.Context, in *SimulatePrepaymentRequest, opts ...grpc.CallOption) (*PrepaymentSimulation, error)
	ExecutePrepayment(ctx context.Context, in *ExecutePrepaymentRequest, opts ...grpc.CallOption) (*ExecutePrepaymentResponse, error)
	RecordRateChange(ctx context.Context, in *RecordRateChangeRequest, opts ...grpc.CallOption) (*Loan, error)
	RecordPayment(ctx context.Context, in *RecordPaymentRequest, opts ...grpc.CallOption) (*LoanScheduleItem, error)
	// ── Loan Group (组合贷款) ────────────────────────────────────────────
	CreateLoanGroup(ctx context.Context, in *CreateLoanGroupRequest, opts ...grpc.CallOption) (*LoanGroup, error)
	GetLoanGroup(ctx context.Context, in *GetLoanGroupRequest, opts ...grpc.CallOption) (*LoanGroup, error)
	ListLoanGroups(ctx context.Context, in *ListLoanGroupsRequest, opts ...grpc.CallOption) (*ListLoanGroupsResponse, error)
	SimulateGroupPrepayment(ctx context.Context, in *SimulateGroupPrepaymentRequest, opts ...grpc.CallOption) (*GroupPrepaymentSimulation, error)
	ExecuteGroupPrepayment(ctx context.Context, in *ExecuteGroupPrepaymentRequest, opts ...grpc.CallOption) (*ExecuteGroupPrepaymentResponse, error)
}

type loanServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLoanServiceClient(cc grpc.ClientConnInterface) LoanServiceClient {
	return &loanServiceClient{cc}
}

func (c *loanServiceClient) CreateLoan(ctx context.Context, in *CreateLoanRequest, opts ...grpc.CallOption) (*Loan, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Loan)
	err := c.cc.Invoke(ctx, LoanService_CreateLoan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanServiceClient) GetLoan(ctx context.Context, in *GetLoanRequest, opts ...grpc.CallOption) (*Loan, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Loan)
	err := c.cc.Invoke(ctx, LoanService_GetLoan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanServiceClient) ListLoans(ctx context.Context, in *ListLoansRequest, opts ...grpc.CallOption) (*ListLoansResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLoansResponse)
	err := c.cc.Invoke(ctx, LoanService_ListLoans_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanServiceClient) UpdateLoan(ctx context.Context, in *UpdateLoanRequest, opts ...grpc.CallOption) (*Loan, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Loan)
	err := c.cc.Invoke(ctx, LoanService_UpdateLoan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanServiceClient) DeleteLoan(ctx context.Context, in *DeleteLoanRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, LoanService_DeleteLoan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanServiceClient) GetLoanSchedule(ctx context.Context, in *GetLoanScheduleRequest, opts ...grpc.CallOption) (*LoanScheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoanScheduleResponse)
	err := c.cc.Invoke(ctx, LoanService_GetLoanSchedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanServiceClient) SimulatePrepayment(ctx context.Context, in *SimulatePrepaymentRequest, opts ...grpc.CallOption) (*PrepaymentSimulation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrepaymentSimulation)
	err := c.cc.Invoke(ctx, LoanService_SimulatePrepayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanServiceClient) ExecutePrepayment(ctx context.Context, in *ExecutePrepaymentRequest, opts ...grpc.CallOption) (*ExecutePrepaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecutePrepaymentResponse)
	err := c.cc.Invoke(ctx, LoanService_ExecutePrepayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanServiceClient) RecordRateChange(ctx context.Context, in *RecordRateChangeRequest, opts ...grpc.CallOption) (*Loan, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Loan)
	err := c.cc.Invoke(ctx, LoanService_RecordRateChange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanServiceClient) RecordPayment(ctx context.Context, in *RecordPaymentRequest, opts ...grpc.CallOption) (*LoanScheduleItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoanScheduleItem)
	err := c.cc.Invoke(ctx, LoanService_RecordPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanServiceClient) CreateLoanGroup(ctx context.Context, in *CreateLoanGroupRequest, opts ...grpc.CallOption) (*LoanGroup, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoanGroup)
	err := c.cc.Invoke(ctx, LoanService_CreateLoanGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanServiceClient) GetLoanGroup(ctx context.Context, in *GetLoanGroupRequest, opts ...grpc.CallOption) (*LoanGroup, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoanGroup)
	err := c.cc.Invoke(ctx, LoanService_GetLoanGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanServiceClient) ListLoanGroups(ctx context.Context, in *ListLoanGroupsRequest, opts ...grpc.CallOption) (*ListLoanGroupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLoanGroupsResponse)
	err := c.cc.Invoke(ctx, LoanService_ListLoanGroups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanServiceClient) SimulateGroupPrepayment(ctx context.Context, in *SimulateGroupPrepaymentRequest, opts ...grpc.CallOption) (*GroupPrepaymentSimulation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupPrepaymentSimulation)
	err := c.cc.Invoke(ctx, LoanService_SimulateGroupPrepayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanServiceClient) ExecuteGroupPrepayment(ctx context.Context, in *ExecuteGroupPrepaymentRequest, opts ...grpc.CallOption) (*ExecuteGroupPrepaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteGroupPrepaymentResponse)
	err := c.cc.Invoke(ctx, LoanService_ExecuteGroupPrepayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoanServiceServer is the server API for LoanService service.
// All implementations must embed UnimplementedLoanServiceServer
// for forward compatibility.
type LoanServiceServer interface {
	CreateLoan(context.Context, *CreateLoanRequest) (*Loan, error)
	GetLoan(context.Context, *GetLoanRequest) (*Loan, error)
	ListLoans(context.Context, *ListLoansRequest) (*ListLoansResponse, error)
	UpdateLoan(context.Context, *UpdateLoanRequest) (*Loan, error)
	DeleteLoan(context.Context, *DeleteLoanRequest) (*emptypb.Empty, error)
	GetLoanSchedule(context.Context, *GetLoanScheduleRequest) (*LoanScheduleResponse, error)
	SimulatePrepayment(context.Context, *SimulatePrepaymentRequest) (*PrepaymentSimulation, error)
	ExecutePrepayment(context.Context, *ExecutePrepaymentRequest) (*ExecutePrepaymentResponse, error)
	RecordRateChange(context.Context, *RecordRateChangeRequest) (*Loan, error)
	RecordPayment(context.Context, *RecordPaymentRequest) (*LoanScheduleItem, error)
	// ── Loan Group (组合贷款) ────────────────────────────────────────────
	CreateLoanGroup(context.Context, *CreateLoanGroupRequest) (*LoanGroup, error)
	GetLoanGroup(context.Context, *GetLoanGroupRequest) (*LoanGroup, error)
	ListLoanGroups(context.Context, *ListLoanGroupsRequest) (*ListLoanGroupsResponse, error)
	SimulateGroupPrepayment(context.Context, *SimulateGroupPrepaymentRequest) (*GroupPrepaymentSimulation, error)
	ExecuteGroupPrepayment(context.Context, *ExecuteGroupPrepaymentRequest) (*ExecuteGroupPrepaymentResponse, error)
	mustEmbedUnimplementedLoanServiceServer()
}

// UnimplementedLoanServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLoanServiceServer struct{}

func (UnimplementedLoanServiceServer) CreateLoan(context.Context, *CreateLoanRequest) (*Loan, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateLoan not implemented")
}
func (UnimplementedLoanServiceServer) GetLoan(context.Context, *GetLoanRequest) (*Loan, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLoan not implemented")
}
func (UnimplementedLoanServiceServer) ListLoans(context.Context, *ListLoansRequest) (*ListLoansResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLoans not implemented")
}
func (UnimplementedLoanServiceServer) UpdateLoan(context.Context, *UpdateLoanRequest) (*Loan, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateLoan not implemented")
}
func (UnimplementedLoanServiceServer) DeleteLoan(context.Context, *DeleteLoanRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteLoan not implemented")
}
func (UnimplementedLoanServiceServer) GetLoanSchedule(context.Context, *GetLoanScheduleRequest) (*LoanScheduleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLoanSchedule not implemented")
}
func (UnimplementedLoanServiceServer) SimulatePrepayment(context.Context, *SimulatePrepaymentRequest) (*PrepaymentSimulation, error) {
	return nil, status.Error(codes.Unimplemented, "method SimulatePrepayment not implemented")
}
func (UnimplementedLoanServiceServer) ExecutePrepayment(context.Context, *ExecutePrepaymentRequest) (*ExecutePrepaymentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecutePrepayment not implemented")
}
func (UnimplementedLoanServiceServer) RecordRateChange(context.Context, *RecordRateChangeRequest) (*Loan, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordRateChange not implemented")
}
func (UnimplementedLoanServiceServer) RecordPayment(context.Context, *RecordPaymentRequest) (*LoanScheduleItem, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordPayment not implemented")
}
func (UnimplementedLoanServiceServer) CreateLoanGroup(context.Context, *CreateLoanGroupRequest) (*LoanGroup, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateLoanGroup not implemented")
}
func (UnimplementedLoanServiceServer) GetLoanGroup(context.Context, *GetLoanGroupRequest) (*LoanGroup, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLoanGroup not implemented")
}
func (UnimplementedLoanServiceServer) ListLoanGroups(context.Context, *ListLoanGroupsRequest) (*ListLoanGroupsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLoanGroups not implemented")
}
func (UnimplementedLoanServiceServer) SimulateGroupPrepayment(context.Context, *SimulateGroupPrepaymentRequest) (*GroupPrepaymentSimulation, error) {
	return nil, status.Error(codes.Unimplemented, "method SimulateGroupPrepayment not implemented")
}
func (UnimplementedLoanServiceServer) ExecuteGroupPrepayment(context.Context, *ExecuteGroupPrepaymentRequest) (*ExecuteGroupPrepaymentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteGroupPrepayment not implemented")
}
func (UnimplementedLoanServiceServer) mustEmbedUnimplementedLoanServiceServer() {}
func (UnimplementedLoanServiceServer) testEmbeddedByValue()                     {}

// UnsafeLoanServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LoanServiceServer will
// result in compilation errors.
type UnsafeLoanServiceServer interface {
	mustEmbedUnimplementedLoanServiceServer()
}

func RegisterLoanServiceServer(s grpc.ServiceRegistrar, srv LoanServiceServer) {
	// If the following call panics, it indicates UnimplementedLoanServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LoanService_ServiceDesc, srv)
}

func _LoanService_CreateLoan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLoanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanServiceServer).CreateLoan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanService_CreateLoan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanServiceServer).CreateLoan(ctx, req.(*CreateLoanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanService_GetLoan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLoanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanServiceServer).GetLoan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanService_GetLoan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanServiceServer).GetLoan(ctx, req.(*GetLoanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanService_ListLoans_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLoansRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanServiceServer).ListLoans(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanService_ListLoans_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanServiceServer).ListLoans(ctx, req.(*ListLoansRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanService_UpdateLoan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLoanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanServiceServer).UpdateLoan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanService_UpdateLoan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanServiceServer).UpdateLoan(ctx, req.(*UpdateLoanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanService_DeleteLoan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteLoanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanServiceServer).DeleteLoan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanService_DeleteLoan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanServiceServer).DeleteLoan(ctx, req.(*DeleteLoanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanService_GetLoanSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLoanScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanServiceServer).GetLoanSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanService_GetLoanSchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanServiceServer).GetLoanSchedule(ctx, req.(*GetLoanScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanService_SimulatePrepayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimulatePrepaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanServiceServer).SimulatePrepayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanService_SimulatePrepayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanServiceServer).SimulatePrepayment(ctx, req.(*SimulatePrepaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanService_ExecutePrepayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecutePrepaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanServiceServer).ExecutePrepayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanService_ExecutePrepayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanServiceServer).ExecutePrepayment(ctx, req.(*ExecutePrepaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanService_RecordRateChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordRateChangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanServiceServer).RecordRateChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanService_RecordRateChange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanServiceServer).RecordRateChange(ctx, req.(*RecordRateChangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanService_RecordPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanServiceServer).RecordPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanService_RecordPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanServiceServer).RecordPayment(ctx, req.(*RecordPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanService_CreateLoanGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLoanGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanServiceServer).CreateLoanGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanService_CreateLoanGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanServiceServer).CreateLoanGroup(ctx, req.(*CreateLoanGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanService_GetLoanGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLoanGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanServiceServer).GetLoanGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanService_GetLoanGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanServiceServer).GetLoanGroup(ctx, req.(*GetLoanGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanService_ListLoanGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLoanGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanServiceServer).ListLoanGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanService_ListLoanGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanServiceServer).ListLoanGroups(ctx, req.(*ListLoanGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanService_SimulateGroupPrepayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimulateGroupPrepaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanServiceServer).SimulateGroupPrepayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanService_SimulateGroupPrepayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanServiceServer).SimulateGroupPrepayment(ctx, req.(*SimulateGroupPrepaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanService_ExecuteGroupPrepayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteGroupPrepaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanServiceServer).ExecuteGroupPrepayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanService_ExecuteGroupPrepayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanServiceServer).ExecuteGroupPrepayment(ctx, req.(*ExecuteGroupPrepaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LoanService_ServiceDesc is the grpc.ServiceDesc for LoanService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LoanService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "familyledger.loan.v1.LoanService",
	HandlerType: (*LoanServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLoan",
			Handler:    _LoanService_CreateLoan_Handler,
		},
		{
			MethodName: "GetLoan",
			Handler:    _LoanService_GetLoan_Handler,
		},
		{
			MethodName: "ListLoans",
			Handler:    _LoanService_ListLoans_Handler,
		},
		{
			MethodName: "UpdateLoan",
			Handler:    _LoanService_UpdateLoan_Handler,
		},
		{
			MethodName: "DeleteLoan",
			Handler:    _LoanService_DeleteLoan_Handler,
		},
		{
			MethodName: "GetLoanSchedule",
			Handler:    _LoanService_GetLoanSchedule_Handler,
		},
		{
			MethodName: "SimulatePrepayment",
			Handler:    _LoanService_SimulatePrepayment_Handler,
		},
		{
			MethodName: "ExecutePrepayment",
			Handler:    _LoanService_ExecutePrepayment_Handler,
		},
		{
			MethodName: "RecordRateChange",
			Handler:    _LoanService_RecordRateChange_Handler,
		},
		{
			MethodName: "RecordPayment",
			Handler:    _LoanService_RecordPayment_Handler,
		},
		{
			MethodName: "CreateLoanGroup",
			Handler:    _LoanService_CreateLoanGroup_Handler,
		},
		{
			MethodName: "GetLoanGroup",
			Handler:    _LoanService_GetLoanGroup_Handler,
		},
		{
			MethodName: "ListLoanGroups",
			Handler:    _LoanService_ListLoanGroups_Handler,
		},
		{
			MethodName: "SimulateGroupPrepayment",
			Handler:    _LoanService_SimulateGroupPrepayment_Handler,
		},
		{
			MethodName: "ExecuteGroupPrepayment",
			Handler:    _LoanService_ExecuteGroupPrepayment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "loan.proto",
}
