// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/export.proto

package export

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FamilyId      string                 `protobuf:"bytes,2,opt,name=family_id,json=familyId,proto3" json:"family_id,omitempty"`
	Format        string                 `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`                        // csv / excel / pdf
	StartDate     string                 `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"` // ISO date
	EndDate       string                 `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	CategoryIds   []string               `protobuf:"bytes,6,rep,name=category_ids,json=categoryIds,proto3" json:"category_ids,omitempty"` // 空=全部
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportRequest) Reset() {
	*x = ExportRequest{}
	mi := &file_proto_export_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportRequest) ProtoMessage() {}

func (x *ExportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_export_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportRequest.ProtoReflect.Descriptor instead.
func (*ExportRequest) Descriptor() ([]byte, []int) {
	return file_proto_export_proto_rawDescGZIP(), []int{0}
}

func (x *ExportRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ExportRequest) GetFamilyId() string {
	if x != nil {
		return x.FamilyId
	}
	return ""
}

func (x *ExportRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *ExportRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *ExportRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *ExportRequest) GetCategoryIds() []string {
	if x != nil {
		return x.CategoryIds
	}
	return nil
}

type ExportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportResponse) Reset() {
	*x = ExportResponse{}
	mi := &file_proto_export_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportResponse) ProtoMessage() {}

func (x *ExportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_export_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportResponse.ProtoReflect.Descriptor instead.
func (*ExportResponse) Descriptor() ([]byte, []int) {
	return file_proto_export_proto_rawDescGZIP(), []int{1}
}

func (x *ExportResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ExportResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ExportResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type FullBackupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FamilyId      string                 `protobuf:"bytes,1,opt,name=family_id,json=familyId,proto3" json:"family_id,omitempty"` // optional: empty = personal backup
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FullBackupRequest) Reset() {
	*x = FullBackupRequest{}
	mi := &file_proto_export_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FullBackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullBackupRequest) ProtoMessage() {}

func (x *FullBackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_export_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullBackupRequest.ProtoReflect.Descriptor instead.
func (*FullBackupRequest) Descriptor() ([]byte, []int) {
	return file_proto_export_proto_rawDescGZIP(), []int{2}
}

func (x *FullBackupRequest) GetFamilyId() string {
	if x != nil {
		return x.FamilyId
	}
	return ""
}

type FullBackupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`     // JSON encoded full backup
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"` // "json"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FullBackupResponse) Reset() {
	*x = FullBackupResponse{}
	mi := &file_proto_export_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FullBackupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullBackupResponse) ProtoMessage() {}

func (x *FullBackupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_export_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullBackupResponse.ProtoReflect.Descriptor instead.
func (*FullBackupResponse) Descriptor() ([]byte, []int) {
	return file_proto_export_proto_rawDescGZIP(), []int{3}
}

func (x *FullBackupResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FullBackupResponse) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

var File_proto_export_proto protoreflect.FileDescriptor

const file_proto_export_proto_rawDesc = "" +
	"\n" +
	"\x12proto/export.proto\x12\x16familyledger.export.v1\"\xba\x01\n" +
	"\rExportRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tfamily_id\x18\x02 \x01(\tR\bfamilyId\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\x12\x1d\n" +
	"\n" +
	"start_date\x18\x04 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x05 \x01(\tR\aendDate\x12!\n" +
	"\fcategory_ids\x18\x06 \x03(\tR\vcategoryIds\"c\n" +
	"\x0eExportResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\"0\n" +
	"\x11FullBackupRequest\x12\x1b\n" +
	"\tfamily_id\x18\x01 \x01(\tR\bfamilyId\"@\n" +
	"\x12FullBackupResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format2\xd9\x01\n" +
	"\rExportService\x12c\n" +
	"\x12ExportTransactions\x12%.familyledger.export.v1.ExportRequest\x1a&.familyledger.export.v1.ExportResponse\x12c\n" +
	"\n" +
	"FullBackup\x12).familyledger.export.v1.FullBackupRequest\x1a*.familyledger.export.v1.FullBackupResponseB-Z+github.com/familyledger/server/proto/exportb\x06proto3"

var (
	file_proto_export_proto_rawDescOnce sync.Once
	file_proto_export_proto_rawDescData []byte
)

func file_proto_export_proto_rawDescGZIP() []byte {
	file_proto_export_proto_rawDescOnce.Do(func() {
		file_proto_export_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_export_proto_rawDesc), len(file_proto_export_proto_rawDesc)))
	})
	return file_proto_export_proto_rawDescData
}

var file_proto_export_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_export_proto_goTypes = []any{
	(*ExportRequest)(nil),      // 0: familyledger.export.v1.ExportRequest
	(*ExportResponse)(nil),     // 1: familyledger.export.v1.ExportResponse
	(*FullBackupRequest)(nil),  // 2: familyledger.export.v1.FullBackupRequest
	(*FullBackupResponse)(nil), // 3: familyledger.export.v1.FullBackupResponse
}
var file_proto_export_proto_depIdxs = []int32{
	0, // 0: familyledger.export.v1.ExportService.ExportTransactions:input_type -> familyledger.export.v1.ExportRequest
	2, // 1: familyledger.export.v1.ExportService.FullBackup:input_type -> familyledger.export.v1.FullBackupRequest
	1, // 2: familyledger.export.v1.ExportService.ExportTransactions:output_type -> familyledger.export.v1.ExportResponse
	3, // 3: familyledger.export.v1.ExportService.FullBackup:output_type -> familyledger.export.v1.FullBackupResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_export_proto_init() }
func file_proto_export_proto_init() {
	if File_proto_export_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_export_proto_rawDesc), len(file_proto_export_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_export_proto_goTypes,
		DependencyIndexes: file_proto_export_proto_depIdxs,
		MessageInfos:      file_proto_export_proto_msgTypes,
	}.Build()
	File_proto_export_proto = out.File
	file_proto_export_proto_goTypes = nil
	file_proto_export_proto_depIdxs = nil
}
